### ISSUE TITLE
Support multi availability zone deployments on AWS

### ISSUE THREAD

**Issue by vyshane** [coreos/coreos-kubernetes#100]
In addition to supporting HA masters by default (#90), it would also be good to have support for multi AZ deployments on AWS. A minimal HA setup would be 3 master nodes on 3 different AZs, with worker nodes also on different AZs.

**Comment by ivankennethwang** [comment]
+1

**Comment by danielwhatmuff** [comment]
+1

**Comment by four43** [comment]
+1 This is a great idea. Having to add subnets and modify the autoscaling group after that fact is kind of a bummer. I'm assuming that's where some of the complexity lies...

**Comment by arkkanoid** [comment]
+1

**Comment by mumoshu** [comment]
Hi, I have sent the PR https://github.com/coreos/coreos-kubernetes/pull/439 for this.
Does it seem to solve your problem?

**Comment by four43** [comment]
What a pull request! It has example snippets and a screenshot. Nice! That looks like it would work for my use case.

**Comment by tigrawap** [comment]
Regarding https://github.com/coreos/coreos-kubernetes/pull/439  
Kubernetes itself does not support multi-AZ   
Provisioning workers alone does not solve the problem, there are more to it, for example AZ-bound EBS

See https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federation.md

**Comment by borsboom** [comment]
The [changelog for Kubernetes v1.2.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#major-themes) says:

> Kubernetes clusters can now span zones within a cloud provider. Pods from a service will be automatically spread across zones, enabling applications to tolerate zone failure.

Does that not apply to AWS?

**Comment by four43** [comment]
We run a multi-az setup with our cluster. It's a fairly small cluster, but Kubernetes will avoid putting pods for the same rc on the same node. There is no guarantee however that those 2 nodes will be in different AZs. It sounds like that's planned for 1.2 however.

**Comment by brandonweeks** [comment]
http://blog.kubernetes.io/2016/03/building-highly-available-applications-using-Kubernetes-new-multi-zone-clusters-a.k.a-Ubernetes-Lite.html

"Ubernetes Lite" is already present in Kubernetes 1.2, however @tigrawap is correct in saying this doesn't support persistent storage across AZs.

**Comment by four43** [comment]
@brandonweeks - Storage was a mess for us, ended up using a different networked solution that resides on a different cluster completely. Glad to see the Kubernetes team addressing these issues.

**Comment by brandonweeks** [comment]
Keep an eye on kubernetes/kubernetes#21931 and kubernetes/kubernetes#20262 which are slated to land in Kubernetes 1.3.

**Comment by dmytroleonenko** [comment]
any update?

**Comment by pieterlange** [comment]
@dmytroleonenko you can spin up worker nodes in multiple AZ's. See https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cluster.yaml#L87

HA (multi-AZ) control plane is landing in an `experimental` branch soon-ish, but i can confirm it works well. See #596 and #608

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
