### ISSUE TITLE
Network CIDRs should be a cluster.yaml setting

### ISSUE THREAD

**Issue by dysinger** [coreos/coreos-kubernetes#109]
It would be nice to be able to pick a different network CIDR for the kubernetes VPC without having to recompile `kube-aws` & maintain a copy of the artifact files in a bucket.

https://github.com/coreos/coreos-kubernetes/pull/108

**Comment by dysinger** [comment]
http://blog.thestateofme.com/2014/05/27/beware_the_default_network/

**Comment by phemmer** [comment]
Note, the `10.0.0.0/8` subnet is hard-coded into kubernetes itself: https://github.com/kubernetes/kubernetes/blob/e2679abdb8a38768800e1de7beb468954b9e6e20/pkg/kubelet/container_bridge.go#L127

**Comment by colhom** [comment]
i have a pr up for this
https://github.com/coreos/coreos-kubernetes/pull/190

**Comment by aaronlevy** [comment]
Closing, as the configurable VPC changes were merged.
