### ISSUE TITLE
docs: expand thinking around master nodes and register=false

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#111]
An "I wish" reported from coreos.com/kubernetes/docs/latest/deploy-master.html

> I wish this page explained why register-node is false and talks about the errors in the kubelet logs

Sounds like we need to cover two things a bit more clearly:

1. register is false so that user pods don't land on the master machine(s). expand on the strategy/thinking behind this. maybe a trade off for when you'd want to do this
2. explicitly state that these logs are harmless and what causes them. related: https://github.com/coreos/coreos-kubernetes/issues/56

**Comment by joshix** [comment]
Closed by https://github.com/coreos/coreos-kubernetes/pull/128
