### ISSUE TITLE
docs: there is no `kube-aws describe` subcommand

### ISSUE THREAD

**Issue by vdemario** [coreos/coreos-kubernetes#114]
I'm following the tutorial on https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html and the command `kube-aws describe` is mentioned twice. However, using release 0.1.0, this subcommand does not exist:

    $ kube-aws describe
    Error: unknown command "describe" for "kube-aws"
    Run 'kube-aws --help' for usage.
    
    $ kube-aws --help
    Manage Kubernetes clusters on AWS

    Usage: 
      kube-aws [command]

    Available Commands: 
      destroy     Destroy an existing Kubernetes cluster
      render      Render a CloudFormation template
      status      Describe an existing Kubernetes cluster
      up          Create a new Kubernetes cluster
      version     Print version information and exit
      help        Help about any command

    Flags:
          --aws-debug[=false]: Log debug information from aws-sdk-go library
          --config="cluster.yaml": Location of kube-aws cluster config file
      -h, --help[=false]: help for kube-aws

    Use "kube-aws [command] --help" for more information about a command.

    $ kube-aws version
    kube-aws version v0.1.0

I'm not sure if this command was renamed to `kube-aws status` or if it simply does not exist.

I'd be happy to submit a PR to fix the docs changing `describe` to `status` or to remove the mentions altogether depending on what happened.

**Comment by aaronlevy** [comment]
Resolved by: https://github.com/coreos/coreos-kubernetes/pull/91
