### ISSUE TITLE
Kuberentes OpenSSL guide MASTER_HOST confusion.

### ISSUE THREAD

**Issue by drocsid** [coreos/coreos-kubernetes#115]
In the document https://coreos.com/kubernetes/docs/latest/openssl.html at the begging it states that MASTER_HOST can be set to "the publicly routable IP or hostname of the master cluster." Then in the OpenSSL Config section It shows IP.2 = ${MASTER_HOST} .

Since IP.2 imples an IP address, and not a hostname, after discussion on IRC, IP.2 should not be set to a hostname. However we can use ${MASTER_DNS_NAME}, which is not mentioned above.

**Comment by drocsid** [comment]
Furthermore, you might suggest not using IPs at all, but configuring only DNS_NAMES instead, for a more dynamic environment.

**Comment by aaronlevy** [comment]
Docs have been updated with examples for both IP and DNS SANs: [openssl-config](https://coreos.com/kubernetes/docs/latest/openssl.html#openssl-config)
