### ISSUE TITLE
Tag nodes in AWS after kubelet registration with instance-type

### ISSUE THREAD

**Issue by eliaslevy** [coreos/coreos-kubernetes#120]
That way if you have a cluster with mixed node types you can target node types using `nodeSelector`.  This would require changes to `kubelet.service` unit installed by `multi-node/aws/artifacts/scripts/install-worker.sh`.

Similarly, it would be a good idea to automatically add tags for other EC2 metadata such as `placement/availability-zone` and `ami-id`.  The tags could be namespaces under `as.amazon.com`.  E.g. `aws.amazon.com:instance-type`.

**Comment by aaronlevy** [comment]
Nodes can be labeled after registration: `kubectl label nodes <nodename> disktype=ssd`,  which can then be used for nodeSelectors in pods.

Also, some specific labels have also been added upstream: https://github.com/justinsb/kubernetes/commit/b2c2d617cf09fcc809b7e5e70f68d8fd622d1c58

But given this is something that is currently managed either by upstream changes, or after a cluster is running, I don't think this is something we can resolve here.

**Comment by therc** [comment]
BTW, this is close to being done upstream: https://github.com/kubernetes/kubernetes/pull/20909
