### ISSUE TITLE
deploy-master.md kube-controller-master.yaml path incorrect

### ISSUE THREAD

**Issue by rvm2015** [coreos/coreos-kubernetes#123]
/srv/kubernetes/manifests/kube-controller-manager.yaml

Should be 

/etc/kubernetes/manifests/kube-controller-manager.yaml (notice the etc instead of srv)

Multiple places in the document.

**Comment by rvm2015** [comment]
Looks like there are other places that have /srv instead of /etc, a grep will find them.

This is for the version live at https://coreos.com/kubernetes/docs/latest/deploy-master.html

**Comment by rvm2015** [comment]
Looking deeper into some of these configs I could be mistaken, are there supposed to be /*/kubernetes/manifests directories under both /etc and /srv? Reasoning?

**Comment by drocsid** [comment]
https://github.com/coreos/coreos-kubernetes/pull/126

**Comment by bcwaldon** [comment]
Not a bug, see justification in #126
