### ISSUE TITLE
docs: use generic cluster/user/context names in kubectl docs

### ISSUE THREAD

**Issue by aaronlevy** [coreos/coreos-kubernetes#124]
In these docs (https://coreos.com/kubernetes/docs/latest/configure-kubectl.html) we use the name "vagrant", but these are generic kubectl docs (vagrant guides have their own copies of this info). 

Maybe change examples to:
cluster=default-cluster
user=default-user
context=default-context

**Comment by robszumski** [comment]
Referenced here as well: https://github.com/coreos/coreos-kubernetes/issues/97#issuecomment-149297534
