### ISSUE TITLE
Native GlusterFS support

### ISSUE THREAD

**Issue by fischerman** [coreos/coreos-kubernetes#131]
Do you have plans to include the GlusterFS client in the CoreOS image to support Kubernetes GlusterFS volumes?

**Comment by aaronlevy** [comment]
Hi @fischerman,

That is probably a question to ask the OS team specifically. If you still have questions about this, please open an issue here: https://github.com/coreos/bugs

This project uses CoreOS as the underlying OS, but this issue queue is somewhat out of scope for what is included in the OS itself.
