### ISSUE TITLE
Secure AWS Deployments with a VPN

### ISSUE THREAD

**Issue by eliaslevy** [coreos/coreos-kubernetes#137]
Currently the AWS deployment allows incoming connections from the Internet to the controller on ports 22 and 443 and to the works on port 22.  It would be nice if there was the option to set up a VPN along with Kubernetes, and lock down the security group ingress rules to only allow connections from within the VPC.

[Here](https://gist.github.com/eliaslevy/bda1a3ae2588661e7121) you can find a CloudFormation template that instantiates an OpenVPN access server on an existing VPC that already has an Internet gateway.  It could be integrated into the Kubernetes CF template while tightening down the ingress security groups.

After that, one only needs to SSH to the VPN instance as `openvpnas`, change the password for the `openvpn` user, visit `https://[elastic_ip]:943/admin` to change any configuration, visit `https://[elastic_ip]` to download the VPN profile, import the profile into your VPN client (e.g. Tunnelblick), and connect to the VPN.

**Comment by pikeas** [comment]
+1!

**Comment by aaronlevy** [comment]
As mentioned in the PR, I think configuring a VPN instance is outside the scope of this project, and is something that should be left to the user to decide.

**Comment by pikeas** [comment]
@aaronlevy The default `kube-up` cluster is too open (eg, ssh and the k8s API open to the world). This access *needs* to be tightened down, which will consequently make interacting with the cluster harder. So, either a) a proper VPN should be part of the default setup, b) kube-proxy should be used for all cluster interactions and documented as such, with a corresponding or other backing service to enable this, or c) pointers in a "how to get your cluster production ready" doc describing a/b/other.

If services like Heapster and ELK are available out of the box for cluster monitoring, surely a VPN should be available out of the box for cluster *access*? It all falls under the umbrella of cluster management.

**Comment by aaronlevy** [comment]
The core motivation of this project is to launch a baseline Kubernetes cluster on CoreOS, from which users can then build on for their particular needs / infrastructure. In the case of services/addons such as Heapster, we still leave this up to the end-user to decide to run. We do automatically deploy the DNS addon, as this is essentially required for a fully functioning Kubernetes cluster.

This isn't to say this will always be the case, and additional services / addons / documentation can be integrated, but I don't think deciding that a user should use a VPN for cluster access is something this project can assume.
