### ISSUE TITLE
 no such host error

### ISSUE THREAD

**Issue by svennela** [coreos/coreos-kubernetes#151]
Hi,

I am doing kube-aws up running into below error.
my cluster.yml
keyName:
  ks-coreos

region:
  us-east-1a

externalDNSName:
  ks.ngcloudapps.com

./kube-aws up
Initialized TLS infrastructure
Wrote kubeconfig to /Users/pivotal/workspace/paas/ks-coreos-aws/clusters/kubernetes/kubeconfig
Waiting for cluster creation...
Failed creating cluster: RequestError: send request failed
caused by: Post https://cloudformation.us-east-1a.amazonaws.com/: dial tcp: lookup cloudformation.us-east-1a.amazonaws.com: no such host

**Comment by ankitforcode** [comment]
Region should be us-east-1 not us-east-1a

**Comment by aaronlevy** [comment]
Going to close this issue, as @ankitforcode mentions, the AZ should be configured separately from the region. Please re-open if you are still having trouble.
