### ISSUE TITLE
Allow me to provide my own certs when calling `kube-aws up`

### ISSUE THREAD

**Issue by iameli** [coreos/coreos-kubernetes#161]
The docs for `kube-aws` read:

> PRODUCTION NOTE: the TLS keys and certificates generated by kube-aws should not be used to deploy a production Kubernetes cluster. Each component certificate is only valid for 90 days, while the CA is valid for 365 days. If deploying a production Kubernetes cluster, consider establishing PKI independently of this tool first.

I have done this, but I don't believe there's a way for me to ask `kube-aws` to use my certs instead of auto-generating them.

Is it intended in this case that I'd just use `kube-aws render` and call the CloudFormation myself?

**Comment by abevoelker** [comment]
I would also like some clarification on this. I'm so grateful for the work that has been done here with the `kube-aws` tool and documentation - it makes things very easy! But I feel like I'm ready to take the next step towards a production setup and am curious what the recommended way to do that is.

**Comment by iameli** [comment]
FWIW we ended up just using the CloudFormation scripts and calling them
with the `aws cloudformation` CLI. Worked fine.

**Comment by aaronlevy** [comment]
Specifying custom TLS assets are not currently exposed via the kube-up script. However, @iameli is correct that you can use the cloud-formation template directly.

Keeping this open to track adding custom TLS assets.

**Comment by listx** [comment]
+1.

**Comment by bencpeters** [comment]
@iameli Can you post an example of how you used the the `aws cloudformation` CLI with your own certs?

Thanks!

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
