### ISSUE TITLE
Possible not to mandate TLS for Kube cluster with cloudformation

### ISSUE THREAD

**Issue by sachingharge** [coreos/coreos-kubernetes#167]
Hi Team,

Is it possible not to mandate TLS for Kubernetes cluster because sometime certificate can take some time?

**Comment by aaronlevy** [comment]
Hi @sachingharge,

Providing an insecure-by-default cluster is not a goal of this project. It is likely possible, but it would require many "workarounds" in various parts of kubernetes to accomplish this. For example, the kube-dns addon by default relies on service accounts, which rely on TLS assets.

For development purposes the kube-aws tool will auto-generate TLS assets for you, and for production infrastructure, generating the assets is a very important part of securing your cluster. Alternatively, is there a particular part of the TLS setup that you are having trouble with / we can improve documentation on?
