### ISSUE TITLE
kube-aws up --config=cluster.yaml does not obey controllerInstanceType or workerInstanceType

### ISSUE THREAD

**Issue by danielwhatmuff** [coreos/coreos-kubernetes#172]
It does not work for kube-aws render or kube-aws up - the m3.medium instance type is output for both cases.

**Comment by danielwhatmuff** [comment]
Seems the newKubeconfig function does not have a mention of the instance type keys as shown in the example config https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/cluster.yaml.example.

func newKubeconfig(cfg *cluster.Config, tlsConfig *cluster.TLSConfig) ([]byte, error) {
  data := struct {
    ClusterName       string
    APIServerEndpoint string
    AdminCertFile     string
    AdminKeyFile      string
    CACertFile        string
  }{
    ClusterName:       cfg.ClusterName,
    APIServerEndpoint: fmt.Sprintf("https://%s", cfg.ExternalDNSName),
    AdminCertFile:     tlsConfig.AdminCertFile,
    AdminKeyFile:      tlsConfig.AdminKeyFile,
    CACertFile:        tlsConfig.CACertFile,
  }

**Comment by xied75** [comment]
:+1:

**Comment by ankitforcode** [comment]
@danielwhatmuff This has been fixed however the latest release is not available. 

@aaronlevy can u please run the release for the recent commits.

**Comment by ankitforcode** [comment]
https://github.com/coreos/coreos-kubernetes/pull/155

**Comment by danielwhatmuff** [comment]
@ankitforcode ok, will watch for a new release.

**Comment by bcwaldon** [comment]
Just released v0.3.0: https://github.com/coreos/coreos-kubernetes/releases/tag/v0.3.0
