### ISSUE TITLE
Production consideration?

### ISSUE THREAD

**Issue by xied75** [coreos/coreos-kubernetes#174]
Dear team,

Except the SSL signing part, what else is stopping this tool being used for production?

Best,

Dong

**Comment by ankitforcode** [comment]
@xied75 High availability of Controller Node. Really wanted to take that up and also the custom CIDR option when using AWS as cloud provider.

**Comment by xied75** [comment]
@ankitforcode Anything I can help you with?

FYI: https://letsencrypt.org/2015/11/12/public-beta-timing.html

**Comment by aaronlevy** [comment]
This tool can be used for production infrastructure. Beyond generating SSL assets, having a backup plan for etcd data would be recommended as this is the source of truth for your cluster. Depending on your infrastructure this could mean EBS volume snapshots, or using [etcd backup tools]( https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#backing-up-the-datastore) or possibly other cloud-provider specific backup options.

As far as High availability control nodes, we document how to configure a multi-master cluster here: https://coreos.com/kubernetes/docs/latest/getting-started.html

The kube-aws tool currently deploys a single master. However, if the master goes down, a new node will be launched using the same data / EBS volume. All of your worker nodes (and the pods they are running) will continue to function until the master node is available again.

I'm going to close this for now, but please re-open if you have any additional questions related to this.
