### ISSUE TITLE
Run kubernetes without SSL certificates

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#176]
I'm plannning to deploy kubernetes in an internal network, for this reason I don't need the SSL certificates to access into kubernetes. There is a way, using cloudformation, to deploy kubernetes without the SSL certificates?

**Comment by somejfn** [comment]
Yes you can if you need to. For testing I've been starting the API server
with "--insecure-bind-address=0.0.0.0"  and have the controller-manager and
scheduler use the insecure port to reach the API server instead. ie. Start
them with "--master=http://127.0.0.1:8080"

**Comment by arkkanoid** [comment]
Thanks, it works!
Also I tried to deploy kubernetes with my own SSL certificates and the cloudformation files. I had problems to set the certificate parameters correctly, in particular with the base64 encoding, finally it works running the following command:
cat clusters/kubernetes/apiserver.pem | base64 | xclip -selection c
...
Maybe it's helpful to someone.

**Comment by mydockergit** [comment]
Can you explain how you run it without SSL?  
I installed Kubernetes with weave network plug-in.
I added the field `--insecure-bind-address=0.0.0.0` to `/etc/kubernetes/manifests/kube-apiserver.yaml`.
I added the field `--master=http://127.0.0.1:8080` to `/etc/kubernetes/manifests/kube-controller-manager.yaml` and `/etc/kubernetes/manifests/scheduler.yaml`.
I capture the network between the master to the worker with `tcpdump` and it is still encrypted.

@arkkanoid @somejfn
