### ISSUE TITLE
AWS, no ELB creation after manual cluster setup

### ISSUE THREAD

**Issue by mvoropaiev** [coreos/coreos-kubernetes#186]
Following [manual guide](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/getting-started.md) to deploy coreos-kubernetes cluster on AWS results in no external load balancer (ELB) created when adding service with `type: LoadBalancer`. No specific errors found.

IAM roles for controller/workers are exact same as: https://github.com/kubernetes/kubernetes/tree/master/cluster/aws/templates/iam

```sh
$ cat nginx-svc.yml 
---

kind: Service
apiVersion: v1
metadata:
  name: nginx-dev
  labels:
    app: nginx
    env: dev
spec:
  selector:
    app: nginx
    env: dev
  ports:
    - name: http-dev
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-dev
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
```

```sh
$ kubectl get svc nginx-dev -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2015-12-07T14:55:59Z
  labels:
    app: nginx
    env: dev
  name: nginx-dev
  namespace: default
  resourceVersion: "1509"
  selfLink: /api/v1/namespaces/default/services/nginx-dev
  uid: a06f31cd-9cf2-11e5-8689-0270c3810fcd
spec:
  clusterIP: 10.3.0.254
  ports:
  - name: http-dev
    nodePort: 31973
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-dev
    nodePort: 32502
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: backend
    env: dev
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

```sh
$ kubectl describe svc nginx-dev
Name:			nginx-dev
Namespace:		default
Labels:			app=nginx,env=dev
Selector:		app=backend,env=dev
Type:			LoadBalancer
IP:			10.3.0.254
Port:			http-dev	80/TCP
NodePort:		http-dev	31973/TCP
Endpoints:		10.2.70.3:80,10.2.71.3:80
Port:			https-dev	443/TCP
NodePort:		https-dev	32502/TCP
Endpoints:		10.2.70.3:443,10.2.71.3:443
Session Affinity:	None
No events.
```

is there any specific steps required to setup ELB creation? Thanks.

**Comment by mvoropaiev** [comment]
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

```
$ uname --all
Linux controller01 4.3.0-coreos #2 SMP Thu Dec 3 02:34:45 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
```

**Comment by xied75** [comment]
Hi @mvoropaiev I didn't follow the manual approach but used the kube-aws cli, I do get ELB created for services. It might help to look at files here https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws/artifacts to find out the differences.

**Comment by mvoropaiev** [comment]
Hi @xied75, yeah, using either kube-aws cli or CloudFormation template results in flawless ELB creation for services, but using manual approach is not. I found a kuberentes issue: https://github.com/kubernetes/kubernetes/issues/17647 not sure yet if it is related.  In the meantime I will try to compare artifacts from the link you given. Thanks!

**Comment by mvoropaiev** [comment]
Comparing the artifacts I have found that `--cloud-provider=aws` switch is missing in manual setup docs for kube-apiserver and kube-controller-manager pods on master node. I have not yet tested to see if it works, and I do understand that is kinda OK since this setup should be suitable for all scenarios, but maybe it should be mentioned somewhere in the docs?

**Comment by mvoropaiev** [comment]
Ok, adding `--cloud-provider=aws` does the thing, and now I am getting:
```
  1m		2s		21	{service-controller }			CreatingLoadBalancer		Creating load balancer
  1m		2s		18	{service-controller }			CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/nginx-dev: no instances found for name: 10.50.1.56
...
```
I think I need to play with hostnames now, but this is at least something for now :)

**Comment by mvoropaiev** [comment]
After changing `--hostname-override` in kubelet unit from internal ip to internal dns name of an instance, load balancer was created successfully. Well, almost, I do get
```
Error creating load balancer (will retry): Failed to create load balancer for service default/nginx-dev: error tagging security group: InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty.
```
as mentioned in issue I was linking previously, but after retry it's status is `CreatedLoadBalancer` and everything is working, hope it will be useful.

**Comment by xied75** [comment]
@mvoropaiev Great job. You solved all the puzzles. Maybe worth a PR to modify the documentations?

**Comment by gopinatht** [comment]
@mvoropaiev I am facing the exact same problem and trying to resolve it. I know it may seem obvious but how do I change the internal IP to internal DNS for --hostname-override? Right now our setting looks something like this:

`--hostname-override=${DEFAULT_IPV4} \`

What do I change this to on AWS?

Any info or pointers appreciated.

**Comment by gopinatht** [comment]
@mvoropaiev For clarity, I am using setup-network-environment (https://github.com/kelseyhightower/setup-network-environment) for network setup. I am not using the DNS addon or skyDNS. Is the DNS addon necessary for resolution?

**Comment by gopinatht** [comment]
@mvoropaiev So I resolved the issue by using the hostname issue by using the $HOSTNAME env variable. But now I see a new error `ELB cannot be attached to multiple subnets in the same AZ.`

**Comment by aaronlevy** [comment]
The kube-aws tool has been updated since the time of filing this issue: the `--hostname-override` flag has been removed from the kube-aws default templates, and the `--cloud-provider=aws` flag has been added to both api-server and controller-manager. Launching ELBs from Loadbalancer type services should work as expected.

I'm going to close this for now, but please re-open if there are still issues.
