### ISSUE TITLE
Install Heapster as a default addon

### ISSUE THREAD

**Issue by aaronlevy** [coreos/coreos-kubernetes#187]
It looks like the horizontal scalability functionality relies on Heapster for the pod metrics. We may want to add Heapster / influxDB as addons to install by default (a-la kube-DNS) given these are required for the auto-scale functionality

Ref: https://github.com/coreos/coreos-kubernetes/issues/177

**Comment by joeatwork** [comment]
+1

**Comment by joeatwork** [comment]
Some heapster talk at https://github.com/kubernetes/heapster/pull/769

**Comment by aaronlevy** [comment]
Fixed in https://github.com/coreos/coreos-kubernetes/pull/236
