### ISSUE TITLE
Mention port to be used by workers

### ISSUE THREAD

**Issue by brianredbeard** [coreos/coreos-kubernetes#19]
The comment at:
https://github.com/coreos/kube-up/blob/master/multi-node/generic/worker-cloud-config.yaml#L22

should mention at the very least a default port.  As most of the configuration has occurred via magic at this point there is no context about what this is providing.

**Comment by aaronlevy** [comment]
Sorry @brianredbeard, I took to long to get to this and what link is referring to isn't clear anymore. Is this still something we need to address?
