### ISSUE TITLE
kube-aws: increase verbosity

### ISSUE THREAD

**Issue by ericchiang** [coreos/coreos-kubernetes#197]
#hackday

It would be nice to have status updates while creating the cluster.

"creating a cloud formation stack..."
"configuring TLS..."

**Comment by sym3tri** [comment]
+1

**Comment by aaronlevy** [comment]
Closing this as the kube-aws tool has changed considerably, and specific tool verbosity being discussed here: https://github.com/coreos/coreos-kubernetes/issues/353
