### ISSUE TITLE
Internet Not Working {Unable to connect to External Services from cluster} - AWS

### ISSUE THREAD

**Issue by ankitforcode** [coreos/coreos-kubernetes#206]
Since the recent release I have not been able to get the internet working on the CoreOS box launched via the template.json script.

core@ip-10-0-0-50 ~ $ ping yahoo.com
PING yahoo.com (98.138.253.109) 56(84) bytes of data.
^C
--- yahoo.com ping statistics ---
23 packets transmitted, 0 received, 100% packet loss, time 21999ms

Since the host does not have access to the internet the containers are unable to reach external services.

**Comment by xied75** [comment]
My cluster on aws created with v3.0.0 works alright. I can't ping too, but docker pull works. Can't ping doesn't mean can't reach Internet, it's ICMP egress traffic blocked.

**Comment by ankitforcode** [comment]
Yes. Seems ICMP egress traffic was blocked.
