### ISSUE TITLE
Update documentation on main coreos site (Cloudformation AWS)

### ISSUE THREAD

**Issue by urashidmalik** [coreos/coreos-kubernetes#209]
Hi Please update the documentation on main site for AWS Cloudformation. Anyone trying to created TLS infrastructure would need to know about which exact SAN entry or else kubectl exec and kube-dns will not work

The code state that there should be a SAN entry for 10.3.0.1.
![image](https://cloud.githubusercontent.com/assets/173068/11853459/ea56f730-a3f2-11e5-8547-d9c8246bd97e.png)
Documentation has that missing @ https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html
![image](https://cloud.githubusercontent.com/assets/173068/11853481/1e1ad320-a3f3-11e5-8ff2-7d1343b2da5d.png)

Also if someone is setting up TLS manually he needs to have *.*.compute.internal as SAN for worker or else kubectl exec will not work.
![image](https://cloud.githubusercontent.com/assets/173068/11853503/3e966c04-a3f3-11e5-98f4-7e2f5d64e800.png)
![image](https://cloud.githubusercontent.com/assets/173068/11853525/6e25552a-a3f3-11e5-9eac-f97911c4625e.png)

**Comment by robszumski** [comment]
Can you submit a PR to this repo with these changes? The documents are located in a folder in the root: https://github.com/coreos/coreos-kubernetes/tree/master/Documentation

**Comment by aaronlevy** [comment]
I believe this has been addressed. Please re-open if not.
