### ISSUE TITLE
Any way to customize DOCKER_OPTS?

### ISSUE THREAD

**Issue by krancour** [coreos/coreos-kubernetes#210]
Supposing someone wanted to customize the `DOCKER_OPTS` to specify some insecure registries or disable Docker's management of iptables, is there a means by which that can be accomplished?

**Comment by mischief** [comment]
@krancour see https://coreos.com/os/docs/latest/customizing-docker.html

**Comment by krancour** [comment]
Nevermind... I think I see how to do this now.  Something roughly like this:

```
$ kube-aws render --output=artifacts/template.json
```

Edit the userdata in the template to include a unit like this in the cloud-config:

```
- name: "docker.service"
  drop-ins:
    - name: "50-insecure-registry.conf"
    content: |
      [Service]
      Environment=DOCKER_OPTS='--insecure-registry="10.0.0.0/8"'
```

Then:

```
$aws s3 cp --recursive --acl=public-read artifacts/ s3://<bucket>/
```

And finally use that in the `aritfactURL` in `cluster.yaml`

Although this seems a lot of work for setting a very common option.

**Comment by four43** [comment]
+1 if this could be added to the template params for CloudFormation / config.yaml

**Comment by krancour** [comment]
> +1 if this could be added to the template params for CloudFormation / config.yaml

+1.  That would be more convenient than providing custom artifacts _just_ to address this one, fairly common concern.

**Comment by zatricion** [comment]
+1 I'd like that feature.
