### ISSUE TITLE
kube-aws: document KubernetesCluster tag

### ISSUE THREAD

**Issue by sym3tri** [coreos/coreos-kubernetes#221]
I want to specify a label or tag to set on all the resources created with this tool.
# hackday

EDIT: Apparently this feature exists, but is not documented. Need to document.

**Comment by colhom** [comment]
@sym3tri have you seen the `KubernetesCluster=<cluster-name>` tag?

**Comment by sym3tri** [comment]
@colhom no I haven't. Is that in master? I don't see it anywhere in the docs.

**Comment by colhom** [comment]
@sym3tri afaik it's undocumented but the behavior has been in master for as
long as I've been using kube-aws

**Comment by sym3tri** [comment]
@colhom ok, updating issue description to update the docs.

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
