### ISSUE TITLE
Cloudformation is pointing to v0.2.0 as default latest

### ISSUE THREAD

**Issue by urashidmalik** [coreos/coreos-kubernetes#223]
As of today, link to cloudformation template is pointing to old release (v0.2.0). 
https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html

http://coreos-kubernetes.s3.amazonaws.com/latest/template.json 
![image](https://cloud.githubusercontent.com/assets/173068/11990594/ad3da786-a9c4-11e5-99f0-ee5b98ea3b37.png)

New version can be accessed at this URI
http://coreos-kubernetes.s3.amazonaws.com/v0.3.0/template.json
![image](https://cloud.githubusercontent.com/assets/173068/11990603/dcf84490-a9c4-11e5-9031-23cd7d7c4fe5.png)

**Comment by aaronlevy** [comment]
@urashidmalik I've updated the latest assets to point to the correct version (v0.3.0), can you let me know if that resolves your issue?
