### ISSUE TITLE
Add CI based conformance tests for kube-aws

### ISSUE THREAD

**Issue by aaronlevy** [coreos/coreos-kubernetes#224]
Testing contributed PRs is currently a manual and time consuming process. We should setup a CI system which is able to launch a kube-aws cluster built from PR, then run the upstream conformance tests against the launched cluster.

related: https://github.com/coreos/coreos-kubernetes/issues/218

/cc @colhom

**Comment by colhom** [comment]
@aaronlevy this is a GREAT idea. I will get on this

**Comment by aaronlevy** [comment]
We have something for this internally. Still needs work, but is functional. Clsoing
