### ISSUE TITLE
Is a Digital Ocean terraform script for multi-node inside this repo's scope?

### ISSUE THREAD

**Issue by hermanjunge** [coreos/coreos-kubernetes#225]
Hi,

I worked with the guide in this repository and developed a solution in [terraform](https://terraform.io/)  for Digital Ocean clusters.

Would it be inside the scope of this repository to fill a Pull Request (i.e. `multi-node/digital-ocean`) with this code: https://github.com/hermanjunge/k8s-do-tf

**Comment by xied75** [comment]
@hermanjunge I can't speak for the team but your choice of tooling is very different to the team's solution to aws which is a single golang cli using aws cloudformation templating underneath. Terraform is great and targeting Digital Ocean is also great, it just doesn't look uniform enough to PR here.

Maybe the team could link your repo in the documentation for people who seeking a DO solution. Besides, your repo definitely can live on its own. I might need to use it soon.

:+1:

**Comment by hermanjunge** [comment]
Got it @xied75. Closing the issue. Thanks for the clarification.
