### ISSUE TITLE
Failed initializing TLS infrastructure: x509: certificate contained IP address of length 0

### ISSUE THREAD

**Issue by raykrueger** [coreos/coreos-kubernetes#226]
In order to get the cidr configs from #190 I'm attempting to use the master kube-aws build. I have reproduced this error with go 1.5.1 and go 1.5.2. I'm on Mac OS 10.11.2

```
$ kube-aws up
Failed initializing TLS infrastructure: x509: certificate contained IP address of length 0
```

After some debugging I've determined it's coming from `return x509.ParseCertificate(certDERBytes)` in `NewSelfSignedCACertificate`.

I've tried to resolve this my self by adding IP addresses to the x509 Certificate details, but nothing changed.

(This did not work):
```diff
diff --git a/multi-node/aws/pkg/tlsutil/x509.go b/multi-node/aws/pkg/tlsutil/x509.go
index 206403c..f909229 100644
--- a/multi-node/aws/pkg/tlsutil/x509.go
+++ b/multi-node/aws/pkg/tlsutil/x509.go
@@ -35,7 +35,9 @@ type ClientCertConfig struct {

 func NewSelfSignedCACertificate(cfg CACertConfig, key *rsa.PrivateKey) (*x509.Certificate, error) {
        now := time.Now()
+       ips := []net.IP{net.ParseIP("127.0.0.1")}
        tmpl := x509.Certificate{
+               IPAddresses:  ips,
                SerialNumber: new(big.Int).SetInt64(0),
                Subject: pkix.Name{
                        CommonName:   cfg.CommonName,
```

**Comment by raykrueger** [comment]
Should this be labeled as priority0? The kube-aws tool is unusable in master right now.

**Comment by colhom** [comment]
hi @raykrueger. This is definitely a p0 bug.

I know what the issue is, and will have a PR coming up shortly. The defaults for the node IP addresses are not being applied until after the cert is generated.

**Comment by raykrueger** [comment]
Thanks! Sorry I couldn't send a patch I gave it a shot with the time I had left but couldn't come up with it.

**Comment by colhom** [comment]
@raykrueger could you post your `cluster.yaml` file so I can test the fixes?

**Comment by colhom** [comment]
@raykrueger feel free to obscure any parameters you don't want to share. I'm mainly interested in the networking configuration related parameters

**Comment by raykrueger** [comment]
Yeesh. Not sure I have one anymore. Essentially I was just setting all the vpc ip parameters to a class c

**Comment by colhom** [comment]
@raykrueger thanks for the bug!

**Comment by raykrueger** [comment]
Thanks for fixing it! Sorry I couldn't provide more.

**Comment by raykrueger** [comment]
I'm still having the same problem actually, I've recreated the yaml I was using and I'll provide it here. A little more background here is that I'm trying to use kube-aws to launch a kubernetes cluster in our existing VPC. That VPC already has our dns forwards and vpn setup.

I just got on my morning train, I'll tinker for a bit and see if I come up with anything.

```
$ bin/kube-aws version
kube-aws version d7c22dd9497d8179781449e21ae2c26d7e525acf

$ bin/kube-aws --config=cluster.yaml up
Failed initializing TLS infrastructure: x509: certificate contained IP address of length 0
```

My cluster.yaml:
```
# Unique name of Kubernetes cluster. In order to deploy
# more than one cluster into the same AWS account, this
# name must not conflict with an existing cluster.
# clusterName: kubernetes

# Name of the SSH keypair already loaded into the AWS
# account being used to deploy this cluster.
keyName: mykey

# Region to provision Kubernetes cluster
region: us-east-1

# Availability Zone to provision Kubernetes cluster
availabilityZone: us-east-1b

# DNS name routable to the Kubernetes controller nodes
# from worker nodes and external clients. The deployer
# is responsible for making this name routable
externalDNSName: k8s.example.com

# Instance type for controller node
#controllerInstanceType: m3.medium

# Disk size (GiB) for controller node
#controllerRootVolumeSize: 30

# Number of worker nodes to create
#workerCount: 1

# Instance type for worker nodes
#workerInstanceType: m3.medium

# Disk size (GiB) for worker nodes
#workerRootVolumeSize: 30

# Location of kube-aws artifacts used to deploy a new
# Kubernetes cluster. The necessary artifacts are already
# available in a public S3 bucket matching the version
# of the kube-aws tool. This parameter is typically
# overwritten only for development purposes.
#artifactURL: https://coreos-kubernetes.s3.amazonaws.com/<VERSION>

# CIDR for Kubernetes VPC
vpcCIDR: "10.215.66.0/24"

# CIDR for Kubernetes subnet
instanceCIDR: "10.215.66.0/24"

# IP Address for controller in Kubernetes subnet
controllerIP: "10.215.66.188"

# CIDR for all service IP addresses
# serviceCIDR: "10.3.0.0/24"

# CIDR for all pod IP addresses
# podCIDR: "10.2.0.0/16"

# IP address of Kubernetes controller service (must be contained by serviceCIDR)
# kubernetesServiceIP: 10.3.0.1

# IP address of Kubernetes dns service (must be contained by serviceCIDR)
# dnsServiceIP: 10.3.0.10
```

**Comment by raykrueger** [comment]
Actually this is reproducible with only the required cluster.yml settings:
```
keyName: test
region: us-east-1
externalDNSName: k8s.example.com
```

**Comment by colhom** [comment]
@raykrueger I am not able to reproduce this on my end. 

can you try deleting the `clusters/kubernetes` directory and/or moving it to another location?

**Comment by raykrueger** [comment]
I have to delete that every time otherwise it can't write the keys.

I mentioned I'm running go 1.5 when I build this, what version are you building on?

```
$ go version
go version go1.5.2 darwin/amd64
```

**Comment by colhom** [comment]
I'm building this with go1.5.2, but 64-bit linux unfortunately. Could you see if you can reproducible this on a linux machine as well? I will try this out on my macbook when I get home today

**Comment by raykrueger** [comment]
Yep. I started on a docker build env for it, but my train ride ended. I'll
get back on that tonight.
