### ISSUE TITLE
AWS multi-node cluster.yaml.example subnet clarifications

### ISSUE THREAD

**Issue by alexjs** [coreos/coreos-kubernetes#231]
Currently the sample AWS YAML has:
```
# CIDR for Kubernetes VPC
# vpcCIDR: "10.0.0.0/16"

# CIDR for Kubernetes subnet
# instanceCIDR: "10.0.0.0/24"

# CIDR for all service IP addresses
# serviceCIDR: "10.3.0.0/24"
```

But 10.3.0.0/24 is outside 10.0.0.0/16, so you couldn't deploy it into a 10.0.0.0/16 VPC. I'm not massively familiar with Kubernetes so wanted to confirm that the Service (and Pod) subnets should be in that /16 range and that simply updating the sample YAML wouldn't affect anything else before submitting a pull request.

EDIT:

I think I now see this doesn't matter, since the CF template doesn't actually create the subnets in the VPC. I'll leave this open just to sanity check, but think it can probably be closed as invalid

**Comment by colhom** [comment]
@alexjs the podCIDR and serviceCIDR options refer to virtual networks which are created and managed by Kubernetes. In the case of kube-aws, the virtual network provider is [flannel](https://github.com/coreos/flannel).

Check out the [Kubernetes networking doc](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/design/networking.md).

**Comment by allingeek** [comment]
I'd really like to reopen this issue. This this a glaring documentation problem. Many people have spent hours trying to debug this perceived issue only to stumble upon this lack luster revelation. 

I'd suggest adding the word "VIRTUAL" or "OVERLAY" or "INTERNAL" to each of those three comments in the YAML file.
