### ISSUE TITLE
Impossible to create a daemonSet pod

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#235]
Hi
On Kubernetes version v1.1.1 I'm trying to run New Relic Agent in all nodes. For this reason I want to use DaemonSet. I've configured a pod as is specified in: https://github.com/kubernetes/kubernetes/tree/master/examples/newrelic
But when I create it, I get this error:

    kubectl create -f newrelicAgent.json                 
    error validating "newrelicAgent.json": error validating data: couldn't find type: v1beta1.DaemonSet; if you choose to ignore these errors, turn validation off with --validate=false

And

    kubectl create --validate=false -f newrelicAgent.json
    Error from server: error when creating "newrelicAgent.json": the server could not find the requested resource

Also, if I execute

    kubectl get daemonsets                               
    Unable to list "daemonsets": the server could not find the requested resource

Is not available DaemonSet for this kubernetes version?
How can I solve it?
Thanks

**Comment by aaronlevy** [comment]
Daemonsets are not enabled by default. You can enable them by adding the `--runtime-config=extensions/v1beta1/daemonsets=true` flag to your kubernetes apiserver manifest (typically /etc/kubernetes/manifests/kube-apiserver.yaml)

See: http://kubernetes.io/v1.1/docs/admin/daemons.html#caveats

**Comment by arkkanoid** [comment]
Thanks @aaronlevy. There is a way to set this flag on boot?

**Comment by aaronlevy** [comment]
If you modify the cloud-config (in this case just a bash script) it will set this flag on boot. I have an open PR to change this as the default: https://github.com/coreos/coreos-kubernetes/pull/239

Alternatively, on existing nodes you would need to modify the kube-apiserver manifest to include the flag: `/etc/kubernetes/manifests/kube-apiserver.yaml`. The kubelet will see the change to the manifest and restart the api-server with the new flag. Also, if you're running multiple master nodes be sure to change the manifest on each of them.
