### ISSUE TITLE
Add support for a dry run without creating AWS resources

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#241]
A `--dry-run` flag would be awesome to generate all of the certs and other assets required, but not actually creating the AWS resources. This could be used to see what the tool does and how things are constructed.

Vaguely related to https://github.com/coreos/coreos-kubernetes/pull/240

**Comment by aaronlevy** [comment]
This should be covered by the `render` command introduced in: https://github.com/coreos/coreos-kubernetes/pull/316
