### ISSUE TITLE
Provide kube-aws upgrade path

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-kubernetes#243]
As of now, kube-aws provides no way to 
- upgrade a cluster to an new version
- apply new configuration to nodes
- rotate in new TLS assets

Depends on reproducible assets (#218) being resolved

**Comment by aaronlevy** [comment]
related: https://github.com/coreos/coreos-kubernetes/issues/230

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
