### ISSUE TITLE
IPs 11.0.0.0/8 are DoD Territory

### ISSUE THREAD

**Issue by hermanjunge** [coreos/coreos-kubernetes#258]
Didn't know that until I saw [this tweet](https://twitter.com/thockin/status/690402376168148993) from @thockin

`People need to stop using 11.0.0.0 IPs for their kube clusters - that is DoD territory.`

Source: http://whois.arin.net/rest/net/NET-11-0-0-0-1

Do we keep using that network on the getting started guide?

**Comment by aaronlevy** [comment]
Ref: https://coreos.com/kubernetes/docs/latest/getting-started.html

Not entirely sure where those IPs are coming from. The docs in this repo always reference 10.0.0.0 (but website should be syncing from here too).

We are going to re-sync the docs to the website to fix the issue.

**Comment by hermanjunge** [comment]
The network is right now at https://coreos.com/kubernetes/docs/latest/getting-started.html

This is strange indeed. We can see that the introduction of `10.3.0.0/24` dates from SEP.11. Anyways, I'm fixing my docs. Thanks for the quick response.
