### ISSUE TITLE
Documentation: Code block formatting on website

### ISSUE THREAD

**Issue by jrdnull** [coreos/coreos-kubernetes#260]
The code block in the Configure kubectl section is missing line breaks [on this page (Single-Node Kubernetes...) ](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html), although renders OK on [this one](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html).

Possibly because it doesn't have the blank line between?

https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubernetes-on-vagrant-single.md#configure-kubectl vs https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubernetes-on-vagrant.md#configure-kubectl

**Comment by robszumski** [comment]
Yes, this is the one difference that our Markdown renderer has from Github-flavored Markdown. Everything else is identical. We catch most of these but sometimes they slip through.
