### ISSUE TITLE
Question about kubelet in coreos

### ISSUE THREAD

**Issue by philbert** [coreos/coreos-kubernetes#266]
I'm playing around with coreos and kubernetes and decided [Kelsey's kubestack](https://github.com/kelseyhightower/kubestack) was a good place to start.

I grabbed the latest stable version of coreos 835.11.0 to discover that terraform apply fails because kubelet was not included in that release.

I found [the blog post Kelsey wrote about the kubelet](https://coreos.com/blog/introducing-the-kubelet-in-coreos/) which states "First we need to get the kubelet up and running. Be sure to follow this tutorial using CoreOS Linux 773.1.0 or greater."

However, it also states "This week we have added the kubelet, a central building block of Kubernetes, in the alpha channel for CoreOS Linux."

Sure enough, I tried the alpha channel version 935.0.0 and /usr/bin/kubelet is there.

So what's the deal with kubelet making it into stable? Is it not ready, or not planned, or just overlooked, or what? I'm just trying to make sense of it all. Cheers.

**Comment by zebulonj** [comment]
+1. Similar question. Landed on this issue after seeing that the `kubelet` is only in the alpha or beta channel.

> Boot a single CoreOS machine which will be used as the Kubernetes master node. You must use a CoreOS version 773.1.0+ on the Alpha or Beta channel for the kubelet to be present in the image.

—https://coreos.com/kubernetes/docs/latest/deploy-master.html

Is there a plan for for the `kubelet` to make it into the stable channel? Is there a reason that it isn't yet (not considered ready for production)? I run the stable channel in production (go figure). Guess it's always an option to build my own Kubernetes binaries, but...

**Comment by xied75** [comment]
https://github.com/coreos/bugs/issues/985

**Comment by philbert** [comment]
Ok that answers my question. Cheers.
