### ISSUE TITLE
no possibility to provide dockercfg

### ISSUE THREAD

**Issue by Morriz** [coreos/coreos-kubernetes#272]
How can I configure the multi-node aws kube-aws setup to use my private aws registry?

It seems the .dockercfg needs to be provided with cloud-config, but I have a hard time finding out how to do this after the nodes have been brought up. I believe it should be done during init, no? If so, then where do I inject this?

**Comment by robszumski** [comment]
What are you using this dockercfg to pull? Kubernetes components that you're hosting yourself, or containers in pods after the cluster is already running?

**Comment by Morriz** [comment]
Ok, I found that kube seems to support aws ecr natively now, so I figured the following:
- because my stack is in eu-west-1
- and the registry in us-east-1 (as its the only one they have now)
- and the assumption that it's not possible to docker pull cross-region (but that would be silly, no?)
-> it follows that I run into the security restrictions for going out of their region's network.

I would like to know for a fact that it's impossible to docker pull cross-region. Any links?

**Comment by Morriz** [comment]
So I don't need to fiddle with dockercfg, unless my assumption holds. Then I would have to bootstrap my nodes with creds, but they only last 12 hours. Pfffff...

**Comment by aaronlevy** [comment]
@Morriz I'm going to close this for now, as it seems this is more an issue with the aws registry. Feel free to reopen if that is not the case.

**Comment by Morriz** [comment]
I have to reopen this, as I don't see a solution from your side to provide a dockercfg, which is needed to provide creds.

**Comment by Morriz** [comment]
Nevermind, I found the docs on how to encode the dockercfg as a kubernetes secret....maybe handy to link to that as well

**Comment by arkkanoid** [comment]
Setting the dockercfg in the user-data solves your problem?
https://coreos.com/os/docs/latest/registry-authentication.html
