### ISSUE TITLE
switching to us-east-1 breaks the installer

### ISSUE THREAD

**Issue by Morriz** [coreos/coreos-kubernetes#273]
Hi, after having installed succesfully many times to eu-west-1, I can't seem to get it installed in us-east-1, even if I give it the region 'us-east-1b'. I have manually inspected for any ghost artifacts, but the destroy script cleans up ok. I spent around 3 hours playing with this, only to conclude something is different between these regions.

I have not changed anything in cluster.yaml but the region and az.

**Comment by somejfn** [comment]
is the AMI ID used for coreos valid in us-east-1 ?

**Comment by Morriz** [comment]
It is blackboxed into the setup. Dunno. Probably selected based on region through a helper.

**Comment by Morriz** [comment]
Yeah, that is retrieved through `coreosutil.GetAMIData(channel)`

**Comment by colhom** [comment]
@morriz what is the symptom? Does the cloudformation make it to the `Creating` phase? Error in the events tab?

Are you using custom artifacts that you uploaded yourself, or the coreos hosted artifacts?

**Comment by Morriz** [comment]
Hi, tnx for coming back so quickly. I have to say the go scripts don't give back much, only that the creation of the instance fails. Can you give me instructions how to generate more?

But it is like I said. I use the 'coreos-kubernetes' github repo as is, and only changed the region.

**Comment by colhom** [comment]
Morriz: Could you log into aws console and look for the cloudformation that kube-aws is creating? It will be the same name as your cluster name parameter.

When/if you find it, look in the events tab for events with failed statuses.

**Comment by Morriz** [comment]
It complains about a key pair not existing, the pair that I used to succesfully create the stack in eu-west-1...weird. I assumed  the key pair would be for all regions. Now let me see where I can add it to another region...got any hints?

**Comment by Morriz** [comment]
Nevermind, it's good now. Darn my cross region noobness ;p
