### ISSUE TITLE
Can't build kube-aws on OS X

### ISSUE THREAD

**Issue by aknuds1** [coreos/coreos-kubernetes#278]
When I try to build kube-aws on OS X (go 1.5.3 installed via homebrew), like this `./multi-node/aws/build`, it fails:

```
Building kube-aws 4b447f79118d15c1b271e7d11887c7a65a7174d0...
go: GOPATH entry is relative; must be absolute path: "".
Run 'go help gopath' for usage.
```

If I modify the build script to not include the current `$GOPATH` (it's not set on my machine), it fails like this:

```
Building kube-aws 4b447f79118d15c1b271e7d11887c7a65a7174d0+dirty...
can't load package: package github.com/coreos/coreos-kubernetes/multi-node/aws/cmd/kube-aws: cannot find package "github.com/coreos/coreos-kubernetes/multi-node/aws/cmd/kube-aws" in any of:
	/usr/local/Cellar/go/1.5.3/libexec/src/github.com/coreos/coreos-kubernetes/multi-node/aws/cmd/kube-aws (from $GOROOT)
	/Users/arve/Projects/coreos-kubernetes/multi-node/aws/Godeps/_workspace/src/github.com/coreos/coreos-kubernetes/multi-node/aws/cmd/kube-aws (from $GOPATH)
```

**Comment by danielwhatmuff** [comment]
Maybe use a Go Docker image to build the code from a mounted volume and set environment variables GOOS=darwin GOARCH=amd64 for cross compilation to OS X.

**Comment by aaronlevy** [comment]
The build script expects you to be in the multi-node/aws directory. So:

`cd multi-node/aws && ./build`

**Comment by colhom** [comment]
@aknuds1 #279 (merged) changes the build script so it figures out it's own GOPATH itself. Want to give that a try?

**Comment by aknuds1** [comment]
@colhom Fails for me on OS X:

```
➜  aws git:(fix-formatting) ./build
Building kube-aws e10320785cbc925e03b9224050d8428172de0e4c...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
ln: /Users/arve/Projects/coreos-kubernetes/multi-node/aws/gopath/src/github.com/coreos//.: Invalid argument
```

**Comment by colhom** [comment]
@aknuds1 this is due to the os X version of `readlink` not working the same as the gnu or linux versions. Highly recommend installing gnu coreutils via homebrew if you're so inclined.

Would you try out #282 for me? I don't have a mac handy.

**Comment by raykrueger** [comment]
To get readlink working you need...

    brew install coreutils
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

**Comment by aaronlevy** [comment]
Should be resolved in https://github.com/coreos/coreos-kubernetes/pull/282
