### ISSUE TITLE
Docker Configuration

### ISSUE THREAD

**Issue by johscheuer** [coreos/coreos-kubernetes#289]
Hi,

I wanted to ask how to change the default docker systemd unit in coreos-kubernetes? When I run my own CoreOS cluster I just overwrite the default docker systemd unit with my own in the cloud-config like this:
```yaml
- name: docker.service
  command: restart
  content: |
    [Unit]
    Description=Docker Application Container Engine
    Documentation=http://docs.docker.com
    After=docker.socket early-docker.target network.target
    Requires=docker.socket early-docker.target

    [Service]
    EnvironmentFile=-/run/flannel_docker_opts.env
    MountFlags=shared
    LimitNOFILE=1048576
    LimitNPROC=1048576
    ExecStart=/usr/lib/coreos/dockerd daemon --host=fd:// $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ

    [Install]
    WantedBy=multi-user.target
```

Is there a similar way in coreos-kubernetes? I tried to overwrite it in the `../generic/worker-install.sh` but it didn't work as expected.

I'm using coreos-kubernetes as multi-node on vagrant.

Thanks!

**Comment by robszumski** [comment]
You should be able to create just a [drop-in](https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html) for `MountFlags=` instead of having to replace the entire file.

Similar to these two: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/worker-install.sh#L149-L168

**Comment by johscheuer** [comment]
Right, I forgot drop-ins.

I got this working solution now:
```Bash
    local TEMPLATE=/etc/systemd/system/docker.service.d/slave-mount-flags.conf
    [ -f $TEMPLATE ] || {
       echo "TEMPLATE: $TEMPLATE"
       mkdir -p $(dirname $TEMPLATE)
       cat << EOF > $TEMPLATE
[Service]
MountFlags=shared
EOF
    }
```

What about adding a line to the [documentation](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/deploy-workers.md#docker-configuration) about drop-ins and docker configuration?

**Comment by robszumski** [comment]
Cool, glad you got it working. In the interest of keeping the docs clear and succinct I would side towards leaving this type of tweak out until it becomes more widespread/common. If you feel differently, propose a PR and we can go from there.

**Comment by johscheuer** [comment]
Sounds good to me. I think we can leave this teak outside of the documentation most users will be fine with the default docker config.

Thanks!
