### ISSUE TITLE
AWS should use vxlan backend

### ISSUE THREAD

**Issue by aaronlevy** [coreos/coreos-kubernetes#291]
Currently using default (UDP), but should use vxlan instead.

See: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh#L71

**Comment by spacepluk** [comment]
Do you mean that flannel uses UDP regardless of that config?  I'm using this on AWS and that might explain I few performance issues I'm running into.

**Comment by aaronlevy** [comment]
Sorry, that might have been unclear.

The config I link to is from the "generic" install scripts, which use vxlan. We need to make similar changes to the AWS scripts here: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/artifacts/scripts/install-controller.sh#L84

It may be as simple as making that change, but also should run the resulting cluster through upstream conformance tests to sanity check.

**Comment by spacepluk** [comment]
Oh I see, I just tried changing only that line and my pods/services stop seeing each other.  I have no idea how to debug this :(  Is there any log I can post that can help?

**Comment by aaronlevy** [comment]
One likely reason is that the port for vxlan (8472) is different than when using UDP (8285). See: https://github.com/coreos/flannel#backends

The cloud-formation would also need to be updated to open the vxlan port between nodes.

**Comment by spacepluk** [comment]
Thanks, I'll take a look at that today :)

**Comment by spacepluk** [comment]
Hey @aaronlevy,
I updated the cloudfront template with the right ports and it seems to be working great so far.

**Comment by aaronlevy** [comment]
@spacepluk, awesome! Would you submit a PR (and we can run it through our cluster tests)?

**Comment by spacepluk** [comment]
@aaronlevy there you go :) #304

**Comment by spacepluk** [comment]
I've noticed than when I'm using vxlan I can't access my services through `kubectl proxy` *(I thought I had tested that...)*.

Accessing services that are exposed using a `LoadBalancer` works fine.  Any idea what might be the reason for that?

**Comment by spacepluk** [comment]
This is why I get when I try to acces kubedash with my browser through the proxy (`http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubedash/`):

```
Error: 'dial tcp 10.2.5.5:8289: i/o timeout'
Trying to reach: 'http://10.2.5.5:8289/'
```

**Comment by spacepluk** [comment]
Nevermind, I found the solution. I'll clean it up and update the PR later.

**Comment by chancez** [comment]
Why not use the AWS-VPC backend rather than VXLAN for AWS?

**Comment by spacepluk** [comment]
I think it's because of this: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-route-tables

**Comment by chancez** [comment]
Fair enough.

**Comment by aaronlevy** [comment]
@spacepluk Sorry I haven't gotten around to testing your change yet.

There is currently a pretty large re-write of the kube-aws tool that is getting very close and we're trying to get that wrapped up. Once that is in place, this PR will likely need to be modified to fit the new format. Would you mind if we hold off on this for a little bit, assuming that change makes it in soon, then rebase on top of that?

ref: https://github.com/coreos/coreos-kubernetes/pull/316

**Comment by aaronlevy** [comment]
Fixed in: https://github.com/coreos/coreos-kubernetes/pull/304
