### ISSUE TITLE
AWS - Specify Existing VPC ID

### ISSUE THREAD

**Issue by four43** [coreos/coreos-kubernetes#296]
I am looking to launch this Kubernetes/CoreOS cluster into an existing VPC. We have existing resources we would like to access in that established VPC. Feature request: Specify VPC ID instead of making a new one every time?

This is stemming from an issue with getting VPCs to talk to each other. The DNS external resolution limitation is biting us hard and we are having issues accessing our docker registry which is already deployed in an established VPC.

**Comment by spacepluk** [comment]
I'm in a similar situation, and it looks like this is a CloudFormation's limitation.  I think it should be possible to create a CloudFormation template of your existing resources using [CloudFormer](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-cloudformer.html) and then update that template to add all the coreos-kubernetes resources but I haven't tried it yet.

**Comment by four43** [comment]
I was thinking of traveling down a similar path. I don't know about you guys, but I'm pretty intimidated by CloudFormation templates. There is all sorts of JSON as strings inside JSON, some YAML in JSON. It seems pretty fragile to me.

**Comment by colhom** [comment]
@four43 agree completely. We have a big re-working of the kube-aws source that simplifies the render pipeline significantly. Once that lands, implementing this functionality will be much easier.

**Comment by colhom** [comment]
We have a PR up for this now. #346

**Comment by colhom** [comment]
fixed in #346
