### ISSUE TITLE
Docs: After creating DNS addon, it's not found among pods

### ISSUE THREAD

**Issue by aknuds1** [coreos/coreos-kubernetes#299]
The [guide](https://coreos.com/kubernetes/docs/latest/deploy-addons.html#deploy-the-dns-add-on) says to create a DNS addon like so: `kubectl create -f dns-addon.yml`. After this, a corresponding pod should be found via this command: `kubectl get pods --namespace=kube-system | grep kube-dns-v9`.

However, in my case the latter command doesn't find anything, even though the addon creation by all accounts went smoothly.

**Comment by colhom** [comment]
@aknuds1 try this
`kubectl get pods --all-namespaces | grep kube-dns-v9`

My guess is you created it in the default namespace.

**Comment by aknuds1** [comment]
@colhom I can't recall right now how I fixed it, but I do know I was recommended using a different DNS addon spec, which is at v10 FWIW. So, this is not a problem anymore. Although service DNS is still not working...
