### ISSUE TITLE
conformance-tests.md uses removed branch of kubernetes git repo

### ISSUE THREAD

**Issue by rutsky** [coreos/coreos-kubernetes#308]
[Here](https://coreos.com/kubernetes/docs/latest/conformance-tests.html#checkout-conformance-test-branch):

```
$ cd kubernetes
$ git checkout conformance-test-v1
```

however `https://github.com/kubernetes/kubernetes` doesn't have `conformance-test-v1` branch.

Looks like this branch was [removed](https://github.com/kubernetes/kubernetes/issues/17536).

**Comment by aaronlevy** [comment]
Yeah, conformance tests were changed to be run directly off the release you wish to test. The instructions need to be updated. Feel free to submit a PR, or we can get these updated soon.

/cc @robszumski
