### ISSUE TITLE
Increase default Virtualbox memory to at least 4GB

### ISSUE THREAD

**Issue by wstrange** [coreos/coreos-kubernetes#311]
The default of 1 GB is practically useless and leads to confusing problems for first-time users

**Comment by aaronlevy** [comment]
Sure this seems reasonable. There were new addons added somewhat recently (heapster / influxdb) which probably made this worse.

We make this easily configurable on the multi-node install, so maybe on the single node install we just make it a var at top of Vagrantfile and default to 2/4GB
