### ISSUE TITLE
SELinux: mount invalid on AWS

### ISSUE THREAD

**Issue by carmstrong** [coreos/coreos-kubernetes#317]
A freshly-provisioned cluster with the latest release of kube-aws can result in SELinux errors under certain workloads. For context and discussion, see https://github.com/deis/postgres/issues/63

**Comment by colhom** [comment]
@aaronlevy will do

**Comment by nick4fake** [comment]
I just noticed this problem on bare metal installation.

I have a cluster of coreos machines under libvirt. Console is filled with errors:
"SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)"

**Comment by nick4fake** [comment]
Checked on stable, beta and alpha. I observe errors even on freshly-installed kubernetes cluster (without any service/rc deployed by me)

**Comment by TerraTech** [comment]
Sorry for the "me too", but I am seeing a similar same problem that @nick4fake has reported...  My lab setup is on Linux (Gentoo)+Qemu+libvirtd...  Is this warning message going to cause subtle or fundamental operational problems with the CoreOS nodes where a process could be denied access by SELinux to a resource when it normally could?  I'm using VirtIO disks: /dev/vda if that matters...

CoreOS stable: 1010.5.0 (I believe I also saw this with 899.17.0)

If you need any further details, please don't hesitate to ask...

**Comment by jswoods** [comment]
Seeing this as well on 1032.1.0.

**Comment by edevil** [comment]
I'm also seeing a lot of these messages, but haven't seen any concrete problems... What are they about?

**Comment by colhom** [comment]
Anyone willing to give me an example kube-aws cluster.yaml + application workload so I can attempt to repro?
@edevil @jswoods @TerraTech

**Comment by edevil** [comment]
I have setup my cluster using this script: https://github.com/edevil/kubernetes-deployment

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
