### ISSUE TITLE
No hyperkube image for 1.2

### ISSUE THREAD

**Issue by tomdee** [coreos/coreos-kubernetes#324]
Kubernetes 1.2 has shipped so this repo and the hyperkube built should be updated - https://quay.io/repository/coreos/hyperkube?tab=tags

**Comment by aaronlevy** [comment]
@tomdee a Coreos hyperkube v1.2 image is in the process of being built / tested. We should be bumping the version in this project this week.

**Comment by stevesloka** [comment]
Is this image different than the normal hyperkube image? I'm trying to test something now on 1.2 and am ok building my own. If it's not the same, do you have a link to how the image was built?

**Comment by aaronlevy** [comment]
It is more or less the same as the normal hyperkube image, but we may backport fixes we find necessary.

The actual build process we use is: https://github.com/coreos/kubernetes/tree/coreos-hyperkube/coreos 

For the 1.2 release we will likely just need to backporting a cadvisor fix for running kubelet inside a container: https://github.com/google/cadvisor/pull/1125

**Comment by pbx0** [comment]
@stevesloka The main difference is that we add a symlink from `/kubelet` to `/hyperkube -- kubelet`. The symlink makes the hyperkube image look just like a kubelet image. This satisfies the [kubelet-wrapper](https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html) script we ship since it expects a kubelet image.

Depending on the release we also may add a few backports necessary to get conformance and other tests passing on CoreOS. We build the hyperkube images from branches for each version in https://github.com/coreos/kubernetes that contain a commit with the build makefile. Branches are named `coreos-hyperkube-{{.VERSION_TAG}}`.

**Comment by stevesloka** [comment]
Ahh thanks, the symlink was the piece that I wasn't getting. I saw the script was calling just /kubelet. 

I'll poke around and see if I can get something working, appreciate the quick response!

**Comment by stevesloka** [comment]
@tomdee I know the CoreOS folks are working on the official image, but I was able to build out my own last night. You just need to set the following in your service. I'm going to use this until the official one comes out since it probably has more changes that my stock hyperkube. 

```
Environment=KUBELET_ACI=quay.io/upmc_enterprises/hyperkube
Environment=KUBELET_VERSION=v1.2.0
```

**Comment by MurgaNikolay** [comment]
Hello.

@stevesloka 
I try your image, but I have error:
kubelet-wrapper[14718]: run: openpgp: invalid signature: hash tag doesn't match
How I can fix it?

**Comment by stevesloka** [comment]
@MurgaNikolay I'm getting that now too but yesterday things worked fine. I wonder if something is up with quay.io?

**Comment by stevesloka** [comment]
@MurgaNikolay I think something with that repo got messed up or something internal to quay. But I pushed it to a new repo name and now it's working. Change your image to the following and see if it works:

```
Environment=KUBELET_ACI=quay.io/upmc_enterprises/hyperkube2
Environment=KUBELET_VERSION=v1.2.0
```

**Comment by aaronlevy** [comment]
There is now a v1.2.0 hyperkube image available: https://quay.io/repository/coreos/hyperkube?tab=tags

I'm going to close this issue, but just to note - the remainder of work to update the documentation / tools to use the new v1.2.0 image is currently in progress here: https://github.com/coreos/coreos-kubernetes/pull/355
