### ISSUE TITLE
Instructions do not lead to successful installation.

### ISSUE THREAD

**Issue by COLABORATI** [coreos/coreos-kubernetes#329]
I followed [this document](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html), and it lead me only to this error message:
```
error: couldn't read version from server: Get https://172.17.4.99:443/api: dial tcp 172.17.4.99:443: connection refused
```

**Comment by colhom** [comment]
@COLABORATI There is a delay between when `kube-aws up` completes and when the API server is ready to receive requests. Please try again now that some time has elapsed.

**Comment by COLABORATI** [comment]
Dear Colhom, you are right, it takes _some time_! This is incredible, just take a coffee and then magic happened... ok, thanks for your attention! BTW you should add this little bit to the description... have a nice day!
