### ISSUE TITLE
kube-aws: output success messages

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#353]
Add two success messages for:

1. `kube-aws init`
2. `kube-aws render`

Existing init output:

```
$ kube-aws init --cluster-name=xxxxxx \
 --external-dns-name=xxxxx \
 --region=xxxx \
 --availability-zone=xxxx \
 --key-name=xxxxx \
 --kms-key-arn="arn:aws:kms:us-east-1:xxxxx"
Edit cluster.yaml to parameterize the cluster. Then use the "kube-aws render" command to render the stack template
````

What if we reformatted the bottom to say:

```
$ kube-aws init --cluster-name=xxxxxx \
 --external-dns-name=xxxxx \
 --region=xxxx \
 --availability-zone=xxxx \
 --key-name=xxxxx \
 --kms-key-arn="arn:aws:kms:us-east-1:xxxxx"
Success! Created cluster.yaml

Next steps:
1. Edit cluster.yaml to parameterize the cluster.
2. Use the "kube-aws render" command to render the stack template
3. Start the cluster with "kube-aws up"
```

Existing render output:

```
$ kube-aws render
Edit cluster.yaml and/or any of the cluster assets. Then use the "kube-aws up" command to create the stack
```

I'm not sure why we're suggesting to tweak the yml again. What about this:

```
$ kube-aws render
Success! Stack rendered to stack-template.json

Next steps:
1. Validate your changes to cluster.yaml with "kube-aws render"
2. Start the cluster with "kube-aws up"
```

**Comment by colhom** [comment]
@robszumski agree the verbiage doesn't do explain how the tool is supposed to be used. I'm going to do a standard 3-step flow here-- we should probably work this content into the docs, as well as reflecting it in the success messages.

1. **Parameters** == [`cluster.yaml`]

  * Mandatory: 
`kube-aws init ...` sets the _required_ parameters. --> `cluster.yaml`

  * Optional: 
Modify any cluster **Parameters** by editing `cluster.yaml`.

2. **Implementation** == `[credentials/, userdata/, kubeconfig, stack-template.json]`
   * Mandatory: 
`kube-aws render` consumes `cluster.yaml` and generates a "default" cluster implementation

   * Optional:
Modify cluster **Implementation** by editing files. 

3. **Instantiation**
    * Mandatory: 
       `kube-aws up` executes your **Implementation** with your **Parameters** to instantiate your cluster.

    * Optional:
      * `kube-aws up --export`: Same thing as `up`, but exports your cluster instantiation as a JSON file. This can be uploaded directly to CloudFormation.

      * `kube-aws validate`: Same thing as `up`, but the `dryRun` version.

The golden rule is you can always get a working cluster by just doing the mandatory steps.

**Comment by colhom** [comment]
@robszumski any suggestions on new success messages?

**Comment by robszumski** [comment]
What about these?

1. init

```
$ kube-aws init --cluster-name=xxxxxx \
 --external-dns-name=xxxxx \
 --region=xxxx \
 --availability-zone=xxxx \
 --key-name=xxxxx \
 --kms-key-arn="arn:aws:kms:us-east-1:xxxxx"
Success! Created cluster.yaml

Next steps:
1. Edit cluster.yaml to parameterize the cluster.
2. Use the "kube-aws render" command to render the stack template
3. Start the cluster with "kube-aws up"
```

2. render

```
$ kube-aws render
Success! Stack rendered to stack-template.json

Next steps:
1. Validate your changes to cluster.yaml with "kube-aws render"
2. Start the cluster with "kube-aws up"
```

3. up

```
$ kube-aws up
Creating AWS resources. This make take several minutes.
```

and after it creates:

```
$ kube-aws up
Creating AWS resources. This make take several minutes.

Success! Your AWS resources have been created. The containers that power your cluster are now being dowloaded.

You should be able to access the Kubernetes API once the containers finish downloading.
```

**Comment by colhom** [comment]
@robszumski Next Steps under `render`, item `1`. Two points on that. 
* Render won't validate the changes. You would call `kube-aws validate` for that.
* You can also make changes to any of the cluster assets (`userdata, stack-template.json`) if you want to further customize your deployments.

I'll work that stuff in and we can do a PR?

**Comment by colhom** [comment]
@cgag maybe you should take this.

**Comment by robszumski** [comment]
@colhom Whoops, that was a typo. Feel free to fix in a PR!
