### ISSUE TITLE
Improve AWS AlarmControllerRecover template

### ISSUE THREAD

**Issue by kastork** [coreos/coreos-kubernetes#354]
The template and params generated by `kube-aws` assumes the use of the `aws` partition.  `aws` is not the only legal partition.  For example, government cloud is `aws-us-gov`.

The template would be more flexible if kube-aws made the partition configurable.

The only place the existing template encounters this issue is in the configuration for AlarmControllerRecover.

This hard-coded use of `aws`,

`arn:aws:automate:` ...

for gov cloud users, needs to be,

`arn:aws-us-gov:automate:` ...

``` json
"AlarmControllerRecover": {
            "Properties": {
                "AlarmActions": ["arn:aws:automate:us-gov-west-1:ec2:recover"],
                "AlarmDescription": "Trigger a recovery when system check fails for 5 consecutive minutes.",
                "ComparisonOperator": "GreaterThanThreshold",
                "Dimensions": [
                    {
                        "Name": "InstanceId",
                        "Value": {
                            "Ref": "InstanceController"
                        }
                    }
                ],
                "EvaluationPeriods": "5",
                "MetricName": "StatusCheckFailed_System",
                "Namespace": "AWS/EC2",
                "Period": "60",
                "Statistic": "Minimum",
                "Threshold": "0"
            },
            "Type": "AWS::CloudWatch::Alarm"
        },
```

**Comment by kastork** [comment]
So I got it to work.

Turns out that the hard coded `arn:aws:...` is the problem.

The required arn expression is

`"arn:aws-us-gov:automate:us-gov-west-1:ec2:recover"`

So it looks like element 1 of the arn needs to be a templated value. so users can choose `aws` or `aws-us-gov`

**Comment by colhom** [comment]
@kastork would you be willing to do a PR for this?

**Comment by kastork** [comment]
@colhom I'm very new to using CloudFormation, so it might take me a while, but yes I'm willing.

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
