### ISSUE TITLE
Upgrade Heapster to 1.0+

### ISSUE THREAD

**Issue by joeatwork** [coreos/coreos-kubernetes#359]
Now that Heapster has a stable 1.0 release, let's upgrade the out-of-the-box version! That will also allow users of Kubernetes Dashboard to see cool metrics in their UIs.

**Comment by aaronlevy** [comment]
@joeatwork would you be able to upgrade the templates to match what is in the kubernetes release-1.2 branch? This is part of the work that still needs to be done for this tool to use 1.2: https://github.com/coreos/coreos-kubernetes/pull/355#issuecomment-201441533

/cc @pbx0

**Comment by joeatwork** [comment]
Will do!

**Comment by colhom** [comment]
@joeatwork probably a good time to take care of #358 as well.

**Comment by chancez** [comment]
@joeatwork @colhom this is done right?

**Comment by pbx0** [comment]
We are on v1.0.2
