### ISSUE TITLE
conformance-test.sh  Unable to parse server version "v1.2.0_coreos.0"

### ISSUE THREAD

**Issue by lukasz-bielinski** [coreos/coreos-kubernetes#364]
hi, i created k8s cluster on coreos:

images:
 image: quay.io/coreos/hyperkube:v1.2.0_coreos.0
 image: gcr.io/google_containers/podmaster:1.1

when i run conformance tests i see several errors regarding version:

    Mar 29 11:27:37.361: INFO: update-demo-nautilus-59l5w is running right image but validator function failed: Unable to parse server version "v1.2.0_coreos.0": Invalid character(s) found in patch number "0_coreos.0"

    Mar 29 11:24:42.188: Failed to get server version: Unable to parse server version "v1.2.0_coreos.0": Invalid character(s) found in patch number "0_coreos.0"

could you please advice what should i change in configuration to get this test running?
regards

**Comment by pieterlange** [comment]
best to wait for actual support in kube-aws for 1.2 :) see PR #355

**Comment by aaronlevy** [comment]
FWIW, we created a new build `v1.2.0_coreos.1` which resolves this issue. @lukasz-bielinski can you let me know if that build resolves your issue?

**Comment by aaronlevy** [comment]
I just want to note that we are still working through an issue on the image hosting side (so the fixed image isn't available yet). See: https://github.com/coreos/coreos-kubernetes/issues/363

**Comment by aaronlevy** [comment]
The `1.2.0_coreos.1` image is available now, and that container contains the fix for this issue.
