### ISSUE TITLE
kube-aws: instance names should be prefixed (or postfixed) with cluster name

### ISSUE THREAD

**Issue by cgag** [coreos/coreos-kubernetes#371]
Monitoring EC2 is a mess when every instance is named "kube-aws-worker".

**Comment by aaronlevy** [comment]
Related: https://github.com/coreos/coreos-kubernetes/issues/221

**Comment by mumoshu** [comment]
@cgag @aaronlevy I have submitted the PR https://github.com/coreos/coreos-kubernetes/pull/435 for this. Would you mind reviewing it?
