### ISSUE TITLE
kubelet is unable to mount NFS volumes for a pod

### ISSUE THREAD

**Issue by groner** [coreos/coreos-kubernetes#372]
I've tried both CoreOS 991.2.0 and CoreOS 1000.0.0 with `quay.io/coreos/hyperkube:v1.1.8_coreos.0`.  In both cases the pods having NFS mounts fail.

Here is what strace reveals.
```
core@ip-10-0-24-116 /etc/systemd/system $ sudo strace -f -p 13201 -vs1024 -e execve,mount
Process 13201 attached with 14 threads
Process 17904 attached
[pid 17904] execve("/bin/mount", ["mount", "-t", "nfs", "files:/mnt/files", "/var/lib/kubelet/pods/86e248cc-f761-11e5-90a3-06f47eab549b/volumes/kubernetes.io~nfs/data"], ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]) = 0
[pid 17904] mount("files:/mnt/files", "/var/lib/kubelet/pods/86e248cc-f761-11e5-90a3-06f47eab549b/volumes/kubernetes.io~nfs/data", "nfs", MS_MGC_VAL, NULL) = -1 EINVAL (Invalid argument)
[pid 17904] +++ exited with 32 +++
```

I am able to perform the mount by hand, on the host.  Here is what strace of that looks like.
```
core@ip-10-0-24-116 /etc/systemd/system $ sudo strace -f -vs1024 -e execve,mount mount files:/mnt/files /mnt/files
execve("/bin/mount", ["mount", "files:/mnt/files", "/mnt/files"], ["COREOS_PRIVATE_IPV4=10.0.24.116", "COREOS_PUBLIC_IPV4=52.87.155.66", "TERM=screen-256color", "PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/mnt/host/source/chromite/bin", "LESSCHARSET=utf-8", "MAIL=/var/mail/root", "LOGNAME=root", "USER=root", "USERNAME=root", "HOME=/root", "SHELL=/bin/bash", "SUDO_COMMAND=/bin/strace -f -vs1024 -e execve,mount mount files:/mnt/files /mnt/files", "SUDO_USER=core", "SUDO_UID=500", "SUDO_GID=500"]) = 0
Process 18450 attached
[pid 18450] execve("/sbin/mount.nfs", ["/sbin/mount.nfs", "files:/mnt/files", "/mnt/files", "-o", "rw"], ["COREOS_PRIVATE_IPV4=10.0.24.116", "COREOS_PUBLIC_IPV4=52.87.155.66", "TERM=screen-256color", "LESSCHARSET=utf-8", "LOGNAME=root", "USER=root", "USERNAME=root", "SUDO_COMMAND=/bin/strace -f -vs1024 -e execve,mount mount files:/mnt/files /mnt/files", "SUDO_USER=core", "SUDO_UID=500", "SUDO_GID=500"]) = 0
[pid 18450] mount("files:/mnt/files", "/mnt/files", "nfs", 0, "vers=4.2,addr=10.0.0.184,clientaddr=10.0.24.116") = -1 EPROTONOSUPPORT (Protocol not supported)
[pid 18450] mount("files:/mnt/files", "/mnt/files", "nfs", 0, "vers=4.1,addr=10.0.0.184,clientaddr=10.0.24.116") = 0
[pid 18450] +++ exited with 0 +++
```

**Comment by groner** [comment]
Copying `/sbin/mount.nfs` and `/lib64/libtirpc.so.1` into the container root, and running `ldconfig -r ROOT` gets NFS mounts to succeed.

I also ran into a problem with private DNS being unavailable in the kubelet container.  I used the `RKT_OPTS` fix described in #367 to work around this.

**Comment by groner** [comment]
I'm not sure where the CoreOS hyperkube images come from.  Is there somewhere I should send this?

**Comment by aaronlevy** [comment]
This is an appropriate place to track this issue. For reference the coreos hyperkube images are built from the release branches in the coreos/kubernetes repo: https://github.com/coreos/kubernetes/tree/coreos-hyperkube-v1.1.8/coreos

It is still somewhat in discussion how mount tools should be handled when running the containerized kubelet. One option is simply adding them to the hyperkube container. Another (longer term) option might be using shared mounts and 'utility' containers such that the tools themselves could be distributed independently of the application container, but then exposed via mounts.

**Comment by groner** [comment]
Thanks for the pointer.  Adding nfs-common to the hyperkube Dockerfile worked to create a hyperkube image that can mount NFS.

**Comment by dtomcej** [comment]
These tools are also missing on the v1.2.0_coreos and v1.2.2_coreos images as well.

Following the CoreOS kubernetes deployment guide does not allow for NFS mounts for this reason.

**Comment by nishen** [comment]
Any idea when this might be added?

**Comment by kayrus** [comment]
The workaround is to download and execute kubelet binary directly on coreos host.

**Comment by jonaz** [comment]
Any progress here? This is a show stopper for deploying coreos with kubernetes in production. 

I would be nice to be able to do that according to the official install instruction and not needing to create a variant kubelet.service which downloads kubelet directly to host instead.

**Comment by robszumski** [comment]
The workaround for now is to mount in whatever you may require from the host as a volume, with `RKT_OPTS`:

https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html#customizing-rkt-options

For example, mounting in the host's resolv.conf:

```ini
[Service]
Environment="RKT_OPTS=--volume=resolv,kind=host,source=/etc/resolv.conf --mount volume=resolv,target=/etc/resolv.conf"
Environment=KUBELET_VERSION=v1.2.3_coreos.0
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=http://127.0.0.1:8080 \
  --config=/etc/kubernetes/manifests
```

**Comment by aaronlevy** [comment]
This only sort of works for nfs. It would require mounting both `/sbin/mount.nfs` and a missing shared library. Where this gets weird is that you're relying on most shared libs existing in the container (debian), but then a single shared lib from the host (coreOS). Last time I tested this it required bind mounting `/lib64/libtirpc.so.1` to `/usr/lib/x86_64-linux-gnu/libtirpc.so.1` -- but this was just mucking around and not something I would really recommend doing.

**Comment by jonaz** [comment]
This seems to be fixed in https://github.com/coreos/kubernetes/releases/tag/v1.2.4%2Bcoreos.1

**Comment by Rio** [comment]
`nfs-common` is installed on it yes but I still can't get nfs to mount due to `rpc.statd` not running.
Found that after determining the kubelet doesn't get the dns settings from the host it's running so doesn't resolve the storage urls.

**Comment by robszumski** [comment]
@Rio Did you try this? https://github.com/coreos/coreos-kubernetes/issues/372#issuecomment-218514725

**Comment by Rio** [comment]
@robszumski I had tried it several times and in several ways but it never worked. Kept getting access denied errors. However I just tried it again and now it does work. So just ignore what I said earlier ;)

**Comment by alexanderkiel** [comment]
I have still the `rpc.statd` problem with CoreOS 1010.5.0 and v1.2.4_coreos.1.

```
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
```

**Comment by plaflamme** [comment]
Same message on CoreOS `1068.0.0` and `v1.2.4_coreos.1`

**Comment by kbrwn** [comment]
@plaflamme. can you share your /etc/systemd/systemd/kubelet.service file? After updating my kubelet to `v1.2.4_coreos.1` my nfs share was able to mount into pods.

**Comment by plaflamme** [comment]
@kbrwn here you go:

```
core@w2 ~ $ cat /etc/systemd/system/kubelet.service 
[Service]
Environment=KUBELET_VERSION=v1.2.4_coreos.1
Environment=KUBELET_ACI=quay.io/coreos/hyperkube
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStart=/usr/lib/coreos/kubelet-wrapper   --api-servers=https://172.17.4.101   --network-plugin-dir=/etc/kubernetes/cni/net.d   --network-plugin=   --register-node=true   --allow-privileged=true   --config=/etc/kubernetes/manifests   --hostname-override=172.17.4.202   --cluster_dns=10.3.0.10   --cluster_domain=cluster.local   --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml   --tls-cert-file=/etc/kubernetes/ssl/worker.pem   --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
core@w2 ~ $
```

**Comment by plaflamme** [comment]
Interestingly, it eventually succeeded at mounting the volume, but only after I manually called `sudo mount.nfs` on that node to test that I was able to mount the volume manually.

For some reason, `rpc.statd` kept failing to start. Here's the relevant information from `journalctl`

```
Jun 09 02:13:40 w2 rpc.statd[7604]: Version 1.2.8 starting
Jun 09 02:13:40 w2 rpc.statd[7604]: Flags: TI-RPC
Jun 09 02:13:40 w2 rpc.statd[7604]: Failed to read /var/lib/nfs/state: Success
Jun 09 02:13:40 w2 rpc.statd[7604]: Initializing NSM state
Jun 09 02:13:40 w2 rpc.statd[7604]: failed to create RPC listeners, exiting
Jun 09 02:13:40 w2 kubelet-wrapper[1784]: E0609 02:13:40.430525    1784 kubelet.go:1780] Unable to mount volumes for pod "kube-registry-v0-51t17_kube-system(598b3299-2de6-11e6-a739-0800273afbf4)": Mount failed: exit status 32
Jun 09 02:13:40 w2 kubelet-wrapper[1784]: Mounting arguments: 192.168.0.102:/Docker /var/lib/kubelet/pods/598b3299-2de6-11e6-a739-0800273afbf4/volumes/kubernetes.io~nfs/kube-system-kube-registry-pv nfs []
Jun 09 02:13:40 w2 kubelet-wrapper[1784]: Output: mount.nfs: rpc.statd is not running but is required for remote locking.
Jun 09 02:13:40 w2 kubelet-wrapper[1784]: mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
Jun 09 02:13:40 w2 kubelet-wrapper[1784]: mount.nfs: an incorrect mount option was specified
Jun 09 02:13:40 w2 kubelet-wrapper[1784]: ; skipping pod
```

This repeated itself for about 15 minutes until this:

```
Jun 09 02:28:28 w2 sudo[22155]:     core : TTY=pts/0 ; PWD=/home/core ; USER=root ; COMMAND=/sbin/mount.nfs 192.168.0.102:/Docker /tmp/patate/
Jun 09 02:28:28 w2 sudo[22155]: pam_unix(sudo:session): session opened for user root by core(uid=0)
Jun 09 02:28:28 w2 sudo[22155]: pam_systemd(sudo:session): Cannot create session: Already running in a session
Jun 09 02:28:28 w2 dbus[691]: [system] Activating via systemd: service name='org.freedesktop.PolicyKit1' unit='polkit.service'
Jun 09 02:28:28 w2 systemd[1]: Starting Authorization Manager...
Jun 09 02:28:28 w2 polkitd[22165]: Started polkitd version 0.113
Jun 09 02:28:28 w2 polkitd[22165]: Loading rules from directory /etc/polkit-1/rules.d
Jun 09 02:28:28 w2 systemd[1]: Started Authorization Manager.
Jun 09 02:28:28 w2 polkitd[22165]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 09 02:28:28 w2 polkitd[22165]: Finished loading, compiling and executing 3 rules
Jun 09 02:28:28 w2 dbus[691]: [system] Successfully activated service 'org.freedesktop.PolicyKit1'
Jun 09 02:28:28 w2 polkitd[22165]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 09 02:28:28 w2 polkitd[22165]: Registered Authentication Agent for unix-process:22161:131523 (system bus name :1.61 [/usr/bin/pkttyagent --notify-fd 4 --fallback], object path /
org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 09 02:28:28 w2 systemd[1]: Starting RPC Bind...
Jun 09 02:28:28 w2 systemd[1]: Reached target Host and Network Name Lookups.
Jun 09 02:28:28 w2 systemd[1]: Started RPC Bind.
Jun 09 02:28:28 w2 systemd[1]: Reached target RPC Port Mapper.
Jun 09 02:28:28 w2 systemd[1]: Starting NFS status monitor for NFSv2/3 locking....
Jun 09 02:28:28 w2 rpc.statd[22203]: Version 1.3.2 starting
Jun 09 02:28:28 w2 rpc.statd[22203]: Flags: TI-RPC
Jun 09 02:28:28 w2 rpc.statd[22203]: Failed to read /var/lib/nfs/state: Success
Jun 09 02:28:28 w2 rpc.statd[22203]: Initializing NSM state
Jun 09 02:28:28 w2 rpc.statd[22203]: Running as root.  chown /var/lib/nfs to choose different user
Jun 09 02:28:28 w2 systemd[1]: Started NFS status monitor for NFSv2/3 locking..
Jun 09 02:28:28 w2 polkitd[22165]: Unregistered Authentication Agent for unix-process:22161:131523 (system bus name :1.61, object path /org/freedesktop/PolicyKit1/AuthenticationAgen
t, locale en_US.UTF-8) (disconnected from bus)
Jun 09 02:28:28 w2 sudo[22155]: pam_unix(sudo:session): session closed for user root
```

So it looks like I ssh'ed into the node and tried to mount the volume manually which succeeded (because I later unmounted it). This seems to have successfully started `rpc.statd` which I guess then allowed the volume to be mounted correctly, because the pod successfully started soon after.

So it seems like `rpc.statd` fails to start until it was started as `root`. Maybe it's using the wrong privileges?

**Comment by samnag** [comment]
I was seeing same issue trying to mount nfs/3 through kubernetes with coreos 1010.6.0 and hyperkube v1.2.4_coreos.1
```
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
```
```
<timestamp> <host> rpc.statd[16092]: Version 1.2.8 starting
<timestamp> <host> rpc.statd[16092]: Flags: TI-RPC
<timestamp> <host> rpc.statd[16092]: Failed to read /var/lib/nfs/state: Success
<timestamp> <host> rpc.statd[16092]: Initializing NSM state
<timestamp> <host> rpc.statd[16092]: failed to create RPC listeners, exiting
```
Fixed it by starting the rpcbind service defined in `/usr/lib/systemd/system` - with `systemctl start rpcbind`. Maybe there should be a hook in kubelet when mounting nfs/3 ?
After rpcbind was started everything worked as expected.

**Comment by nballotta** [comment]
Hi, same problem here. Manually mounting the share on the node with sudo, done the trick. 

Tested on CoreOS stable (1010.6.0).

**Comment by cdpb** [comment]
same with hyperkube v1.3.0_coreos.1 with kubelet-wrapper on latest stable (1010.6.0)

**Comment by Orpheus2015** [comment]
Guys. any idea how to hot fix this? Its critical for us, we can't setup our prod properly! HELP!

**Comment by alogoc** [comment]
@Orpheus2015  You can create a service with the binary version of kubelet till this bug is fixed. I have been mounting NFS on kubernetes without any issues.

Add this on the service, the rest of the service you can find it here [https://coreos.com/kubernetes/docs/latest/deploy-master.html](url)

`[Service]
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStartPre=/usr/bin/mkdir -p /opt/bin
ExecStartPre=/usr/bin/curl -s -L -o /opt/bin/kubelet -z /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.2.4/bin/linux/amd64/kubelet
ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
`

**Comment by cdpb** [comment]
I don't have problems anymore with kubelet-wrapper v1.3.0. You can also try to switch to nfsv3 rather than nfsv4 - for whatever reason, that works for me. Or as alogoc suggested, use the binary

**Comment by stevesloka** [comment]
I am running CoreOS stable (1122.2.0) and can confirm I need to run `sudo systemctl start rpc-statd` then my NFS mounts will work.

**Comment by robszumski** [comment]
> I am running CoreOS stable (1122.2.0) and can confirm I need to run sudo systemctl start rpc-statd then my NFS mounts will work.

I think the more appropriate thing is to start/enable `nfs-client.target`, which has an `[Install]` section. This makes it more appropriate for starting via cloud-config/ignition for greater immutability.

**Comment by thomasliddledba** [comment]
Running: 
Kubernetes - v1.7.5+coreos.1
Tectonic - 1.7.5+tectonic.1

`systemctl start rpc-statd` fixed my issue (described by @alexanderkiel).
Also
`systemctl enable rpcbind` to enable it
