### ISSUE TITLE
unable to run v1.2.0_coreos.[0-1]

### ISSUE THREAD

**Issue by jessesanford** [coreos/coreos-kubernetes#374]
If modify the kubernetesVersion to use v1.2.0_coreos.0 or v1.2.0_coreos.1 both of which are in the quay.io/coreos/hyperkube repository I get the cluster up and running but then get lots of error messages about the kube-system namespace not existing. When I create that namespace the system does not continue to create the various 'kube-' services. I am able to create controllers secrets and services because the api is up and running but all the containers inside the pod do not have dns because the kube-dns service is not running. Has anyone successfully used kube-aws to run >=1.2.0?

**Comment by aaronlevy** [comment]
It's possible you're running into an issue where the api now requires content-type headers. This was causing curl requests to fail, which are used to create kube-system namespace and subsequent addons.

The issue has been fixed here: https://github.com/coreos/coreos-kubernetes/pull/341

**Comment by aaronlevy** [comment]
@jessesanford any updates?

**Comment by jessesanford** [comment]
Sorry that was the issue. You can close this. I was able to get things working by updating everything to pass the content type headers as you said. Nice guess!
