### ISSUE TITLE
Issue with DNS when redeploying kubernetes cluster on to same nodes 

### ISSUE THREAD

**Issue by karthikus** [coreos/coreos-kubernetes#376]
I am trying to redeploy kubernetes on to the same cluster (with new set of keys etc.). As a part of re-deployment, I delete several kubernetes directories on the host. Additionally, I remove all pods from rkt, unmount and delete the /var/lib/kubelet directory.

After redeployment all services come up, the master could talk to the workers except for the DNS service. I get the following error with DNS service.

`E0402 00:51:33.668674       1 reflector.go:136] Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
` 

When I delete the nodes (VMs) and create a new set of nodes and deploy the kuberenetes everything works well. Also, as stated in [Turning down the cluster](http://kubernetes.io/docs/getting-started-guides/docker/) section, something is left behind for DNS services that causes this error. How can I make sure I have a clean set of nodes for kubernetes redeployment ?

**Comment by colhom** [comment]
@karthikus can you try deleting the kubernetes service token secret in your kube-system namespace? It should be re-generated, at which point you can destroy the DNS pod and let the RC re-create it. Let me know if this fixes your problem?

**Comment by Rio** [comment]
This fixed it for me. Switching certificates can be confusing if you don't really know how kubernetes uses tokens and stuff. thanks

**Comment by aaronlevy** [comment]
Closing this particular issue, but feel free to open an issue about adding docs (or even a PR!) for switching certificates.
