### ISSUE TITLE
Kubelet often fails with dependency on AWS Instance reboot

### ISSUE THREAD

**Issue by rwillard** [coreos/coreos-kubernetes#377]
When AWS instance reboots, the kubelet often fails with dependency. Connecting to the instance and manually restarting the kubelet works fine though.

**Comment by colhom** [comment]
@rwillard can you post the output that you're seeing? I assume "fails with dependency" is referring the the `kubelet.service` systemd job?

**Comment by rwillard** [comment]
Yeah that was for the `kubelet.service` systemd job. It doesn't happen every time, and could be changed with the 1.2 release. I believe the only thing it depends on is docker, so if docker is slow to start it will fail is my guess.

**Comment by aaronlevy** [comment]
I'm going to close this issue, as I believe this is related to: https://github.com/coreos/coreos-kubernetes/issues/545 and there's some helpful discussion there.
