### ISSUE TITLE
Unable to initialize an asset directory. kube-aws init command missing

### ISSUE THREAD

**Issue by elifarley** [coreos/coreos-kubernetes#378]
Following instructions from an article about installing and using [Kubernetes on AWS](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html), I've [downloaded the kube-aws tool](https://github.com/coreos/coreos-kubernetes/releases) version 0.5.1

The README section on [initializing an asset directory](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/README.md#initialize-an-asset-directory) suggests using kube-aws' init command, like so:

```bash
$ kube-aws init --cluster-name=my-cluster-name \
[...]
```
However, this doesn't work:

> Error: unknown command "init" for "kube-aws"

**Comment by cgag** [comment]
I just tried to reproduce this and couldn't.  Can you provide any more information?  Are you on linux or OSX?  Any chance there's an old version on your path that's being used? Can you double check the output of `kube-aws version`? Were you able to successfully verify the binary with gpg?

**Comment by elifarley** [comment]
Sorry for the noise. As I was playing with some other tools like Otto and Deis, one of these had probably installed an older version of kube-aws...

DUH! :dizzy_face:
