### ISSUE TITLE
ECR on Kubernetes 1.2.0

### ISSUE THREAD

**Issue by elohr** [coreos/coreos-kubernetes#381]
IAMRoleWorker will need this policy to be able to take advantage of the functionality of pulling images from ECR on AWS:

```
            {
                "Action": [
                    "ecr:GetAuthorizationToken", 
                    "ecr:BatchGetImage"
                ], 
                "Resource": "*", 
                "Effect": "Allow"
            }
```
[https://github.com/kubernetes/kubernetes/issues/23777](url)

**Comment by spacepluk** [comment]
I was just looking into this :)

I had to add also `ecr:GetDownloadUrlForLayer` to make it work.

**Comment by aaronlevy** [comment]
closed in: https://github.com/coreos/coreos-kubernetes/pull/384
