### ISSUE TITLE
default recordSetTTL is 0

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-kubernetes#400]
If `recordSetTTL` is left commented out in cluster.yaml, `kube-aws up` fails:

```sh
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: TTL must be at least 1 second
```

@cgag in order to fix this, we need to:
* set the default TTL value [here](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/config.go#L31)

* validate the TTL value [here](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/config.go#L329) as part of config validation

* add test cases for default value, invalid value, and valid value to `pkg/config/config_test.go`

**Comment by cgag** [comment]
Dang, I had it defaulted to 300 and forgot to set it when I made it configurable. Anyway, fixed and moved the validation into the config validation from the cluster validation.  Moved the check that hostedZone isn't blank over as well.
