### ISSUE TITLE
kubelet config has both --kubeconfig and --tls-* options

### ISSUE THREAD

**Issue by tomdee** [coreos/coreos-kubernetes#408]
I believe that if you specify the kubeconfig, there's no need to specify tls-cert-file too.

e.g. 
```
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=${CONTROLLER_ENDPOINT} \
  --register-node=true \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --hostname-override=${ADVERTISE_IP} \
  --cluster_dns=${DNS_SERVICE_IP} \
  --cluster_domain=cluster.local \
  --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
  --tls-cert-file=/etc/kubernetes/ssl/worker.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem
Restart=always
RestartSec=10
```

**Comment by aaronlevy** [comment]
The certs specified in the kubeconfig are used for outbound connections (both as server and client validation).

However, the kubelet also has its own api (e.g. for exec/logs). When the apiserver is dialing the kubelet the certs specified on the cli (--tls-cert-file --tls-private-key-file) are what are used for tls termination by the kubelet api. If they were only specified in the kubeconfig, it wouldn't know to use those values (and instead would default to using the kubelet self-generated assets).

**Comment by tomdee** [comment]
OK, that makes sense.
