### ISSUE TITLE
kube-aws should create its own network ACL

### ISSUE THREAD

**Issue by joshma** [coreos/coreos-kubernetes#418]
From what I see, it looks like kube-aws relies on the default VPC ACL to be used for its subnet. When you launch into an existing VPC, though, depending on how the default ACL is configured (mine DENYs all just so I don't accidentally use it) you then need to switch its ACL to a new one.

It'd be nice if kube-aws included its own ACL in the cloudformation stack, even if it just ALLOWs everything.

**Comment by colhom** [comment]
> It'd be nice if kube-aws included its own ACL in the cloudformation stack, even if it just ALLOWs everything.

@joshma - I take it this is so the ACL is create for you and part of the cloudformation stack? One word of caution- if you modify the ACL after cloudformation has last touched it, you'll not be able to cleanly tear down the stack.

Suggestions on `cluster.yaml` configuration syntax for this feature. Are you interested in putting up a PR?

**Comment by joshma** [comment]
@colhom I'd say it's for two reasons:

1) so that it's managed by the CF stack like you say, so it's more cleanly separated out. We could do things like add some more explicit ALLOWs in the future if the ports are better defined - ideally we can only whitelist common ports rather than allow all. (It can mirror the security groups.)

2) folks with modified default ACLs will get a confusing experience if their default ACL doesn't allow e.g. SSH, which is what I ran into.

I think not being able to tear down the stack is annoying, but you'll run into it either way (assuming you need to modify the ACL). Currently you'll probably create a new ACL and assign it to the subnet, so that ACL will block tear down as well.

Does `cluster.yaml` need to change? Much like the security groups, it seems to me that kube-aws can do this without needing the user's input - I don't see any cases where auto-creating a managed ACL will be problematic.

I'd be happy to work on a PR if you can point me to the code that generates the CF template. I'm not using this for anything work-related, though, so it'll depend on when I have some free time. 😄

**Comment by colhom** [comment]
@joshma this would be a great complement to our work with integrating Calico with kube-aws. If you'd like to get started with a PR, you should check out the [cloudformation stack template](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/stack-template.json).

A good example for this project would be tracking the [vpcId](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/config.go#L113) configuration parameter through the [config parsing](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/config.go#L170), [templating](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/config.go#L311), and [AWS API interaction](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/cluster/cluster.go#L81) stages of the pipeline.

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
