### ISSUE TITLE
[Kube-Aws 0.6.1] Cloud-Config is garbled when converted to AWS ec2 instance User-Data

### ISSUE THREAD

**Issue by gabe-ochoa** [coreos/coreos-kubernetes#429]
The User-Data contained with the launch configurations that are created by the kube-aws tool look to be garbled. I see the encoded User-Data in the CloudFormation template (sample below) but the User-Data in the launch configuration created by that CloudFormation template is garbled (sample below). 

I was attempting to update the worker launch configuration to test out a different instance type on a running cluster and any machine from the copied launch configuration were unresponsive after start up. 

```
kube-aws version: v0.6.1
Kubernetes version: 1.2.2
CoreOS Kubernetes Image: v1.2.2_coreos.0
CoreOS Version: 1010.1.0
```

User-Data sample from CloudFormation template:

```
H4sIAAAJbogA/5x6547jSJPg/3kK3ez3Y/e01fSuD30APSWSomhESrw7DCh6752wD39UVfW0HbfVQEPKjAyX4VIR/+YX9Ri8+HUVpfEvft2Fdf/xl91ubAJvCJ+fdrsuvNf18NIP3bYUrx93v9ZR9Ou2FRVeVYXFG1RaDWEXeX74cfevpkunDfa3tJnQ181w8IPfwipo6g2s/7hLhqH5CAAQ+OH5DwM/wghBPclW6dC/4XvZVV65IQtqPw+7D33YTakfvm7tdkFXNy9p9Q76NTgKvryz9eEp1O/7u932dQir4ePuv75a3O3+z2Wj+f++WTLCdky7sP/0jin4jvrbHx1tAv8I8g3z+XgPi3D47nxYefdi2x268fOSX5elVwUfd/3gdcMvf8jxd9z+zulPtfSZx+82vyAz31a+4OOrKe3qqtyofpIvDK/w1m82b5gH7fRpgj7AH+Df3mzkA/inZ2j28KkdvfVDWgNvB4BkbcLuqY+fHvzVkK3ftLNlfnp5mepiLMNdUPX/madV8Cmp++E/+3rs/PATsFkSsAlcF9Pr/e5eXsp6rIbd26FPz0ObBuNw+AH01y+El9A3n3r+BIx9BxTp/TOT7/f1Mndes7G7+79f7OvFa9KXpwrDrv/0tN/+GwNGUeQb6C6M035T/ktVB+Gn501/i6wo6vnl6SdpEcZh8CPEm0u+SfFkq6vCIeyBzUrSKOyH/lvgYnwS+20T/9PGE7LxBIE/h6hLL60+vX/9UNS+V3wH+AwITVdPabDZjjd/S+nJyh+wNtfdZmZfQXxYvfJb5EPRv/hhN7xEm9g/IOj74h3JhyYsfzj4HlVe8nD9q/NPmCeOrxzl1bE+ecXsrf33y2bob2r74heHalsuii9+4XibJwbM+qkciyF9GTc7+PBmZt/6exD63doMr+x6fR8O/d9x/b/yci7s/S5thrSuPr1T+BxZdhul3Rul3dinVbzzSu9RV7u8/CIlE0abeX/6eTD6gyDxRUM/jzB/EkSszdM/1VXYJ/XwFZ6n3b2S4pd0+LSG/c/8sW4G4J5WwI+K/OVPruedyecFfS/kL3OXbpnoaS+v2eJl13hD8nH357b3lrQqvw42lX7cxY+02d+9PsTf0tnvVyah/YGm6eO9jmlg5m4MGxFsymGF2BQBCUFqpM3Cot1QzLOj9nI+emAk+6fHHReDZV7BSyI/WJ1n6JhB967RutfoFFjSo2d8q9Q0p7jiBbc6g7RWnA/vk8r31UF4kjRl9XDgk/h2lGv3kEz+idZ9sd7WggfLMpLK0jo9x7HRM3HeJnkqUjPIMDM/
```

User-Data sample from LaunchConfiguration:

```
    nÿzçãHàÿy
Ýì÷c÷´Õô®}=%¢hDJ¼;(zï°TUõ´·Õ@CÊáRÿæõ¼øu¥ñ/~ÝuÿñÝnlov».¼×õðÒÝ¶¯w¿ÖQôë¶^UÅTZ
ay~øq÷¯¦K§
ö·´Ð×ÍpðßÂ*hê
¬ÿ¸K¡ùøáù?ÂA=ÉVéÐ¿á{ÙU^¹!j?»}ØM©¾nívAW7/iõú58
¾¼³õá)Ôïû»Ýöu«áãî¿¾ZÜíþÏe£ùÿ¾Y2ÂvL»°ÿô)øúÛmÿò
óùxpøî|Xy÷bÛºñó_¥WwýàuÃ/ÈñwÜþÎéOµôÇï6¿ 3ßV¾àã«)íêªÜ¨~/¯ðÖo6oíôi>ÀàßÞläø§ghöð©½õCZodmÂî©üÕ­ß´³e~zyêb,Ã]Põÿ§Uð)©ûá?ûzìüð°Y°   \Óëýî^^Êz¬ÝÛ¡OÏCãpøô×/Ð7zþ}éý3ï÷õ2w^³±»û¿_ìëÅkÒ§
Ã®ÿô´ßþFQäè.Ó~SþKUá§çM¬(êùåé'iÆað#ÄK¾Iñd««Â!ìÍJÒ(ìþ[àb|ûmÿÓÆ²ñ?¨K/­>½ýPÔ¾W|øMWOi°Ù7KéÉÊ°6×Ýff_A|X½ò[äCÑ¿øa7¼DØ? èûâÉ&,8øU^òpý«óO'¯åÕ±>yÅì­ý÷Ëfèojûâj[./~áx'Ìú©!}7;øðffßú{úÝÚ¯ìz}ýßqý¿òr.ìý.m´®>½SøYv¥Ý¥ÝØ§U¼óJïQW»¼ü"%Fyúy0ú ñEC?0D¬ÍÓ?ÕUØ'õð§Ý½âtø´ýÏü±nàVÀüåO®çÉç}/ä/snèi/¯Ùâe×xCòq÷ç¶÷´*¿6~ÜÅ´Ùß½>ÄßÒÙïW&¡ý¦éã½i`ænlÊaØ Aj¤ÍÂ¢ÝPÌ³£ör>z`$û§Çe^ÁK"?XgèA÷®Ñº×èXÒ£g|«Ô4§¸â·:´VïÊ÷ÕAx4eõpàøvk÷LþÖ}±ÞÖË2ÊÒ:=Ç±Ñ3qÞ&y*R3È03?KÛÛÁ=ÐÎch~TçÜ*©ÑEÚ×ó
BõÃ6<4UÜ3GÂ/bTÞÌc u+3vÒË­[ÌNÁl7ià9áÇYõbO÷"fçP®y­Ãl²úER9 y OxmQ«ès?9IRls I-2"<íJ,Hê°F¦Ô_ê1\ÏAÊzm8f2)*Þ×3~;yx÷Ü%VÕ+íc­I..Ú   ¦ÁäÞÎÌ$fAcacÖ   Cm\,+ËÒáâpÇZpu]@ÄYÚ¢ÝKU(ßoðrifZ ?îU  sÆZ<"¸DX( F>üQ)>¼ûÎ,ÚÛÃ©  z@ÀÝ£ ¬åJ6$Õáãâ)÷N5M~fáÌa£$º±e®K·#JÁÃI¡Íêqh*è+apîÐî1U/YÀ¥RúC½í³y8£+PqRs0sóÒóv^]èÃ^×u¤W7âîÁskse  ì(¯ÚÅ]þ|=,çØ;öÂÁÎÎª£¥Û½>xÃèå¥"¹`áZÙ!ïp°+ÍäÓ:ù¾¦76¹k?T"H2"â}nnåì.
§»#ÂÖhcª®ÇÄþ<XJ3ùrvG[óaðÜ;ßyTÅðs¿ðê!|èÚ²w`¥*ò=Ô
Þ.§´®4!jbH@É±½KW×+ßõp&']DñÌ1D3qqe
Í§ý%]Lã®§*G[ºeÂ$;×F8.`òò}4óÁAÑZØ_¬ÉêÆNw(°³UUlnfÑ
#¢B¤­l0loßssYP÷¦ª<?WÆ    á"@à
```

Please let me know if any other information would be helpful. Thanks!

**Comment by colhom** [comment]
@gabe-ochoa did you modify any of the templates after `kube-aws render`? What do `user-data/cloud-config-{controller,worker}` files look like in your assets directory?

**Comment by gabe-ochoa** [comment]
@colhom We did modify the templates after `kube-aws render`. The user-data/cloud-config was modified to use a dedicated etcd cluster for the `kube-apiserver` and `flannel` endpoints. The etcd2 service on the controller was also switched to proxy mode pointing to the dedicated cluster. See the modified files attached.

[cloud-config.zip](https://github.com/coreos/coreos-kubernetes/files/234729/cloud-config.zip)

If there is a better way to go about pointing to a dedicated etcd cluster guidance would be much appreciated. I know there is an issue open to track the steps towards a true prod ready deployment with the `kube-aws` tool which I'm very excited about! 

Thanks!

**Comment by colhom** [comment]
@gabe-ochoa sorry for the radio silence on this. Have you seen this problem in recent versions of kube-aws?

**Comment by gabe-ochoa** [comment]
@colhom yes, still seeing it. The main alterations to the user-data and CF stack-template are endpoints for a discrete etcd cluster and to use gp2 storage. I've seen the PRs for both and am watching as they make their way through.

I put up a 1.2.4 cluster with kube-aws 0.7.1 this morning and still have the jumbled user-data in the launch configs. 

Thanks again for the help!

**Comment by aaronlevy** [comment]
May be totally off-base here, but @colhom aren't some of the assets gzipped? Or maybe all of the user-data is? might just be a matter of `cat user-data | gunzip`

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
