### ISSUE TITLE
Step by Step - Vagrant

### ISSUE THREAD

**Issue by tdeheurles** [coreos/coreos-kubernetes#43]
Hi,
I'm following the [kubernetes Step by Step](https://coreos.com/kubernetes/docs/latest/getting-started.html).
Everything is fine since I have an issue with the kube-controller.
This one request a cloud provider. If I provide `vagrant`, it fails telling that vagrant does not implement load-balancer.

Maybe a comment for vagrant can ne added at the start of the guide ? Or maybe i'm missing simply missing something for things to work ?

**Comment by aaronlevy** [comment]
We don't currently document setting the cloud-provider for vagrant installations. However, supporting various cloud-providers is on the roadmap.

The instructions you linked should still work on vagrant without setting the cloud-provider, and are nearly identical to how we deploy kubernetes in our vagrant reference installation: https://github.com/coreos/coreos-kubernetes/tree/master/single-node

Is there a specific functionality that you need from the vagrant cloud-provider?

**Comment by tdeheurles** [comment]
the kube-controller-manager gives an error :

```
 $ docker logs 22d1b1867440
I0916 08:17:51.126684       1 plugins.go:69] No cloud provider specified.
I0916 08:17:51.127772       1 nodecontroller.go:114] Sending events to api server.
E0916 08:17:51.128778       1 controllermanager.go:201] Failed to start service controller: ServiceController should not be run without a cloudprovider.
```

But it seems that this error is an error. The kubernetes team have a post talking about that and saying they need to remove that message.

It was confusing but it seems ok.

Thank you @aaronlevy
