### ISSUE TITLE
kube-aws: Provide more contexts on stack creation failed?

### ISSUE THREAD

**Issue by mumoshu** [coreos/coreos-kubernetes#430]
Hi, Thanks for sharing this!

I have just encountered the following error on `kube-aws up`:

```
$ kube-aws up
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [VPC, IAMRoleController, InternetGateway, IAMRoleWorker].
```

Looking into AWS console revealed that its cause was that CloudFormation failed to create a `AWS::EC2::InternetGateway`:
![image](https://cloud.githubusercontent.com/assets/16041074/14735203/9225e2b6-08aa-11e6-9ad2-c62b03a4cad3.png)

It was not very obvious just reading the message from `kube-aws`.
I guess if we could provide more context one can deal with errors more quickly.

Without thinking much, something like the following seems helpful for me:

> Stack creation failed.
> Printing recent events from Cfn which may or may not indicate what was problem:
> *snip*
> CREATE_FAILED	AWS::EC2::InternetGateway	InternetGateway	The maximum number of internet gateways has been reached.

Any thoughts?

**Comment by colhom** [comment]
@cgag brought this up previously

**Comment by robszumski** [comment]
It would be great to add this
