### ISSUE TITLE
kube-aws: Possibly clearer message on `kube-aws destroy`

### ISSUE THREAD

**Issue by mumoshu** [coreos/coreos-kubernetes#434]
Execuse me if this sounds like nitpicking but a tiny proposal regarding UX follows.

`kube-aws destroy` immediately returns with the message denoting that the cfn stack is already destroyed.

```
$ kube-aws destroy
Destroyed cluster
```

However, the destruction is just scheduled and takes several minutes until actually get deleted.

![image](https://cloud.githubusercontent.com/assets/22009/14804170/d3a9242a-0b9b-11e6-9b48-3955eadbf3d3.png)

It's an my off-the-cuff but would it be clearer for users to show a message like `CloudFormation stack is being destroyed.` or more shortly `Destroying cluster`, or make `kube-aws` wait for the completion of the destruction(IMO too much though)?

**Comment by cgag** [comment]
I definitely agree it shouldn't claim the cluster has been destroyed. Something like `CloudFormation stack is being destroyed. This will take several minutes`.  Want to submit a PR or do you want me to do it?

**Comment by mumoshu** [comment]
That message sounds nice! I'll submit a PR with it.

**Comment by mumoshu** [comment]
@cgag I have submitted the PR #445 for this.
I appreciate it if you or your colleague could review it 🙇
