### ISSUE TITLE
quay.io/coreos/hyperkube image for v1.2.3?

### ISSUE THREAD

**Issue by 0x777** [coreos/coreos-kubernetes#446]
Can you automate the release of this image whenever a new release of kubernetes rolls out?

**Comment by aaronlevy** [comment]
We are currently seeing some e2e/conformance test failures that we need to isolate as flakes: https://github.com/coreos/coreos-kubernetes/issues/380 but the v1.2.3 image release should be soon.

At the same time we also validate the release image against the installations based on the tool in this repo, so there are still some manual steps (e.g. update addons, build process, etc.)

Then the last step is also updating the image based any security issues that have been surfaced by [Clair vulnerability scans](https://github.com/coreos/clair) - which is currently a glibc update we're validating.

We're trying to tighten this process so we can release as close to upstream as possible, but there is still some delay (see above). It's definitely a goal to automate as much of this as possible.

In the interim, the same build process we use is documented in our release branches in the coreos/kubernetes repo. For example, for the v1.2.3 release you can build images following the readme here: https://github.com/coreos/kubernetes/tree/coreos-hyperkube-v1.2.3/coreos

**Comment by aaronlevy** [comment]
The v1.2.3 image has been released (https://quay.io/repository/coreos/hyperkube?tab=tags) and the tools in this repo will be updated to reference that image shortly.
