### ISSUE TITLE
/usr/lib/coreos/kubelet-wrapper does not exist on stable channel

### ISSUE THREAD

**Issue by arvinep** [coreos/coreos-kubernetes#448]
It's a new multi node setup,

DISTRIB_RELEASE=899.15.0

```
$ journalctl -b 
systemd[1408]: kubelet.service: Failed at step EXEC spawning /usr/lib/coreos/kubelet-wrapper: No such 
```

Following below link and manually created the wrapper:
https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html 

I understand that this wrapper is not shipped in "stable" channel and prior to 962.0.0 yet, but we should at least have it fixed in stable releases so kublet.service not throwing error. Thanks.

**Comment by pieterlange** [comment]
That's not really how the coreos release model works.. You can run the beta channel until stable catches up to 962

**Comment by colhom** [comment]
@arvinep the hard dependency is rkt version >= 1.0. If you check out https://coreos.com/releases, you'll see that stable actually has rkt 1.0. You should be able to drop the kubelet-wrapper script/ systemd service onto your filesystem and it should work until 962.x.x gets promoted to stable.

\cc @aaronlevy for sanity on this

**Comment by arvinep** [comment]
hey @colhom I did the same and issue gone,
Just wanted to point this out that yet without this wrapper, kubelete.service won't start which means 
"kubectl get nodes" throwing following error:

```
$ kubectl get nodes
The connection to the server 172.17.4.101:443 was refused - did you specify the right host or port
```

**Comment by aaronlevy** [comment]
You are correct, if you use the stable release, it will not contain the kubelet-wrapper.

An option here might be to better document this as comments in the vagrant config file: 

https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/vagrant/config.rb.sample#L1
https://github.com/coreos/coreos-kubernetes/blob/master/single-node/Vagrantfile#L25

**Comment by aaronlevy** [comment]
The kubelet-wrapper is now included in the stable channel
