### ISSUE TITLE
Label node on worker creation

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#452]
Hi, 
I want to label all new nodes from an AWS autoscaling group.
I can achieve this manually with kubectl label node.... But I want to do this automatically when a new node is deployed.
How can I label a new node when it starts? There is some script to add in user-data?

**Comment by aaronlevy** [comment]
There is a `--node-labels` flag on the kubelet you can use. This will set the labels on a node on first registration. For example `--node-labels=foo=bar,baz=bat`.

You would need to add this flag to the kubelet service file which is rendered into `userdata/cloud-config-worker` (template: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cloud-config-worker#L29)

**Comment by arkkanoid** [comment]
thanks @aaronlevy
