### ISSUE TITLE
kubernetes does not fetch ecr access keys

### ISSUE THREAD

**Issue by Thermi** [coreos/coreos-kubernetes#461]
Hello,

It seems kubernetes does not fetch the ecr access keys via the EC2 API. This prevents it from pulling images from the AWS ECRs, barring me from deploying images from the ECR.
The error in the log looks like this:
```
2016-05-04 22:09:51 +0200 CEST   2016-05-04 22:12:47 +0200 CEST   5         zre       Pod                              Warning   FailedSync   {kubelet ip-172-16-4-25.eu-west-1.compute.intern
al}   Error syncing pod, skipping: failed to "StartContainer" for "zre" with ErrImagePull: "API error (500): Get https://<account number>.dkr.ecr.eu-west-1.amazonaws.com/v2/zre/manifests/latest:
 no basic auth credentials\n"
```
Trying via shell:
```
docker pull /<account number>.dkr.ecr.eu-west-1.amazonaws.com/zre
Using default tag: latest
Error response from daemon: Get https:///<account number>.dkr.ecr.eu-west-1.amazonaws.com/v2/zre/manifests/latest: no basic auth credentials
```
Giving the controller access to the ECR by giving it my ECR login (retrieved it using aws get ecr-login and ran the resulting command in a root shell on the controller) enabled it to get the image by using docker.

The ECR and the cluster are in the same region (eu-west-1). The cluster was set up via kube-aws on 2016-05-04. The cluster.yaml specifies hyperkube version v1.2.3_coreos.0. The IAM roles have policies attached to it, that allow it to access all ECR repositories of my account:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1462314918000",
            "Effect": "Allow",
            "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:DescribeRepositories",
                "ecr:GetAuthorizationToken",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:ListImages"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
Yes, the policy is really attached to the controller and the workers. I additionally rebooted the instances to make sure they apply.
Please tell me if you need anything else or find a solution to this problem.

**Comment by colhom** [comment]
@Thermi this is fixed and merged in #384. Thanks for the issue!
