### ISSUE TITLE
feature request: ship dashboard/ui by default

### ISSUE THREAD

**Issue by kbrwn** [coreos/coreos-kubernetes#464]
Many readers of the kubernetes documentation have come to expect that a dashboard will be automatically included in 1.2 clusters due to this line in the docs: 

"By default, the Kubernetes Dashboard is deployed as a cluster addon. For 1.2 clusters it is enabled by default." 

We are on 1.2.x but don't include a dashboard by default. This confuses some new users of k8s. Yes we could just PR the upstream docs to say something like:

"By default, the Kubernetes Dashboard is deployed as a cluster addon. For 1.2 clusters deployed via kube-up.sh, it is enabled by default."

But I think that shipping a UI is worth discussing since it is something that upstream has decided to include and that k8s competitors include by default as well.

Perhaps instead of [kubernetes-dashboard](https://github.com/kubernetes/dashboard) we could ship a variant of Tectonic Console? @sym3tri @joeatwork

**Comment by sym3tri** [comment]
We should ship the open-source dashboard with the base coreos-kubernetes install. Tectonic Console will remain a part of the Tectonic product line.

**Comment by pbx0** [comment]
We ship the dashboard addon now. I think we can close this.
