### ISSUE TITLE
Too many processes in process table

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#469]
Hi, I'm running multiple apllications on a large instance with Kubernetes 1.2.0.
For testing purposes, I've deployed a web-app with 50 replicas. All replicas are deployed, but about 5 applications show an error:

    INFO spawnerr: Too many processes in process table to spawn 'nginx'

and

    INFO spawnerr: Too many processes in process table to spawn 'php5-fpm'

All new applications show this error. It means that the process table is full!?
The application base runs supervisord and Nginx, 

ps aux | wc -l

    416

cat /proc/sys/kernel/pid_max

    32768

ulimit -a
    
    core file size          (blocks, -c) unlimited
    data seg size           (kbytes, -d) unlimited
    scheduling priority             (-e) 0
    file size               (blocks, -f) unlimited
    pending signals                 (-i) 61083
    max locked memory       (kbytes, -l) 64
    max memory size         (kbytes, -m) unlimited
    open files                      (-n) 1024
    pipe size            (512 bytes, -p) 8
    POSIX message queues     (bytes, -q) 819200
    real-time priority              (-r) 0
    stack size              (kbytes, -s) 8192
    cpu time               (seconds, -t) unlimited
    max user processes              (-u) 61083
    virtual memory          (kbytes, -v) unlimited
    file locks                      (-x) unlimited

**Comment by bacongobbler** [comment]
This looks like something that should be posted to supervisor's repo. coreos-kubernetes won't likely have the answer you're looking for. See https://github.com/Supervisor/supervisor/blob/769da42d4cff9195924738b8e6095853df53f50a/supervisor/process.py#L237-L244

**Comment by arkkanoid** [comment]
I've the same problem with a basic Nginx App. Also, when this happens other services are unvailable, for example I can't connect to the node via SSH:

    May 11 09:22:51 ip-10-0-0-118.eu-west-1.compute.internal systemd[1]: sshd@0-10.0.0.118:22-X.X.X.X:47650.service: Failed to fork: Resource temporarily unavailable
    May 11 09:22:51 ip-10-0-0-118.eu-west-1.compute.internal systemd[1]: sshd@0-10.0.0.118:22-X.X.X.X:47650.service: Failed to run 'start' task: Resource temporarily     unavailable
    May 11 09:22:51 ip-10-0-0-118.eu-west-1.compute.internal systemd[1]: Failed to start OpenSSH per-connection server daemon (X.X.X.X:47650).
    May 11 09:22:51 ip-10-0-0-118.eu-west-1.compute.internal systemd[1]: sshd@0-10.0.0.118:22-X.X.X.X:47650.service: Unit entered failed state.
    May 11 09:22:51 ip-10-0-0-118.eu-west-1.compute.internal systemd[1]: sshd@0-10.0.0.118:22-X.X.X.X:47650.service: Failed with result 'resources'.

I've seen a new systemd attribute "TaskMax": http://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

But it seems that my docker service hasn't this limit:

    docker.service - Docker Application Container Engine
       Loaded: loaded (/usr/lib64/systemd/system/docker.service; disabled; vendor preset: disabled)
      Drop-In: /etc/systemd/system/docker.service.d
               └─40-flannel.conf, 50-insecure-registry.conf
       Active: active (running) since Wed 2016-05-11 09:12:14 UTC; 42min ago
         Docs: http://docs.docker.com
     Main PID: 1048 (docker)
        Tasks: 743
       Memory: 1.1G
          CPU: 2min 56.742s
       CGroup: /system.slice/docker.service

**Comment by mischief** [comment]
you are probably running into the cgroup pids controller limit. systemd sets TasksMax to 512 by default in a very recent version of CoreOS. docker itself had this limit raised, but everything else is running at 512 tasks (processes+threads+kernel threads) max by default.

**Comment by arkkanoid** [comment]
Close in favor of https://github.com/coreos/bugs/issues/1266
