### ISSUE TITLE
Unable to update CloudFormation stack if AutoScaleWorker resource changes

### ISSUE THREAD

**Issue by danielfm** [coreos/coreos-kubernetes#476]
Currently, `kube-aws` uses the same number for the minimum, maximum, and desired node quantities at `"AutoScaleWorker"` resource in the CloudFormation stack template:

````js
"AutoScaleWorker": {
  "DesiredCapacity": "{{.WorkerCount}}",
  "MaxSize": "{{.WorkerCount}}",
  "MinSize": "{{.WorkerCount}}"
}
````

The side effect of this decision is that it's impossible to update the stack if there's any change in the `"AutoScaleWorker"` resource (i.e, when changing `workerInstanceType`). This is the error message when that happens:

````
MinInstancesInService must be less than the autoscaling group's MaxSize
````

My quick workaround was to append a zero to the `"MaxSize"` value, like this...

````js
"AutoScaleWorker": {
  "DesiredCapacity": "{{.WorkerCount}}",
  "MaxSize": "{{.WorkerCount}}0",
  "MinSize": "{{.WorkerCount}}"
}
````

...but that's not ideal. Of course, I changed the maximum number of nodes after the stack update was completed. =]

**Comment by colhom** [comment]
Ref #340 

Cluster upgrade path is a top priority.
