### ISSUE TITLE
Update user-data with kube-aws

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#485]
Hi, 
I want to modify the worker user-data configuration in a cluster that it's already running.
I've modified some parameters in the cloud-config-worker file, and then I run kube-aws render, which shows:

    Error: mkdir credentials: file exists

I don't want to modify the existing credentials. Moreover, I can't modify the userdata set in the cloudformation-template due to it's encrypted.

How can I modify the user-data without create new credentials / stack?

**Comment by colhom** [comment]
See the first item in #340. As of now, you can do this today. (Assume starting out with a freshly-created cluster)

```sh
vim userdata/cloud-config-controller #and/or worker
kube-aws up --export
```
Then take that JSON file that's produced by `--export` and use it to update your cloudformation stack via AWS api, cli or web interface.

**Comment by colhom** [comment]
@arkkanoid if your question has been answered, could you close out this issue?

**Comment by vvbogdanov87** [comment]
Hello @colhom ,
How can I decrypt UserData?

**Comment by jeromegn** [comment]
I'd be interested in knowing how to update the cloud-config on an existing cluster. I think that's what his original question was.

Basically, I'm trying to add a runtime-config parameter to the apiserver pod defined in the controller cloud-config (to enable ScheduledJob on my kube 1.4.x cluster.) I was hoping updating that would handle the pod recreation accordingly.

Any thoughts?
