### ISSUE TITLE
Git repo volume fails

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#490]
Hi, 
I've configured a replication controller with a GitRepo volume type http://kubernetes.io/docs/user-guide/volumes/#gitrepo

When I create the pod, I get the following error:

    Unable to mount volumes for pod "omk-frontend-rzt00_omk-backend(0608ca5b-1cea-11e6-bd96-06f0e36b13f1)": failed to exec 'git clone https://XXXX:XXXX@bitbucket.org/myuser/myrepo.git': : executable file not found in $PATH

The image has Git installed, so I'm not sure if it's an hyperkube issue.
Can you try to clone a repo with this volume type in your Kubernetes cluster?

**Comment by colhom** [comment]
Duplicate of #327 . fix is in progress
