### ISSUE TITLE
Updating a stack via kube-aws is disabled without comment

### ISSUE THREAD

**Issue by lattwood** [coreos/coreos-kubernetes#499]
Hey, noticed the update flag is disabled but there's no comment explaining why and I'm curious.

https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/cmd/kube-aws/command_up.go#L29

**Comment by colhom** [comment]
@lattwood the biggest reason it is provides an operator means to shoot their own foot. Depending on the nature of the upgrade (what needs to be replaced), you could see your controller machine re-created and hence your etcd data wiped away. We feel it's too dangerous to have such an operation available as part of the CLI interface.

You can use `kube-aws up --export` to produce a complete stack file, and then manually update your stack using that exported file and the AWS web interface /cli tool. In the web interface case, it will show you everything that's going to happen. If you controller machine is going to be replaced-- get ready to manually dump/restore your deployment. [WIP doc on doing that](https://github.com/coreos/docs/pull/789/files)

**Comment by kalbasit** [comment]
@colhom how about using a stack update policy? The following allows anything but EC2 instance replacement.

```yaml
{
  "Statement" : [
    {
      "Effect" : "Deny",
      "Principal" : "*",
      "Action" : "Update:Replace",
      "Resource" : "*",
      "Condition" : {
        "StringEquals" : {
          "ResourceType" : ["AWS::EC2::Instance", "AWS::AutoScaling::AutoScalingGroup"]
        }
      }
    },
    {
      "Effect" : "Allow",
      "Principal" : "*",
      "Action" : "Update:*",
      "Resource" : "*"
    }
  ]
}
```

**Comment by colhom** [comment]
@kalbasit this week I am working on a discrete etcd cluster, which will make updates much easier and more flexible. Hopefully this problem will go away soon!

**Comment by kalbasit** [comment]
@colhom nice! I'll keep an eye out for that!

**Comment by aaronlevy** [comment]
I'm going to close this as it seemed the question has been answered. But please re-open if necessary.
