### ISSUE TITLE
tpm: use forward naming

### ISSUE THREAD

**Issue by philips** [coreos/coreos-kubernetes#502]
for the TPM third party resource we should use forward naming for the labels. Currently they are something like `com.coreos.tpm/foo` when the intention with the labels in k8s is that they look like schema free URLs `tpm.coreos.com/foo`.

cc @mjg59 @kans

**Comment by aaronlevy** [comment]
Where is this implemented?

**Comment by mjg59** [comment]
The version you reviewed has this implemented
