### ISSUE TITLE
kube-aws validate doesn't check stack name format

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#505]
When customizing the stack name in cluster.yaml, the `validate` command doesn't check this value, but `status` will fail:

```
$ kube-aws validate
Validating UserData...
UserData is valid.

Validating stack template...
Validation Report: {
  Capabilities: ["CAPABILITY_IAM"],
  CapabilitiesReason: "The following resource(s) require capabilities: [AWS::IAM::InstanceProfile, AWS::IAM::Role]",
  Description: "kube-aws Kubernetes cluster test-1.2.3"
}
stack template is valid.

Validation OK!
```

All valid, but:

```
$ kube-aws status
Error: Failed fetching cluster info: unable to get public IP of controller instance:
ValidationError: 1 validation error detected: Value 'test-1.2.3' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
	status code: 400, request id: abc123
```

**Comment by colhom** [comment]
@robszumski when you try to do `'kube-aws up`, does it fail immediately and give you indicative output? Or does it partially create the stack and then bail leaving a `CREATE_FAILED` status stack?

**Comment by robszumski** [comment]
@colhom I fixed the issue before trying to launch anything

**Comment by colhom** [comment]
@robszumski there has been some calculated laziness with not detecting simple errors that `kube-aws up` will error out on immediately as a result of the cloudformation create API returning an error. I would think the stack name would fall into that category.

**Comment by robszumski** [comment]
Works for me

**Comment by colhom** [comment]
Would like to say that in an ideal world, kube-aws validate would encompass any and all errors that would prevent your stack from creating, barring aws service outages. That's a little ways off right now- we're better off addressing particularly annoying/common issues as they pop up.

**Comment by robszumski** [comment]
FWIW, I just ran into this again.
