### ISSUE TITLE
Skydns gets kubelet-wrapper's container resolv.conf, not host's

### ISSUE THREAD

**Issue by chancez** [coreos/coreos-kubernetes#506]
In Kubernetes 1.2, pods only have a single nameserver in /etc/resolv.conf, which points to the kube-dns addon. https://github.com/kubernetes/kubernetes/issues/15592

This is fine, however kube-dns is expected to forward DNS queries for domains it's not authoritative over. This doesn't work perfectly today because the kube-dns pod inherits it's /etc/resolv.conf from the host, which in this case is the kubelet-wrapper container's resolv.conf, so it's getting 8.8.8.8 and 8.8.4.4 rather than the host's resolv.conf. 

This means clusters which have an internal DNS server in their network are unable to resolve internal dns names, as that nameserver is not in skydns' resolv.conf. This is the case for AWS, for example, as every EC2 instance gets it's own hostname, which Amazon resolve for us normally.

The work around is to mount in /etc/resolv.conf into kubelet-wrapper as documented here: https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md#use-the-hosts-dns-configuration 

I couldn't find any open issues for this specific problem yet, so I'm putting this here for others who run into the issue, and to track the status of this particular behavior.

**Comment by aaronlevy** [comment]
ref: https://github.com/coreos/bugs/issues/1228

**Comment by robszumski** [comment]
Closed via https://github.com/coreos/coreos-kubernetes/pull/681
