### ISSUE TITLE
Testing: Feature matrix

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-kubernetes#509]
This project has been growing lots of features lately, which is awesome!

Many of these features are modal in nature (route53 integration, mutliple subnets, etc) and have subtle interactions with each other which we do not currently test beyond unit tests.

We need a conformance testing matrix which does e2e/conformance tests repeatedly with various combinations of configuration values.

Ref #500 for why is is becoming necessary.

\cc @cgag @aaronlevy

**Comment by aaronlevy** [comment]
Given the time cost / complexity of running tests against a configuration matrix, I'd prefer to start off with:

* Set a version for deprecating legacy features (this seems to be much of the current pain)
* Create a blessed testing configuration which exercises as much of the functionality as you can in a single run.
