### ISSUE TITLE
Deprecate instanceCIDR/availabilityZone parameters

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-kubernetes#520]
#439 introduced the `subnets` list for specifying instanceCIDR and AZ for a set of subnets, superseding these parameters.

\cc @aaronlevy

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws and all active development is taking place there.

If this issue still needs to be addressed, please re-open the issue under the new repository.
