### ISSUE TITLE
Can't ping out 

### ISSUE THREAD

**Issue by rwillard** [coreos/coreos-kubernetes#526]
Setting up new cluster with kubeaws. Troubleshooting trying to figure out why I can't get a docker container to work. When I try to test network by pinging google.com or elsewhere from one of the minion nodes, I don't get any resp. Is this expected? I am pulling from docker successfully, just not getting some other services to work properly.

**Comment by cgag** [comment]
Looks like we don't have an egress rule that allows ICMP: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/stack-template.json#L344.

Seems to me we should probably allow it.  Anyone opposed? cc: @colhom @aaronlevy

**Comment by colhom** [comment]
I'm good with ICMP ingress/egress allowed by default.
