### ISSUE TITLE
Kubernetes Dashboard not working in v0.7.0

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#529]
When I create the Kubernetes Dashboard I get:

    kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

    kubectl describe pod/kubernetes-dashboard-b3fno --namespace=kube-system

    pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0-beta2"
    Successfully pulled image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0-beta2"
    Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kubernetes-dashboard     pod=kubernetes-dashboard-b3fno_kube-system(bbb465f0-2bd4-11e6-afe5-06c3038ee649)"
    
    Created Created container with docker id 649fe85c2dfe
    Started Started container with docker id 649fe85c2dfe
    BackOff Back-off restarting failed docker container    

No logs are showed in the pod.

**Comment by n1kt0** [comment]
HI, did you resolve it?

**Comment by arkkanoid** [comment]
Yes, I'd a problem with the dns resolution

**Comment by n1kt0** [comment]
same here!

**Comment by arkkanoid** [comment]
You should check the logs in each container of kube-dns pod.

**Comment by wutongjie23hao** [comment]
Hi, can you tell me the location of logs?

**Comment by arkkanoid** [comment]
kubectl get pods --namespace=kube-system
Check if one container is not ready in the kube-dns pod: etcd, kube2sky, skydns or healthz.
To check logs:
kubectl logs kube-dns-v11-y91ps -c etcd --namespace=kube-system

**Comment by jasonhubs** [comment]
I get the save error and how can I resolve it?

-  kubectl get pods --namespace=kube-system -o wide 
``` bash
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   1/1       Running   8          18m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   1/1       Running   8          18m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   1/1       Running   8          18m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   0/1       Error     8          18m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS    RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   0/1       Error     8          18m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   0/1       CrashLoopBackOff   8          18m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   0/1       CrashLoopBackOff   8          18m       100.10.67.2   1.1.1.232
```

- kubectl get events --namespace=kube-system -o wide

``` bash 
22m       22m       1         kubernetes-dashboard-2734510724-4x2n4   Pod       spec.containers{kubernetes-dashboard}   Normal    Created      {kubelet 1.1.1.232}   Created container with docker id 507d2b096b75
22m       22m       1         kubernetes-dashboard-2734510724-4x2n4   Pod       spec.containers{kubernetes-dashboard}   Normal    Started      {kubelet 1.1.1.232}   Started container with docker id 507d2b096b75
20m       22m       9         kubernetes-dashboard-2734510724-4x2n4   Pod                                               Warning   FailedSync   {kubelet 1.1.1.232}   Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-2734510724-4x2n4_kube-system(d8557081-a4f4-11e6-a058-fa163e6b76a6)"

20m       20m       1         kubernetes-dashboard-2734510724-4x2n4   Pod       spec.containers{kubernetes-dashboard}   Normal    Created      {kubelet 1.1.1.232}   Created container with docker id 4fc0f6abeeb5
20m       20m       1         kubernetes-dashboard-2734510724-4x2n4   Pod       spec.containers{kubernetes-dashboard}   Normal    Started      {kubelet 1.1.1.232}   Started container with docker id 4fc0f6abeeb5
17m       20m       14        kubernetes-dashboard-2734510724-4x2n4   Pod                                               Warning   FailedSync   {kubelet 1.1.1.232}   Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-2734510724-4x2n4_kube-system(d8557081-a4f4-11e6-a058-fa163e6b76a6)"

19m       19m       1         kubernetes-dashboard-2734510724-4x2n4   Pod                                               Normal    Scheduled    {default-scheduler }   Successfully assigned kubernetes-dashboard-2734510724-4x2n4 to 1.1.1.232
17m       17m       1         kubernetes-dashboard-2734510724-4x2n4   Pod       spec.containers{kubernetes-dashboard}   Normal    Created      {kubelet 1.1.1.232}    Created container with docker id 390b53860866
17m       17m       1         kubernetes-dashboard-2734510724-4x2n4   Pod       spec.containers{kubernetes-dashboard}   Normal    Started      {kubelet 1.1.1.232}    Started container with docker id 390b53860866
5m        17m       54        kubernetes-dashboard-2734510724-4x2n4   Pod                                               Warning   FailedSync   {kubelet 1.1.1.232}    Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-2734510724-4x2n4_kube-system(d8557081-a4f4-11e6-a058-fa163e6b76a6)"

12m       12m       1         kubernetes-dashboard-2734510724-4x2n4   Pod          spec.containers{kubernetes-dashboard}   Normal    Created             {kubelet 1.1.1.232}        Created container with docker id 9847b1cf699d
12m       12m       1         kubernetes-dashboard-2734510724-4x2n4   Pod          spec.containers{kubernetes-dashboard}   Normal    Started             {kubelet 1.1.1.232}        Started container with docker id 9847b1cf699d
6m        6m        1         kubernetes-dashboard-2734510724-4x2n4   Pod          spec.containers{kubernetes-dashboard}   Normal    Created             {kubelet 1.1.1.232}        Created container with docker id 58d50de652e4
6m        6m        1         kubernetes-dashboard-2734510724-4x2n4   Pod          spec.containers{kubernetes-dashboard}   Normal    Started             {kubelet 1.1.1.232}        Started container with docker id 58d50de652e4
19m       19m       1         kubernetes-dashboard-2734510724         ReplicaSet                                           Normal    SuccessfulCreate    {replicaset-controller }   Created pod: kubernetes-dashboard-2734510724-4x2n4
19m       19m       1         kubernetes-dashboard                    Deployment                                           Normal    ScalingReplicaSet   {deployment-controller }   Scaled up replica set kubernetes-dashboard-2734510724 to 1
```
- ping the pod ip
``` bash
[root@jason-kube1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                    READY     STATUS             RESTARTS   AGE       IP            NODE
kubernetes-dashboard-2734510724-4x2n4   0/1       CrashLoopBackOff   8          23m       100.10.67.2   1.1.1.232
[root@jason-kube1 ~]# ping 100.10.67.2
PING 100.10.67.2 (100.10.67.2) 56(84) bytes of data.
64 bytes from 100.10.67.2: icmp_seq=1 ttl=61 time=2.36 ms
64 bytes from 100.10.67.2: icmp_seq=2 ttl=61 time=0.770 ms
64 bytes from 100.10.67.2: icmp_seq=3 ttl=61 time=0.914 ms
64 bytes from 100.10.67.2: icmp_seq=4 ttl=61 time=0.719 ms
```

**Comment by MichaelTSS** [comment]
I believe I have the same issue as @jasonhubs. The `kubernetes-dashboard` keeps restarting logging the same event:
```Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff:```

After a couple minutes though, it successfully starts the pod and the interface is available again.

`$ kubectl get pods --namespace=kube-system -o wide
NAME                                                                  READY     STATUS             RESTARTS   AGE       IP             NODE
elasticsearch-logging-v1-3xu4d                                        1/1       Running            9          21d       10.244.0.20    ip-172-20-0-214.eu-central-1.compute.internal
elasticsearch-logging-v1-ke89f                                        1/1       Running            7          21d       10.244.0.16    ip-172-20-0-214.eu-central-1.compute.internal
fluentd-elasticsearch-ip-172-20-0-214.eu-central-1.compute.internal   1/1       Running            3          21d       10.244.0.21    ip-172-20-0-214.eu-central-1.compute.internal
fluentd-elasticsearch-ip-172-20-0-215.eu-central-1.compute.internal   1/1       Running            0          21d       10.244.1.2     ip-172-20-0-215.eu-central-1.compute.internal
heapster-v1.2.0-3305922223-1694q                                      4/4       Running            0          21d       10.244.1.3     ip-172-20-0-215.eu-central-1.compute.internal
kibana-logging-v1-ah854                                               1/1       Running            17         21d       10.244.0.17    ip-172-20-0-214.eu-central-1.compute.internal
kube-dns-v19-vw22o                                                    3/3       Running            11         21d       10.244.0.28    ip-172-20-0-214.eu-central-1.compute.internal
kube-proxy-ip-172-20-0-214.eu-central-1.compute.internal              1/1       Running            3          21d       172.20.0.214   ip-172-20-0-214.eu-central-1.compute.internal
kube-proxy-ip-172-20-0-215.eu-central-1.compute.internal              1/1       Running            0          21d       172.20.0.215   ip-172-20-0-215.eu-central-1.compute.internal
kubernetes-dashboard-v1.4.0-6a658                                     1/1       Running            44         21d       10.244.0.19    ip-172-20-0-214.eu-central-1.compute.internal
monitoring-influxdb-grafana-v4-fcmkl                                  1/2       CrashLoopBackOff   208        21d       10.244.0.18    ip-172-20-0-214.eu-central-1.compute.internal`
