### ISSUE TITLE
kube-aws validation error message should be more specific on which userdata file is invalid

### ISSUE THREAD

**Issue by mcalhoun** [coreos/coreos-kubernetes#530]
kube-aws validate  
Validating UserData...
Error: cloud-config validation errors:
UserDataWorker: line 198: error: mapping values are not allowed in this context
UserDataWorker: line 0: warning: incorrect type for "" (want struct)

The error message doesn't indicate if it's line 198 in cloud-config-controller or cloud-config-worker

**Comment by cgag** [comment]
Currently the mapping is UserDataWorker => cloud-config-worker, UserDataController => cloud-config-controller. 

Maybe it should say `cloud-config-worker` instead of `UserDataWorker`?

**Comment by mcalhoun** [comment]
Ahh...I didn't pick up on that...I shouldn't have missed that...sorry! It would definitely idiot-proof it by specifying the filename instead of the UserData{Worker,Controller}.

**Comment by colhom** [comment]
@mcalhoun agree completely. Nothing like inconsistent verbage to send the brain into a tailspin.
