### ISSUE TITLE
Option to not assign public IPs for worker nodes

### ISSUE THREAD

**Issue by whereisaaron** [coreos/coreos-kubernetes#535]
Is it necessary for worker nodes get assigned public IPs? All the subnets created by kube-aws 0.7.1 are currently set to automatically assign public IP address to new instances (MapPublicIpOnLaunch = true). If this is a preference rather than a requirement, could this be a `cluster.yaml` option which changes the flag in `stack-template.json` ?

The controller needs a public/accessible IP of course, and it has the option to assign an EIP one, so no problem there.

```
...
    "{{$subnetLogicalName}}": {
      "Properties": {
        "AvailabilityZone": "{{$subnet.AvailabilityZone}}",
        "CidrBlock": "{{$subnet.InstanceCIDR}}",
        "MapPublicIpOnLaunch": true,
        "Tags": [
          {
            "Key": "KubernetesCluster",  
            "Value": "{{$.ClusterName}}"
          }
        ],
        "VpcId": {{$.VPCRef}}
      },
...
```

**Comment by whereisaaron** [comment]
It seems there is some dependency of public IPs for workers? I tried creating a cluster with `"MapPublicIpOnLaunch": false` and the controller and API started, but the workers never registered with the controller. `get nodes` returned an empty list, even 20 minutes after the cluster was created. (this list no longer includes the controller node with 1.2.4).

I destroyed the cluster, flipped `MapPublicIpOnLaunch` to true and created the cluster again. It worked fine and the nodes registered with the controller.

Tested using kube-aws 0.7.1.

Shouldn't the controller(s) and workers only (ideally) need the VPC subnet to communicate?

**Comment by colhom** [comment]
@whereisaaron all nodes get a public ip by default because it's unfortunately still sometimes necessary to ssh into Kubernetes nodes, and most of our users at this stage are probably not using a VPN.

I would love to see a PR that makes this behavior configurable, and would entertain discussion on making no-public-worker-ip the default.

**Comment by dgarbus** [comment]
@whereisaaron: I just spun up a new cluster (0.7.1) with `"MapPublicIpOnLaunch": false` and confirmed that `kubctl get nodes` returned the number of nodes that I expected. I think this is actually working properly, although I would also like to see a configuration item in cluster.yaml for this.

**Comment by whereisaaron** [comment]
Thanks for trying to replicate @dgarbus. Maybe something else went wrong for me. I'll definitely try again and if it works maybe we can put together a patch to add public IPs for workers as configurable option.

Hi @colhom I can see why people might like this as an option, but it seems like the wrong default. People without VPN can also just ssh to the controller EIP and ssh-agent their way to the nodes from there.

The public IP address option could also be good for people who'd like to use external-to-AWS CDN/load-balancers directly across their node ports rather than use AWS ELB, e.g. to avoid the ELB spin-up / priming issues and region limitations.

**Comment by gmcquillan** [comment]
@whereisaaron I also followed this path, and it continues to be a problem on v0.8.0.
