### ISSUE TITLE
Add validate check that specified route table includes default route and/or Internet gateway

### ISSUE THREAD

**Issue by whereisaaron** [coreos/coreos-kubernetes#536]
If the user specifies a route table in `cluster.yaml` and is, ahem, an idiot, they may not have included a default route that provides Internet access, e.g. an AWS Internet Gateway or some form or NAT/proxy instance. In this case `kube-aws validate` and `kube-aws up` will succeed, but the cluster will not init correctly. "Tested" using kube-aws 0.7.1.

A possible extra validation check would be to raise an error if a custom route table is specified and that table has no default route (`0.0.0.0/0`) entry.

A possible extra validation check would be to raise a warning if the route table specified contains a default root that is not an AWS Internet Gateway. The warning would just be to remind the user that the default route must provide Internet access.

**Comment by colhom** [comment]
@whereisaaron are you envisioning a non-fatal warning? I can imagine multiple plausible scenarios where either:

* igw is not the default route
* igw is not associated at all with route table 

The question is: are we being overly annoying for the "average" user? I would think most users want an igw attached to their route table in some fashion, maybe we can even assume as the catch-all route?

**Comment by whereisaaron** [comment]
@colhom I imagined no igw in the routing table as only a warning, as there are plenty of no-igw ways to make a routing table work for kube-aws. Just "I notice you have no igw in your subnet, please make sure your nodes have some other way to get to the Internet".

I did imagine no default route at all as being a fatal error, as I didn't see any sensible configurations where this would work. However, as it only affects 'kube-aws validate' output, whether it is an error or warning is probably not worth debate, just a warning is fine.

These warnings and/or error are only going to happen for some people, those who
a) Opt to specify their own routing table, and
b) Run the optional 'kube-aws validate'
A warning/tip like this from a validate function doesn't sound too annoying?
