### ISSUE TITLE
Option to assign to default security group for VPC

### ISSUE THREAD

**Issue by rwillard** [coreos/coreos-kubernetes#537]
I've been modifying the security groups on the nodes to allow for traffic from other security groups in the same VPC. Is there a reason why the nodes aren't in the default security group, and if not should there be an option in the cluster.yaml to allow for it to be?

**Comment by whereisaaron** [comment]
At the moment this is something you can do by modifying the 'stack-template.json' file after `kube-aws render`, you can either modify the security group that will be created, or you can add your own security group identifiers to the list.

I agree it would be great if we could specify one or more security groups in 'cluster.yaml' and have those copied into the list into the list in 'stack-template.json'.

Ideally there would be an option for workers and another for the controller, e.g.

```
workerSecurityGroupsIds:
  - sg-12345678
  - sg-12345ddd

controllerSecurityGroupsIds:
  - sg-12345678
  - sg-56789abc
```
And the Id's would just get slotted into the existing 'stack-template.json' list, e.g.
```
    "LaunchConfigurationWorker": {

      "Properties": {
        ...
        "SecurityGroups": [
          {
            "Ref": "SecurityGroupWorker"
          },
          "sg-12345678",
          "sg-12345ddd"
        ],
        ...
      },
      "Type": "AWS::AutoScaling::LaunchConfiguration"
    },
```

(I am not clear if we can use security group names or only security group Id's here. The CloudFormation [documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-securitygroups) says "If your instances are launched within VPC, specify Amazon VPC security group IDs." and the [Security Group 'Ref' function](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#d0e45500) says it returns an Id "for EC2-VPC security groups that are not in a default VPC". So maybe we can only use Id's.)

**Comment by colhom** [comment]
@whereisaaron would love to see a PR for this.
