### ISSUE TITLE
SetupNetwork Error - Failed to setup network for pod

### ISSUE THREAD

**Issue by Immanuel-Daniel** [coreos/coreos-kubernetes#556]
I have deployed a multi-cluster, but when I create a pod for a service using kubectl, I have the below error. Kindly help me resolve this,

Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  25m           25m             1       {default-scheduler }                    Normal          Scheduled       Successfully assigned mongo-controller-5n2yp to 172.17.4.201
  25m           1m              138     {kubelet 172.17.4.201}                  Warning         FailedSync      Error syncing pod, skipping: failed to "SetupNetwork" for "mongo-controller-5n2yp_default" with SetupNetworkError: "Failed to setup network for pod \"mongo-controller-5n2yp_default(6b3a1d6f-3c40-11e6-8cea-080027ad62c7)\" using network plugins \"cni\": could not find \".\" plugin; Skipping pod"

**Comment by aaronlevy** [comment]
@Immanuel-Daniel are you enabling calico on via the `USE_CALICO=true` flag?

**Comment by Immanuel-Daniel** [comment]
@aaronlevy yes, they have been set to true. And the Calico-node is enabled and running on them.

**Comment by aaronlevy** [comment]
Did you update the `K8S_VER=` env var to use an image which contains the calico binaries? This would be `v1.2.4_coreos.cni.1` for the latest release (note the `.cni.` portion of the version).

Also just to note, in the upcoming 1.3 release the binaries will all be in the same image.

**Comment by Immanuel-Daniel** [comment]
@aaronlevy Thanks a lot!! I had missed the .cni. portion as you mentioned.

Fixing it, runs my containers without any trouble.

**Comment by abh** [comment]
Are the calico binaries in the 1.4 images?

I'm getting about the same error using the 1.4 beta image.

```
  12m  	1s     	506    	{kubelet core9.ntp}    		Warning	FailedSync     	Error syncing pod, skipping: failed to "SetupNetwork" for "kubernetes-dashboard-3781782280-w9tud_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kubernetes-dashboard-3781782280-w9tud_kube-system(9a70e512-7675-11e6-b059-525400cddd82)\" using network plugins \"cni\": failed to find plugin \"calico\" in path [/opt/cni/bin /opt/flannel/bin]; Skipping pod"
```

I'm starting the kubelet-wrapper with

```
  --network-plugin-dir=/etc/kubernetes/cni/net.d \
  --network-plugin=cni \
```

**Comment by aaronlevy** [comment]
@abh We will be releasing new beta images which contain the calico binaries in the next couple hours (likely v1.4.0-beta.3)

**Comment by garo** [comment]
Just in case somebody wonders this issue with v1.4.0_coreos.0 image: this image is broken and doesn't contain the calico binary. Use instead v1.4.0_coreos.1

**Comment by ElijahCaine** [comment]
For anybody who found this (like I did) there are two ways to apply the above advice:

1. Bump the `K8S_VER` variable in `multi-node/generic/controller-install.sh` and `multi-node/generic/worker-install.sh` from `v1.4.0_coreos.0` (or lower) to `v1.4.0_coreos.1`.
2. Update your local copy of the repo! It's fixed on master.

*Sincerely,*
*\- Someone else who forgets to pull updates regularly*
