### ISSUE TITLE
docs: add explanation about kubelet failure to register on master nodes

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#56]
On a master node, the kubelet will attempt to post status to the API over and over again.

We should add a note that this isn't an issue and also explain why this happens.

**Comment by jerrykan** [comment]
Is there any way to suppress these messages (ie. stop the kubelet process from trying to update the node status), or are logging these errors actually desirable?

**Comment by aaronlevy** [comment]
There is an upstream proposal for better handling this workflow (https://github.com/kubernetes/kubernetes/issues/14140#issuecomment-142126864).

Essentially, we still want the node to register itself with the api, but only want it running static pods and not accepting work from api-server.

Until then, I don't believe there is a good way of specifically suppressing these messages.

**Comment by jerrykan** [comment]
OK, thanks for the info.

**Comment by joshix** [comment]
Closed by https://github.com/coreos/coreos-kubernetes/pull/128

**Comment by joshix** [comment]
Closed by https://github.com/coreos/coreos-kubernetes/pull/128
