### ISSUE TITLE
document incompatibility of AWS EBS with availability zones

### ISSUE THREAD

**Issue by Thermus** [coreos/coreos-kubernetes#560]
Please document the incompatibility of AWS EBS with using several availability zones.
kubernetes currently does not take into account in what AZ an EBS is, when it schedules a pod that uses a EBS volume on a node. That prevents the use of EBS with multiple AZs. This just caused a major problem for me, forcing me to `destroy` the cluster and `up` it with a cluster configuration that does not use multiple AZs.

**Comment by cgag** [comment]
I was under the impression kubernetes did respect which AZ an EBS is in.  I remember reading about it in   @colhom should confirm if we were wrong about what parts of ubernetes/federation-lite made it in to 1.2 or if this is a bug.

**Comment by Thermus** [comment]
I tested it and it didn't work. I used the latest coreos-kubernetes release on AWS on CoreOS stable.

**Comment by colhom** [comment]
@Thermus the [upstream guide](http://kubernetes.io/docs/admin/multiple-zones/#limitations) for multi-zone explains that volume affinity only works for `PersistentVolumeClaims`.

@robszumski we should probably add this little factoid in `cluster.yaml`. It's counter-intuitive but very useful to know.

**Comment by robszumski** [comment]
@colhom or @Thermus would you be able to take a quick swing at a PR for this to get the basics down, and then someone can some back and flesh out the writing?
