### ISSUE TITLE
Hyperkube: Calico appears to be shipped incorrectly in quay.io/coreos/hyperkube:v1.3.0

### ISSUE THREAD

**Issue by andrewhowdencom** [coreos/coreos-kubernetes#562]
Possibly related: https://github.com/coreos/coreos-kubernetes/issues/552

In the v1.2.4.cni version of Kuberkube, the CNI binaries including calico are shipped as part of the hyperkube container. However, in 1.3.0 the calico binary seems to be missing.

v1.2.4
<details>
```
$ docker run quay.io/coreos/hyperkube:v1.2.4_coreos.cni.1 ls /opt/cni/bin/
bridge
calico
cnitool
dhcp
flannel
host-local
host-local-ptp
ipvlan
loopback
macvlan
ptp
tuning
```
</details>

v1.3.0

<details>
```
$docker run quay.io/coreos/hyperkube:v1.3.0_coreos.0 ls /opt/cni/bin
bridge
cnitool
dhcp
flannel
host-local
ipvlan
loopback
macvlan
ptp
tuning
```
</details>

There does seem to be a binary file at /opt/cni/calico, but it's not executable, and it's not in the Kubelet path.

<details>
```
docker run quay.io/coreos/hyperkube:v1.3.0_coreos.0 stat /opt/cni/calico
  File: '/opt/cni/calico'
  Size: 8858402   	Blocks: 17304      IO Block: 4096   regular file
Device: 32h/50d	Inode: 44          Links: 1
Access: (0664/-rw-rw-r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-07-02 07:39:38.000000000 +0000
Modify: 2016-07-02 07:39:38.000000000 +0000
Change: 2016-07-05 05:45:30.950161524 +0000
 Birth: -
```
</details>

Edited.

**Comment by pbx0** [comment]
I'll try to fix this and release a `v1.3.0_coreos.1` image later today or tomorrow. As of the v1.3.0 releases we should just be shipping the Calico binaries by default so you are right to compare it to the v1.2.4 cni image.

**Comment by pbx0** [comment]
`v1.3.0_coreos.1` hyperkube image is out. This should be fixed now, let us know if you have further problems.

**Comment by robszumski** [comment]
Can we update the docs with this image? Or are we not at that point yet?

**Comment by andrewhowdencom** [comment]
Will update this when we've got a cluster up indicating success or failure. 

Re. Docs, if you're referring to the "bare metal installation of Kubernetes on CoreOS", that's the guide we followed and we ran into the following issue with k8s on GCE:

https://github.com/kubernetes/kubernetes/issues/27347#issuecomment-226484155

Might be worth making a note about.

**Comment by robszumski** [comment]
For context, we normally bump those versions when we do a release. I guess @pbx0 can consider this a friendly bump for that :) But I'm not sure if all of the testing is done.

@andrewhowdencom Thanks for keeping us updated

**Comment by andrewhowdencom** [comment]
I forgot to update this! Seemed fine with initial testing (provisioning on GCE, adding some resources with persistent disks). Gone elsewhere internally for review now. Thanks for your awesome work!
