### ISSUE TITLE
kube-aws: useCalico cluster.yml setting ignored – Calico always active

### ISSUE THREAD

**Issue by felixbuenemann** [coreos/coreos-kubernetes#564]
The controller and worker userdata has several services that use `enable: {{.UseCalico}}`.

However both setting `useCalico: false` and leaving it commented out in `cluster.yml` have no effect and the services get installed and are running:

```
core@ip-10-0-0-50 ~ $ systemctl status calico-node.service
● calico-node.service - Calico per-host agent
   Loaded: loaded (/etc/systemd/system/calico-node.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-07-06 08:03:38 UTC; 9min ago
 Main PID: 1554 (runsvdir)
    Tasks: 8
   CGroup: /machine.slice/calico-node.service
           ├─1554 /sbin/runsvdir -P /etc/service
           ├─5811 runsv felix
           ├─5812 /usr/bin/python /usr/bin/calico-felix
           └─5847 /usr/bin/python -m calico.etcddriver /run/felix-driver.sck
```

Tested with kube-aws 1.2.4 and both v1.2.4_coreos.1 and v1.3.0_coreos.1 images.

**Comment by pbx0** [comment]
This should be fixed in https://github.com/coreos/coreos-kubernetes/pull/555 I believe. We also found that setting `useCalico: false` wasn't being respected.

**Comment by felixbuenemann** [comment]
Yes, that's what I meant. The relevant commit seems to be e1212f2.

**Comment by aaronlevy** [comment]
closed in: https://github.com/coreos/coreos-kubernetes/pull/555

**Comment by felixbuenemann** [comment]
Thanks, Aaron!
