### ISSUE TITLE
AWS spot instance termination notification marks node as unschedulable and starts draining it

### ISSUE THREAD

**Issue by mgilbir** [coreos/coreos-kubernetes#565]
I couldn't find anywhere if this is already implemented, if so, feel free to disregard this and close the issue directly.

It would be great if nodes that are running on spot instances are marked as unschedulable and drained upon a spot instance termination notification. The way to retrieve these notifications is described in [this blog post](https://aws.amazon.com/blogs/aws/new-ec2-spot-instance-termination-notices/).

The gist of it consists in having a process polling every 5s the URL `http://169.254.169.254/latest/meta-data/spot/termination-time` and, when it shows a time in the future, take actions to drain the k8s node. 

You only get a 2 minutes heads up but it may allow for a clean shutdown of pods before the instance is terminated.

**Comment by pieterlange** [comment]
That would be great indeed, but i can imagine it's not that high up on the feature list yet.

First of all you'd want to prevent pods with a `terminationGracePeriodSeconds` value over 120 - (poll interval) - (some extra slack?) from being scheduled on spot instances. I guess the primitives are already there but you'd have to write your own scheduler & polling daemonset. :)

**Comment by mumoshu** [comment]
@mgilbir @pieterlange Thanks for the inspiration!

I've implemented it with simple shell-scripting. Rough around the edges but it seems to work. 

https://github.com/mumoshu/kube-spot-termination-notice-handler

Just run `kubectl create -f spot-termination-notice-handler.daemonset.yaml` and it should work.

**Comment by pieterlange** [comment]
That's really cool! I like the simple implementation. And now that i think about it, i think one could currently set a node selector for pods that have a large `terminationGracePeriodSeconds` so they don't get scheduled on spot instances. Nice work :)

**Comment by iameli** [comment]
@mumoshu Wow, love that!

Stream Kitchen is going to need this feature too, but I'm not necessarily sure this repo is the right place for it? It seems like everyone that's using AWS Spot Instances for Kubernetes is going to run that kube-spot-termination-notice-handler or something similar to it as a cluster addon, irrespective of how the Kubernetes cluster got there.
