### ISSUE TITLE
Kubelet doesn't restart when one dependency is rebooted

### ISSUE THREAD

**Issue by arkkanoid** [coreos/coreos-kubernetes#567]
Hi, 
I've a node that is in 'not ready' status. Accessing in the node I can see that the kubelet.service is loaded but not running. 
Looking the logs I see that flanneld has rebooted, so Docker.service (has a dependency with Flanneld) also has rebooted. Booth services now are active and running.
However, the kubelet service (has a dependency with Docker) is in loaded status. Why it is not running after reboot?

**Comment by pbx0** [comment]
Are you using kube-aws? If so, I believe this same issue has come up: https://github.com/coreos/coreos-kubernetes/issues/545 and been fixed in master.

If this isn't the right fix for you could you paste the output from `systemctl cat kubelet` on the node whose kubelet isn't running?

**Comment by arkkanoid** [comment]
Yes, it seems the same issue. I will check it in the next version.

Thanks
