### ISSUE TITLE
quay.io/coreos/hyperkube image for v1.2.5

### ISSUE THREAD

**Issue by felixbuenemann** [coreos/coreos-kubernetes#570]
Please consider releasing a hyperkube image vor k8s 1.2.5, kubernetes v1.3.0 still has quite some issues preventing an upgrade from 1.2.4.

**Comment by danielfm** [comment]
@felixbuenemann I'm also considering upgrading from Kubernetes 1.2.4 to 1.3 in the short term, but I'm not aware of upgrading issues. Can you elaborate? Which specifically are the issues you're referring to?

**Comment by felixbuenemann** [comment]
@danielfm Issues with mounting secret volumes on k8s 1.3.0, see kubernetes/kubernetes#28750 and the related kubernetes/kubernetes#28616.

**Comment by aaronlevy** [comment]
Just a heads up that a `v1.2.6` image is currently being built and should be available at `quay.io/coreos/hyperkube:v1.2.6_coreos.0` in about an hour or so (assuming tests/build are successful)

**Comment by felixbuenemann** [comment]
Thanks, successfully updated to the new version.

**Comment by danielfm** [comment]
@aaronlevy what happened with the `.cni.X` images? There's no CNI images since 1.2.4 release.

**Comment by aaronlevy** [comment]
@danielfm we started including the CNI binaries in the main image. So you should be good to use versions greater than v1.2.6 (for v1.2.x series) and v1.3.x

**Comment by aaronlevy** [comment]
Also updated release notes to make this a little more clear: https://github.com/coreos/kubernetes/releases/tag/v1.2.6%2Bcoreos.0
