### ISSUE TITLE
indication of slow startup?

### ISSUE THREAD

**Issue by bfallik** [coreos/coreos-kubernetes#571]
Hi,

While testing single-node startup on a fresh VM over conference wifi it took tens of minutes for the docker containers running kubernetes to start. Presumably it just took a very long time for Docker to download the hyperkube image.

During this time it wasn't obvious at all what was going on in the system. journald captured lots of error messages about failed API requests but I didn't see any logging about the state. Docker wasn't helpful either since there didn't seem like a good way to track the download.

Could we add some logging to kubelet (or elsewhere) so that it's obvious when the kubelet is downloading the docker images?

brian

**Comment by robszumski** [comment]
@bfallik Which guide were you following?

> Could we add some logging to kubelet (or elsewhere) so that it's obvious when the kubelet is downloading the docker images?

This would have to be pursued upstream, as we don't own the kubelet software.

**Comment by robszumski** [comment]
The AWS guide has [just been updated](https://github.com/coreos/coreos-kubernetes/pull/558) with this copy, after the `up` step:

> NOTE: It can take some time after `kube-aws up` completes before the cluster is available. When the cluster is first being launched, it must download all container images for the cluster components (Kubernetes, dns, heapster, etc). Depending on the speed of your connection, it can take a few minutes before the Kubernetes api-server is available.

Does this satisfy your concerns?

**Comment by bfallik** [comment]
@robszumski Sortof. I read that text and expected to wait. Since I new the wifi was slow I logged into the box to try and follow the process. It was completely obvious when the kubelet-wrapper was downloading hyperkube from the log:
```
Jul 13 16:21:15 localhost kubelet-wrapper[1611]: image: downloading signature from https://quay.io/c1/aci/quay.io/coreos/hyperkube/v1.3.0_coreos.1/aci.asc/linux/amd64/
Jul 13 16:21:15 localhost kubelet-wrapper[1611]: Downloading signature:  0 B/473 B
Jul 13 16:21:15 localhost kubelet-wrapper[1611]: Downloading signature:  473 B/473 B
Jul 13 16:21:16 localhost kubelet-wrapper[1611]: Downloading ACI:  0 B/161 MB
Jul 13 16:21:16 localhost kubelet-wrapper[1611]: Downloading ACI:  16.4 KB/161 MB
Jul 13 16:21:17 localhost kubelet-wrapper[1611]: Downloading ACI:  120 KB/161 MB
Jul 13 16:21:18 localhost kubelet-wrapper[1611]: Downloading ACI:  225 KB/161 MB
Jul 13 16:21:19 localhost kubelet-wrapper[1611]: Downloading ACI:  486 KB/161 MB
...
```

but once this step was complete there was nothing to indicate that now the kubelet had started a second `docker pull` for its hyperkube image. The log just showed a bunch of API errors.

Since the first image download took so long I thought I was already passed the long wait phase. And since kubernetes wasn't running and the log contained a bunch of errors I thought that something was broken.

**Comment by robszumski** [comment]
Totally understand, I'm glad that at least the wrapper script was clear.

I'm going to close this as it's not directly actionable for this repo, but we have some changes coming up to the provisioning process, based on the CoreOS work on "self-hosted" Kubernetes: https://docs.google.com/document/d/1VNp4CMjPPHevh2_JQGMl-hpz9JSLq3s7HlI87CTjl-8/edit

**Comment by bfallik** [comment]
Cool, no problem. Maybe this ticket will provide a clue for someone else in case they hit it too.
