### ISSUE TITLE
cni plugin + flannel on v1.3: pods can't route to service IPs

### ISSUE THREAD

**Issue by pbx0** [coreos/coreos-kubernetes#572]
If you set the kubelet network plugin to `cni` and use the following cni config:
```
{
    "name": "flnet",
    "type": "flannel",
    "delegate": {
        "isDefaultGateway": true
    }
}
```
Then any pod created without host networking will not be able to access service IPs. No route to host errors will occur despite a default gateway existing. The kube-dns pod will be unable to contact the API server and the dashboard will crashloop as a result.

Trying to contact api server from dns pod over service IP:
```
$ ./kubectl --kubeconfig=./kubeconfig --namespace=kube-system exec kube-dns-v15-gm61j -- wget http:\/\/10.3.0.1:443\/version
Connecting to 10.3.0.1:443 (10.3.0.1:443)
wget: can't connect to remote host (10.3.0.1): No route to host
error: error executing remote command: error executing command in container: exit status 1
```

DNS pod's routes:
```
default via 10.2.37.1 dev eth0
10.2.0.0/16 via 10.2.37.1 dev eth0
10.2.37.0/24 dev eth0  src 10.2.37.56
```

Notably, the DNS pod can contact the apiserver over the pod network. Additionally you can ping service IPs from the host itself but not from within a pod.

Another path that needs more exploring is that after briefly checking it appears that when the cni is used with calico this problem doesn't occur. Is the calico plugin essentially doing something right that the bridge plugin is not in this case? Or is the bridge plugin still just called by calico anyway?

This issue is currently blocking https://github.com/coreos/coreos-kubernetes/issues/501. The issue occurs regardless of the container runtime set. Docker and flannel will work if you don't set the network plugin to `cni` and let it configure flannel directly. 

I've been testing and debugging this on a single-node cluster with help from @steveeJ. Additionally, anyone testing this should make sure their v1.3 hyperkube image has updated to the latest CNI. Try this branch: https://github.com/pbx0/kubernetes/commits/coreos-v1.3.0-cni-lo or this image: quay.io/peanutbutter/hyperkube:v1.3.0_cni.latest

**Comment by Quentin-M** [comment]
Hi,

From kubelet.service:
```
Environment="KUBELET_ACI=quay.io/peanutbutter/hyperkube"
Environment="KUBELET_VERSION=v1.3.0_cni.latest"
Environment="RKT_OPTS=--volume dns,kind=host,source=/etc/resolv.conf --mount volume=dns,target=/etc/resolv.conf --volume rktbin,kind=host,source=/share/bin/rkt --mount volume=rktbin,target=/usr/bin/rkt --volume var-lib-rkt,kind=host,source=/var/lib/rkt --mount volume=var-lib-rkt,target=/var/lib/rkt --volume=stage,kind=host,source=/usr/lib/rkt --mount volume=stage,target=/usr/lib/rkt --volume=mp,kind=host,source=/usr/sbin/modprobe --mount volume=mp,target=/usr/bin/modprobe --volume share,kind=host,source=/share --mount volume=share,target=/share"

ExecStart=/share/bin/kubelet-wrapper \
  --rkt-path=/share/bin/rkt \
  --rkt-stage1-image=coreos.com/rkt/stage1-coreos:1.10.0 \
  --container-runtime=rkt \
  --v=6 \
  --network-plugin=cni \
  --network-plugin-dir=/etc/kubernetes/cni/net.d \
  --reconcile-cidr=true \
  --pod-cidr=10.2.0.0/16 \
  --api-servers=https://100.127.0.201 \
  --hostname-override=100.127.0.205 \
  --register-node=true \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --cluster-dns=10.3.0.10 \
  --cluster-domain=cluster.local \
  --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
```

On the kubelet's host:
```
$ cat /etc/kubernetes/cni/net.d/flannel.conf
{
   "name": "rkt.kubernetes.io",
   "type": "flannel",
   "delegate": {
       "isDefaultGateway": true
   }
}
```

From within a rkt pod that do not use --net=host, to another pod, using DNS resolution and its service IP:
```
$ ip r
default via 10.2.72.1 dev eth0
10.2.0.0/16 via 10.2.72.1 dev eth0
10.2.72.0/24 dev eth0  proto kernel  scope link  src 10.2.72.81

$ curl -vv http://keystone-api:5000
* About to connect() to keystone-api port 5000 (#0)
*   Trying 10.3.0.75...
* Connected to keystone-api (10.3.0.75) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: keystone-api:5000
> Accept: */*
>
< HTTP/1.1 300 Multiple Choices
< Date: Wed, 13 Jul 2016 23:34:36 GMT
< Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5
< Vary: X-Auth-Token
< Content-Length: 593
< Content-Type: application/json
<
* Connection #0 to host keystone-api left intact
{"versions": {"values": [{"status": "stable", "updated": "2015-09-15T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}], "id": "v3.5", "links": [{"href": "http://keystone-api:5000/v3/", "rel": "self"}]}, {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "http://keystone-api:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}]}}
```

Description of the service:
```
kubectl describe service keystone-api
Name:			keystone-api
Namespace:		default
Labels:			<none>
Selector:		app=keystone-api
Type:			ClusterIP
IP:			10.3.0.75
Port:			keystone5000	5000/TCP
Endpoints:		10.2.72.9:5000
Port:			keystone35357	35357/TCP
Endpoints:		10.2.72.9:35357
Session Affinity:	None
No events.
```

Setup is mainly using https://github.com/pbx0/coreos-kubernetes/tree/single-rktnetes

**Comment by steveeJ** [comment]
@Quentin-M you don't mention if it's working for you or not, so I assume it's additional debug information?

**Comment by Quentin-M** [comment]
@steveeJ As you can see in the third code block, the pod successfully curl'd a service, after resolving its name via the DNS service.

**Comment by steveeJ** [comment]
@Quentin-M 
> As you can see in the third code block, the pod successfully curl'd a service, after resolving its name via the DNS service.

Thanks for the clarification. Can you give us a diff between your local repo and #551?

**Comment by pbx0** [comment]
I moved kube-proxy from alpha.5 to v1.3.0 and it appeared to have fixed things.

**Comment by pbx0** [comment]
Scratch that, I may be getting delirious and never fixed it at all. I had updated kube-proxy and tried adding back `--reconcile-cidr=true` and `--pod-cidr=${POD_NETWORK}`. I'll re-open for now and have to revisit this. I'm not sure this helps though I think previously, I just didn't wait long enough for the restarts.

**Comment by steveeJ** [comment]
I've got the following result

```
$ kubectl --kubeconfig=./kubeconfig --namespace=kube-system get po
NAME                                  READY     STATUS    RESTARTS   AGE
heapster-v1.1.0-3647315203-un53i      2/2       Running   0          32s
kube-apiserver-172.17.4.99            1/1       Running   0          1m
kube-controller-manager-172.17.4.99   1/1       Running   0          1m
kube-dns-v15-raaxi                    3/3       Running   0          1m
kube-scheduler-172.17.4.99            1/1       Running   0          1m
kubernetes-dashboard-v1.1.0-akyd3     1/1       Running   0          1m
```
Connectivity to the service IP works fine from the DNS pod too, tested manually.

Here's [the diff](https://gist.github.com/steveeJ/f0505be82c5595ca8c3708fa5a30b3a8) against the #551, but in short: I disabled Docker.

**Comment by Quentin-M** [comment]
Good catch. I remember masking docker on my rkt nodes too to get proper networking - a while ago.

**Comment by pbx0** [comment]
OK so the reason this doesn't work is because the docker0 bridge is getting set by flannel on CoreOS. This doesn't work when delegating to CNI because cni creates its own bridge with the same IP. Its not clear to me if docker should understand how to deal with this or if we just shouldn't be doing this on CoreOS.

```
5: docker0    inet 10.2.44.1/24 scope global docker0\       valid_lft forever preferred_lft forever
6: cni0    inet 10.2.44.1/24 scope global cni0\       valid_lft forever preferred_lft forever
```

However, the solution for this repo is fairly easy, we just change docker's execstart line from
`ExecStart=/usr/lib/coreos/dockerd daemon --host=fd:// $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ`
to
`ExecStart=/usr/lib/coreos/dockerd daemon --host=fd:// $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ`

I'll update the rktnetes PR with this fix for now. Also we require CNI binaries >= v0.3.0 for rktnetes which has made it into kubernetes master but not a release yet.

**Comment by steveeJ** [comment]
> However, the solution for this repo is fairly easy, we just change docker's execstart line

Am I correct that this will break Docker containers that want to use the bridge? Is getting CNI and Docker to cooperate within the same flannel allocated subnet on the same bridge something we want to do?

**Comment by pbx0** [comment]
@steveeJ Well docker + kubernetes + cni is broken for me right now with this setup, but it was so before this change as well. I don't think changing the bridge IP is the problem in this case. While it might break someone launching docker containers on their own from benefitting from flannel networking -- For the kubernetes case, the kubelet should just be launching containers and specifying use of the cni0 bridge I believe. Does this sound right?
