### ISSUE TITLE
Document process for accessing the kube-dashboard

### ISSUE THREAD

**Issue by aaronlevy** [coreos/coreos-kubernetes#576]
Either adding client cert to browser, or using kubectl proxy

/cc @robszumski

**Comment by dghubble** [comment]
I can add something along the lines of what was done here https://github.com/coreos/coreos-baremetal/pull/274/commits/281e41159425e40bbca359c07773e511cccccfd0

**Comment by aaronlevy** [comment]
That would be awesome! thanks!
