### ISSUE TITLE
S3 access slow from docker images inside Kubernetes (kube-aws 0.7.1, k8s 1.2.4)

### ISSUE THREAD

**Issue by gmaybrun** [coreos/coreos-kubernetes#579]
First off, I'm sorry I don't have anything too well-defined to put here. I've been experimenting with using kube-aws to launch a K8s cluster for production use, and as a side-effect I'm seeing significantly slower access to S3 from within the docker images owned by Kubernetes.

I tested on four separate instances in `us-west-1`:

1) Using kube-aws (v0.7.1, K8s 1.2.4) to create a cluster of m3.medium's in an existing VPC (allowing kube-aws to create its own subnets). Besides this, the only changes were to `cluster.yaml`: `releaseChannel: true` and `workerCount: 2`

2) Same setup as above, but with `useCalico: true` and `kubernetesVersion: v1.2.4_coreos.cni.1`

3) A manually launched CoreOS-stable-1010.5.0-hvm on an m3.medium (this is the same AMI that kube-aws is using -- is ami-79473c19).

4) A manually launched Amazon Linux AMI 2016.03.3 (HVM), SSD Volume Type (ami-31490d51).

On all four instances even a simple test such as running (within a Docker container) `aws s3 ls s3://some-bucket` takes approximately twice as long from the containers running on K8s machines than the standalone CoreOS machine or the Amazon Linux machine. The same goes for downloading files from S3 -- consistently twice as long.

When running a similar test using the image `arjanschaaf/centos-qperf`, I see very little performance impact on docker-to-docker communication on K8s vs non-K8s.

Similarly, running tests with the image `imlonghao/speedtest-cli` show almost identical results between K8s, CoreOS Docker, and Amazon Linux.

I don't have any idea why S3 would be slower, but would greatly appreciate any direction or suggestions on this issue.

**Comment by spacepluk** [comment]
Are you using the same s3 endpoint in all your tests?

**Comment by gmaybrun** [comment]
Yes, for example using `aws s3 --endpoint https://s3-us-west-1.amazonaws.com ls s3://some-bucket-in-us-west-1`

**Comment by gmaybrun** [comment]
To add a little more information.  The following script again takes roughly 1.5-2x as long inside a K8s docker vs anywhere else:

```python
import time
from boto.s3.connection import S3Connection

t0 = time.time()
conn = S3Connection(is_secure=True, host='s3.amazonaws.com')
k = conn.get_bucket('some-bucket').get_key('some-20mb-file')
foo = k.get_contents_as_string()
print(time.time() - t0)
```

However if I get generate a signed URL for retrieval and use curl, the timing is the same from K8s docker vs elsewhere:
```python
import time
import subprocess
from boto.s3.connection import S3Connection

t0 = time.time()
conn = S3Connection(is_secure=True, host='s3.amazonaws.com')
k = conn.get_bucket('some-bucket').get_key('some-20mb-file')
subprocess.call(['curl', '-o', '/dev/null', k.generate_url(expires_in=30)])
print(time.time() - t0)
```

**Comment by spacepluk** [comment]
Hmm,
I don't know what might be the reason for this, but the fact that curl goes full speed signals that there's no bottleneck in K8s.

I just checked on my environment and I get the same speed from a K8s container and from a small Arch Linux machine that I deployed on the same VPC/subnet just for testing.

My test was `aws sync` a big folder with ~30Mb files and measuring speeds with `speedometer`.  In both cases I get around 120Mb/s.

**Comment by tigrawap** [comment]
How did you pass credentials for AWS into container?

It could be delays on userinfo credentials fetch via private ip address
Did you try providing AWS credentials as env vars?

**Comment by gmaybrun** [comment]
I've tried specifying credentials via `~/.aws/{config,credentials}`, via ENV vars `AWS_ACCESS_KEY_ID`/`AWS_SECRET_KEY`/`AWS_REGION`, and as arguments passed to the `S3Connection` constructor.

I reran the same tests using speedometer, and agree that in terms of raw network usage, K8s is making no difference (all tests tap out at roughly the same network speed). Not really sure what to check from here...

**Comment by spacepluk** [comment]
Maybe DNS resolution is slow?

**Comment by gmaybrun** [comment]
I'm not sure of the best way to benchmark DNS resolution, but just running `dig` against several domains (amazonaws.com, google.com, s3-us-west-1.amazonaws.com) shows `Query time` of either 0ms or 1ms. For uncached domains it's around 8ms. So I'm thinking DNS lookups aren't the culprit.  `resolv.conf` inside K8s is: 

    nameserver 10.0.0.2
    search us-west-1.compute.internal

**Comment by gmaybrun** [comment]
This issue exists on a 100% default kube-aws cluster.

Create a 100% default kube-aws cluster in `us-east-1b`:
```
kube-aws init --cluster-name k8s-test2 --external-dns-name k8s-test.stage.domain.tld --availability-zone us-east-1b --key-name my-key-name --kms-key-arn my-kms-arn --region us-east-1
kube-aws render
kube-aws validate
kube-aws up
```

Create a bucket in `us-east-1` and put a large test file in it:
```
aws s3 mb --region us-east-1 s3://my-k8s-testing-bucket
dd if=/dev/random of=/tmp/random-data bs=1m count=40
aws s3 cp /tmp/random-data s3://my-k8s-testing-bucket
```

Log into a k8s worker, run a debian container, and try downloading the file via curl and via boto. Curl is consistently ~30% faster in terms of time-to-completion. Watch with speedometer for fun.
```
# In terminal 1
ssh core@<worker IP>
docker run -it debian

apt-get update && apt-get install -y speedometer

speedometer -r eth0 -t eth0
```

```
# In terminal 2, after terminal 1 has completed installation of speedometer
ssh core@<worker IP>

docker exec -it $(docker ps |grep debian|awk '{print $1}') bash

apt-get update && apt-get install -y python-pip curl && pip install boto

cat >/tmp/test.py <<EOF
import time
from boto.s3.connection import S3Connection
import subprocess
import os

AWS_ACCESS_KEY_ID='something here'
AWS_SECRET_ACCESS_KEY='something here'
S3_BUCKET = 'my-k8s-testing-bucket

def download_via_sdk(is_secure=True):
    conn = S3Connection(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, is_secure=is_secure, host='s3.amazonaws.com')
    k = conn.get_bucket(S3_BUCKET).get_key('random-data')
    foo = k.get_contents_as_string()

def download_via_curl(is_secure=True):
    from boto.s3.connection import S3Connection
    conn = S3Connection(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, is_secure=is_secure, host='s3.amazonaws.com')
    k = conn.get_bucket(S3_BUCKET).get_key('random-data')
    devnull = open(os.devnull, 'w')
    subprocess.call(['curl', '-o', '/dev/null', k.generate_url(expires_in=5)], stdout=devnull, stderr=devnull)
    devnull.close()

def mean(lst):
    return float(sum(lst)) / float(len(lst))

def std(lst):
    m = mean(lst)
    return (sum(float(i-m)**2 for i in lst) / (len(lst) - 1)) ** 0.5

def run(cb, n=10):
    ts = []
    for _ in xrange(n):
        t0 = time.time()
        cb()
        ts.append(time.time() - t0)
    if n == 1:
        return ts[0], 0
    return mean(ts), std(ts)

if __name__ == '__main__':
    print 'download_via_sdk (mean, std): ', run(download_via_sdk, 100)
    print 'download_via_curl (mean, std): ', run(download_via_curl, 100)
EOF

python /tmp/test.py
```

**Comment by spacepluk** [comment]
Maybe you're running into this? https://github.com/boto/boto3/issues/268

**Comment by aaronlevy** [comment]
I don't think this is an issue we're going to be able to resolve here, but curious if there is any update?

My first guess would have been what @spacepluk mentioned, and that inside the container we're hitting the cluster-dns server first (10.0.0.2) which maybe can't resolve some internal aws domains (not sure if boto tries to do some internal magic here) - so the request has to time out, then continue to next nameserver - which then can resolve the hosts. Just a guess.

I'm going to close this issue, as I don't think it's related to how we're running kubernetes on CoreOS, but please let me know if I should re-open the issue.
