### ISSUE TITLE
add ability to customize security group rules

### ISSUE THREAD

**Issue by sym3tri** [coreos/coreos-kubernetes#588]
In my use-case i want to allow a specific port range. It'd be nice if I could just configure this in cluster.yaml

i.e.

```yaml
# Single TCP port or range to allow inbound access to worker nodes.
# Useful for exposing services using NodePorts.
workerInboundPorts: 32000-321000
```

**Comment by whereisaaron** [comment]
I think this is almost a duplicate of #537 which lets you add one or more security groups to be associated with workers and controllers during 'kube-aws render'. The security groups you specify can include the ports to allow.

Alternatively could also the port ranges or groups to the CloudFormation template before you use 'kube-aws render'.

**Comment by aaronlevy** [comment]
I'm going to close as duplicate. I'm also hesitant to try and plumb through all cloudFormation options when they could be modified in the cloudFormation directly. If we end up pushing all the options through to the cluster.yaml, then we may as well just use the cloudFormation directly anyway
