### ISSUE TITLE
Usage with existing cloudformation

### ISSUE THREAD

**Issue by olalonde** [coreos/coreos-kubernetes#589]
I have an existing Cloudformation stack which launches an RDS instance and an ElastiCache instance. I need both of those to be in the same VPC as kubernetes. I'm not sure what would be the best way to achieve this without having to hard code the VPC ID in my CF files. Is it safe to use the cloudformation template generated by kube-aws as a nested stack? I assume I wouldn't be able to use the kube-aws up command directly in that case.

**Comment by c-knowles** [comment]
I've just started to use kube-aws inside this project so I'm not an expert but I saw `vpcId`, `vpcCIDR` and `routeTableId` inside the cluster.yaml that is customisable for using an existing VPC. Maybe that's a good way to go.

**Comment by olalonde** [comment]
Ok thanks, yeah maybe that would be more simple. I just learned about nested Clouformation stack and found it nice that it would allow me to re-use multiple templates without having to hardcode IDs in them, but not sure if that's realistically do-able with kube-aws.

**Comment by olalonde** [comment]
It seems the generated `stack-template.json` isn't a valid cloudformation template but needs to be processed by `kube-aws` first so I guess my nested template idea won't work. I'm wondering what template system it uses.

**Comment by c-knowles** [comment]
My experience of CloudFormation nested templates is I generally avoid them since they have to be uploaded separately to S3 which means you can't really send a set of them together in one go. Last time I checked this meant you lose traceability on the AWS console since the template recorded for the stack just holds the reference to the S3 file which could have changed since the stack creation. I prefer to use a template generator for a similar purpose to generate the entire stack together but keep parts of it re-useable. I don't yet know though whether `kube-aws` supports any extensions like that so hopefully someone else can comment.

**Comment by iwarp** [comment]
Ive run into the same issue, I wanted to pass in security groups vpc and autoscale size, i solved this via altering the stack_template.json to use CloudFormation Parameters so i can pass in the VPC from the higher level CF stack. This also gave me a way to change the autoscale group for the worker without having to re-export the cloudformation template and effecting the userdata encryption causing a rebuild of the entire landscape.

**Comment by olalonde** [comment]
@iwarp thanks for the tip. how did you generate `stack_template.json` though? the one I got from `kube-aws` was not properly formatted json (it contained some Go template snippets).

**Comment by iwarp** [comment]
once i've run the  "kube-aws render" i replace the stack_template.json, i can then run the kube-aws up --export as many times as i need. Yes your right the stack_template does contain Go templates, ive just left them in, attached is my template file.

[stack-template.txt](https://github.com/coreos/coreos-kubernetes/files/389351/stack-template.txt)

**Comment by aaronlevy** [comment]
I'm going to close this issue as it seems like a resolution has been found, but please let me know if we should re-open
