### ISSUE TITLE
No hyperkube image for 1.3.3

### ISSUE THREAD

**Issue by mattymo** [coreos/coreos-kubernetes#590]
Kubernetes v1.3.3 was released a few days ago and it would be nice to see CoreOS parity with gcr.io official images. CoreOS packaged hyperkube is far easier to work with, largely due to the Debian base docker image. When can we expect v1.3.3 and is there a general cadence to following releases? Should the delay be measured in days or weeks?

**Comment by aaronlevy** [comment]
Sorry for the delay, there were a few back-to-back releases with not much heads-up as far as timing. This last release was on Friday, so we didn't get started on validation until yesterday (Monday).

We should have something out soon (if all testing goes well, hopefully today).

**Comment by pbx0** [comment]
v1.3.3+coreos.0 is available!
