### ISSUE TITLE
IAM role policy for route53 missing

### ISSUE THREAD

**Issue by andrejvanderzee** [coreos/coreos-kubernetes#593]
When you create a cluster with **kube-aws**, the IAM role policies for route53 are required for federations. Starting the controller manager without the appropriate policy results in this error:

```
I0730 11:02:54.546106       1 servicecontroller.go:267] DNS zone "federation.com." not found.  Creating DNS zone "federation.com.".
E0730 11:02:54.635894       1 controllermanager.go:128] Failed to start service controller: AccessDenied: User: arn:aws:sts::XXXXXXXXX:assumed-role/eu-west-IAMRoleWorker-111XNNQL6I0Q1/i-058b9f62da378f89e is not authorized to perform: route53:CreateHostedZone
    status code: 403, request id: 2a6c2074-5645-11e6-90e0-cb8f82179241
```

Now we have to manually add this policy in the AWS console:

```
{
      "Effect": "Allow",
      "Action": ["route53:*"],
      "Resource": ["*"]
 }
```

**Comment by colhom** [comment]
@andrejvanderzee I would like the deployer to specify which route53 hosted zones Kubernetes should have access to in `cluster.yaml`. There is a lot of trust placed in the integrity of DNS records, and single accounts often have dozens of zones- I think allowing `*` is hazardous.
