### ISSUE TITLE
kubernetes cni plugin + flannel + docker networking issues

### ISSUE THREAD

**Issue by pbx0** [coreos/coreos-kubernetes#595]
Sort of related to https://github.com/coreos/coreos-kubernetes/issues/572. In this issue rkt containers couldn't contact service IPs because docker was creating a `docker0` bridge with an IP that was passed in from flannel (for direct docker + flannel configuration). I disabled this bridge ip option and rkt cni networking was fixed.

However, docker networking with cni remains broken. `docker0` and `cni0` are both created. Presumably pods being created from kubernetes are just told to use the `cni0` bridge, but, I think there is something I don't understand here. Interestingly enough if you configure the `USE_CALICO` option, docker appears to work and `cni0` is never created.

This is reproducible from my [rktnetes PR](https://github.com/coreos/coreos-kubernetes/pull/551) since it configures both rkt and docker through a cni config passed to the kubelet. Pods not using `--net=host` such as dns and the dashboard will crashloop.

@steveeJ @euank

**Comment by euank** [comment]
To be clear, is the old method of using flannel directly via docker being disabled entirely (the subnet and bip bits) in favor of CNI?

**Comment by pbx0** [comment]
Disabling only in the sense that we don't pass certain options into dockerd that we used to do. Not sure if there are other hooks here I am missing.

**Comment by euank** [comment]
@pbx0 Doing some log diving, the dns image is trying to access the `10.3.0.1` service ip. That ip indeed does not appear to be routable. I think the root cause of that is a lack of a running `kube-proxy`.

**Comment by pbx0** [comment]
Ack yes, sadly this was PEBKAK type of error where a misconfigured slipped that was causing the proxy not to run for docker. Closing.

**Comment by tomdee** [comment]
Sorry, I was on vacation for the last week this missed this issue. Glad you solved it, ping me if I can provide any other help.

**Comment by TerraTech** [comment]
@pbx0 I just converted over to using rktnetes+CNI, and I'm now hitting this too (related https://github.com/coreos/coreos-kubernetes/issues/572).  What was the misconfiguration you found?  I'm thinking something is left over from the old `flannel` only config.

interfaces:
cni0: 10.11.57.1/24
docker0: 10.11.57.1/24

**Comment by pbx0** [comment]
@TerraTech I'm not sure if your having the same issue as I did in this issue but, I have run into this before! See: https://github.com/coreos/coreos-kubernetes/issues/698#issuecomment-250633015

Basically, flannel is passing two environment variables to the docker daemon that is no longer needed with CNI. If those variables aren't removed the docker0 bridge will come up with the same IP as the cni0 bridge and cause problems. The fix is in these two commits: 
Original Change: 7ad1347
A followup commit that works with docker 1.11 and 1.12: 00591a2

The first commit adds a drop-in to the docker.service that leaves out the `DOCKER_OPT_BIP`
`DOCKER_OPT_IPMASQ` environment variables that are set by flannel. The second commit just overrides those variables with an Environment file because the dockerd command line changed recently making the first fix obsolete.

Let me know if this doesn't solve your problem.

**Comment by TerraTech** [comment]
@pbx0 thanks for the followup!
My attention got diverted to https://github.com/coreos/coreos-kubernetes/issues/707 and at this point, I just shutdown docker on the master and workers since the cluster is based on rktnetes.  So far, the regular podnet is working fine with no collisions, though I'm having a major problem with the service IPs.
