### ISSUE TITLE
Is there any plan to add the kubernetes load balancer to vagrant?

### ISSUE THREAD

**Issue by wolfeidau** [coreos/coreos-kubernetes#60]
Tried to run through the guestbook example and it worked for the most part except there is no load balancer so services aren't exposed by the cluster in the normal way.

I managed to get the guest book example working as it was exposed as a nodeport but still a bit confusing / limited.

I would love to use this stack for demos locally but I really need the load balancer.

Cheers

**Comment by vyshane** [comment]
I believe that [load balancing](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#type-loadbalancer) is only supported on cloud providers.

**Comment by aaronlevy** [comment]
We don't currently set the Vagrant cloud-provider. Even so, the cloud-provider code for vagrant is a no-op (see: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vagrant/vagrant.go#L94-L97)

Using the service NodePort, as you mentioned, is generally the way you would expose the service in situations where there is no platform-specific loadbalancer support: http://kubernetes.io/v1.0/docs/user-guide/services.html#external-services

If you want to setup a load-balancer in front of your vagrant nodes, it would need to be done manually at this time. However, there is an proposal for adding this type of functionality for platforms that do not have load-balancer integration: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer
