### ISSUE TITLE
Hyperkube v1.3.4_coreos.0 doesn't load calico cni

### ISSUE THREAD

**Issue by mattymo** [coreos/coreos-kubernetes#600]
This doesn't affect previous CoreOS Hyperkube releases or Google's hyperkube at gcr.io/google_containers/hyperkube:v1.3.4

If I put calico in /opt/cni/bin/calico and populate /etc/cni/net.d/10-calico.conf with the following:
```{
  "name": "calico-k8s-network",
  "type": "calico",
  "etcd_authority": "127.0.0.1:2379",
  "log_level": "info",
  "ipam": {
    "type": "calico-ipam"
  }
}```

I end up with the following error when starting a pod:
Aug  3 18:13:24 ubuntu1604 kubelet[2920]: E0803 18:13:24.899619    2949 cni.go:201] Error adding network: could not find "." plugin
Aug  3 18:13:24 ubuntu1604 kubelet[2920]: E0803 18:13:24.899755    2949 cni.go:152] Error while adding to cni lo network: could not find "." plugin
Aug  3 18:13:24 ubuntu1604 kubelet[2920]: E0803 18:13:24.900999    2949 docker_manager.go:1977] Failed to setup network for pod "dnsmasq-j0x50_kube-system(2c6f3dea-598b-11e6-b076-6445f31b27c9)" using network plugins "cni": could not find "." plugin; Skipping pod
Aug  3 18:13:25 ubuntu1604 kubelet[2920]: E0803 18:13:25.006670    2949 pod_workers.go:183] Error syncing pod 2c6f3dea-598b-11e6-b076-6445f31b27c9, skipping: failed to "SetupNetwork" for "dnsmasq-j0x50_kube-system" with SetupNetworkError: "Failed to setup network for pod \"dnsmasq-j0x50_kube-system(2c6f3dea-598b-11e6-b076-6445f31b27c9)\" using network plugins \"cni\": could not find \".\" plugin; Skipping pod"

**Comment by pbx0** [comment]
We currently ship the calico plugin in the rootfs of `quay.io/coreos/hyperkube:v1.3.4_coreos.0` So if you are using the kubelet-wrapper script we ship with coreos to run the kubelet, the kubelet should be able to detect the cni plugins under `/opt/cni/bin/`. Do you have more information about how you are invoking the kubelet within the hyperkube image?

Is it possible you are bind mounting something over the `/opt/cni/bin`folder inside the container?

**Comment by mattymo** [comment]
@pbx0 thanks for pointing this out. Google's hyperkube is still missing it, so I can't test it the same way for parity's sake.

This works for running kubelet:
#!/bin/bash
/usr/bin/docker run --privileged --rm \
--net=host --pid=host --name=kubelet \
-v /etc/cni:/etc/cni:ro \
-v /etc/kubernetes:/etc/kubernetes \
-v /sys:/sys \
-v /dev:/dev \
-v /var/lib/docker:/var/lib/docker \
-v /var/run:/var/run \
-v /var/lib/kubelet:/var/lib/kubelet \
quay.io/coreos/hyperkube:v1.3.4_coreos.0 \
nsenter --target=1 --mount --wd=. -- \
./hyperkube kubelet \
$@

This doesn't:
#!/bin/bash
/usr/bin/docker run --privileged --rm \
--net=host --pid=host --name=kubelet \
-v /etc/cni:/etc/cni:ro \
-v /opt/cni:/opt/cni:ro \
-v /etc/kubernetes:/etc/kubernetes \
-v /sys:/sys \
-v /dev:/dev \
-v /var/lib/docker:/var/lib/docker \
-v /var/run:/var/run \
-v /var/lib/kubelet:/var/lib/kubelet \
quay.io/coreos/hyperkube:v1.3.4_coreos.0 \
nsenter --target=1 --mount --wd=. -- \
./hyperkube kubelet \
$@

Dropping the nsenter line has the same effect on Docker 1.11 with MountFlags=shared. MountFlags=slave requires the nsenter hack.

I'm still trying to figure out what's fundamentally different between your hyperkube and Google's. Mounting the /opt/cni directory shouldn't make any difference.

**Comment by pbx0** [comment]
So, I think your issue in the second case is that you do `-v /opt/cni:/opt/cni:ro \` which bind mounts the host's `/opt/cni` over the container's `/opt/cni`. If your host cni directory has either the wrong permissions or doesn't contain all the plugins, this may be where you are having a problem. 

Now what I still don't understand is why the second case would fail with our hyperkube but not with upstream's hyperkube since you are just relying on your own cni dir at this point. Can you do an `ls -l /opt/bin/cni` on your host? Our hyperkube image contains:

```
-rwxrwxr-x. 1 root root  4875584 Jul 11 21:02 bridge
-rwxrwxr-x. 1 root root  8858402 Aug  2 02:20 calico
-rwxrwxr-x. 1 root root  3553952 Jul 11 21:02 cnitool
-rwxrwxr-x. 1 root root 10402056 Jul 11 21:02 dhcp
-rwxrwxr-x. 1 root root  3601416 Jul 11 21:02 flannel
-rwxrwxr-x. 1 root root  3821192 Jul 11 21:02 host-local
-rwxrwxr-x. 1 root root  4273352 Jul 11 21:02 ipvlan
-rwxrwxr-x. 1 root root  3868496 Jul 11 21:02 loopback
-rwxrwxr-x. 1 root root  4290392 Jul 11 21:02 macvlan
-rwxrwxr-x. 1 root root  4858784 Jul 11 21:02 ptp
-rwxrwxr-x. 1 root root  3726720 Jul 11 21:02 tuning
```

We've tried to start providing better documentation on the differences between our hyperkube distribution and upstream's distribution. We aim to keep closing the gap and at least not become more divergent. See: https://github.com/coreos/kubernetes/releases/.

**Comment by mattymo** [comment]
$ ls -l /opt/cni/bin/
total 17304
-rwxr-xr-x 1 root root 8858402 Aug  4 12:54 calico
-rwxr-xr-x 1 root root 8858402 Aug  4 12:54 calico-ipam

Calico instructions say you only need the calico binary there.

**Comment by pbx0** [comment]
I can't speak to how Calico works, but I suspect the issue here is the lack of other plugins.

**Comment by tomdee** [comment]
@mattymo If you're running Calico in this repo then you're running it in _Canal_ mode (i.e.using it with Flannel). This means you would be using the `flannel` CNI plugin and the `host-local` plugin for IPAM instead of `calico-ipam`.

**Comment by mattymo** [comment]
Thanks! I'll close this issue.

**Comment by mattymo** [comment]
@tomdee can you please explain the difference in Kubernetes cni config between "Calico mode" and "Canal mode"? Why would it run flannel if I configure calico as the plugin name? Why the switch between v1.3.3 and v1.3.4 here and what makes your hyperkube binary so much different from Google's?

**Comment by tomdee** [comment]
Hi @mattymo  - see here for some more explanation https://github.com/coreos/coreos-kubernetes/blob/0351183a3c18c642bb0f7bbf33bede1af494e46a/Documentation/deploy-workers.md#set-up-the-cni-config

In "canal" mode, the CNI plugin is flannel and it's delegating to Calico (i.e. flannel for data plane and Calico for network policy)

In "Calico" mode, Calico is just being used directly and it being used for both data-plane and policy).

The plugin name is just an opaque string, the `type` actually determines what plugin to use.

I don't believe there's any difference between 1.3.3 and 1.3.4 (but maybe I'm wrong?). The change to add Calico to the hyperkube image is minimal and here - https://github.com/coreos/kubernetes/commit/5e1e4bfbc38b58316d30e9d23a28549db4d0b6b6

**Comment by aaronlevy** [comment]
I'm going to close this issue as resolved. But please let me know if it should be re-opened.
