### ISSUE TITLE
401 Unauthorized kube-apiserver in multiple master nodes front of ELB

### ISSUE THREAD

**Issue by sachincab** [coreos/coreos-kubernetes#609]
Hi,

We are trying to achieve high availability cluster with multiple master nodes front ELB.
Also trying to use ingress to layer 7 traffic from ELB to master nodes.
http://kubernetes.io/docs/user-guide/ingress/#tls

apiserver-key and apiserver cert configured as secrets.

We also have external hostname for apiserver which points to ELB.
**Scenario-1**: Request through external hostname and passing through ELB get HTTP/1.1 401 Unauthorized error.

**Scenario-2**: service endpoint HTTPS request is working fine over https and admin crt and key.
```
curl -v --cacert ca.pem https://kubernetes.default.svc.cluster.local/version --cert admin.pem --key admin-key.pem

Host: kubernetes.default.svc.cluster.local
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 10 Aug 2016 16:34:24 GMT
< Content-Length: 260
<
{
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.4",
  "gitCommit": "dd6b458ef8dbf24aff55795baa68f83383c9b3a9",
  "gitTreeState": "clean",
  "buildDate": "2016-08-01T16:38:31Z",
  "goVersion": "go1.6.2",
  "compiler": "gc",
  "platform": "linux/amd64"
* Connection #0 to host kubernetes.default.svc.cluster.local left intact
```

**Ingress config:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: no-rules-map
spec:
  tls:
    - secretName: testsecret
  backend:
    serviceName: kubernetes
    servicePort: 443
```

```
kubectl describe ing
Name:			no-rules-map
Namespace:		default
Address:
Default backend:	kubernetes:443 (172.18.2.4:443,172.18.2.5:443)
TLS:
  testsecret terminates
Rules:
  Host	Path	Backends
  ----	----	--------
  *	* 	kubernetes:443 (172.18.2.4:443,172.18.2.5:443)
Annotations:
No events.
```

**TLS secret details:**
```
kubectl describe secrets testsecret
Name:		testsecret
Namespace:	default
Labels:		<none>
Annotations:	<none>

Type:	Opaque

Data
====
tls.crt:	1675 bytes
tls.key:	1679 bytes
```
------------------------------------------------------------------------------------

Question: can you please let me know your inputs why HTTPS request for apiserver fails through external hostname passing through ELB?

Please let me know if you need any more information on this.

Thanks!

**Comment by sachincab** [comment]
Just to add, client certificate authentication work properly with kubernetes svc endpoint: kubernetes.default.svc.cluster.local. However it gives 401 Unauthorized errors while accessing through ELB hostname with ingress with TLS secret mentioned above.

On ELB we have,
Load Balancer Protocol Load Balancer Port   Instance Protocol   Instance Port
        HTTPS	                          443   	                 HTTPS	               443

**Comment by aaronlevy** [comment]
@sachincab When you are making requests to the ELB endpoint are you using client-certs? The "Unauthorized" error means the request did not succeed at authenticating against the api-server. The AuthN method could be bearer token, client cert, basic auth, etc. (depends on what you've configured & how you're making the request).


In your

**Comment by aaronlevy** [comment]
I'm going to close this due to inactivity, but please let me know if it should be re-opened
