### ISSUE TITLE
Kubernetes addons?

### ISSUE THREAD

**Issue by wolfeidau** [coreos/coreos-kubernetes#61]
I rolled out the single and multi host setups and noticed the only addon your deploying is kube-dns.

Is there any plan to add others? 

Specifically kube-ui, metrics and logging.

Even some notes on any possible issues doing so would be super handy.

**Comment by aaronlevy** [comment]
Our initial goal is to document the necessary steps to deploy a fully-functional Kubernetes cluster. The DNS Addon, at this stage, is effectively a requirement of a functional Kubernetes cluster.

Once your base Kubernetes cluster is running, you should be able to deploy any of the documented addons / example applications into your cluster. In some cases this should be as simple as `kubectl create -f addon.yaml`

As we move forward, some addons could be added to the set automatically deployed into the vagrant reference installations, but the core goal is to bring up a cluster from which you can deploy any of your Kubernetes applications (addons included).
