### ISSUE TITLE
Changes to the memory not working in `multi-node` vagrant setup config

### ISSUE THREAD

**Issue by wolfeidau** [coreos/coreos-kubernetes#62]
When using the `multi-node` vagrant setup updating one of the vars as follows has no effect.

```
$worker_vm_memory=2048
```

All vms end up using 512 MB of memory anyway.

Only way to fix it is modify the `config.rb` as follows, but this results in ALL vms using 1024 MB.

```
diff --git a/multi-node/vagrant/Vagrantfile b/multi-node/vagrant/Vagrantfile
index 771b674..a85ede8 100644
--- a/multi-node/vagrant/Vagrantfile
+++ b/multi-node/vagrant/Vagrantfile
@@ -10,11 +10,11 @@ Vagrant.require_version ">= 1.6.0"

 $update_channel = "alpha"
 $controller_count = 1
-$controller_vm_memory = 512
+$controller_vm_memory = 1024
 $worker_count = 1
-$worker_vm_memory = 512
+$worker_vm_memory = 1024
 $etcd_count = 1
-$etcd_vm_memory = 512
+$etcd_vm_memory = 1024

 CONFIG = File.expand_path("config.rb")
 if File.exist?(CONFIG)
```

**Comment by aaronlevy** [comment]
I was not able to reproduce the issue. I copied `config.rb.sample` to `config.rb` and modified the vm_memory values to 1024 for all node types (up from 512 default) and the updated value was used.

To modify the memory or node count, the changes should only be made in the `config.rb` file, as whatever is in this file will be used. In your above diff, you're modifying the Vagrantfile directly. Is it possible your config.rb still has 512 -- which is overriding the changes you made in the Vagrantfile?

**Comment by wolfeidau** [comment]
Try this configuration.

```ruby
$update_channel="alpha"

$controller_count=1
$controller_vm_memory=512

$worker_count=1
$worker_vm_memory=2048

$etcd_count=1
$etcd_vm_memory=512
```

From what I observed you will end up with 3 VMs all running 512MB of ram.

**Comment by aaronlevy** [comment]
I am still not able to reproduce the issue. I copy/pasted your configuration above into `config.rb` and the nodes that launched had the correct memory.

One possibility: be sure you're putting your configuration in `config.rb` not `config.rb.sample`.

**Comment by aaronlevy** [comment]
@wolfeidau were you able to get this working?

**Comment by aaronlevy** [comment]
Let me know if this issue needs to be reopened.
