### ISSUE TITLE
KubeDNS Addon should uses kubedns instead of etcd/kube2sky

### ISSUE THREAD

**Issue by Quentin-M** [coreos/coreos-kubernetes#625]
The KubeDNS addon doesn't use etcd + kube2sky anymore but kubedns. We should update the docs accordingly.

- https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns
- https://github.com/kubernetes/kubernetes/commit/4c1047d359fa1ee64aa30508b5be4407aeec19a3.

**Comment by aaronlevy** [comment]
There are a couple open PRs that started this work, but didn't get all the way there.

https://github.com/coreos/coreos-kubernetes/pull/607
https://github.com/coreos/coreos-kubernetes/pull/603

@colhom last we spoke you said you were going to take a look at this? Any updates?
