### ISSUE TITLE
kubelet doesn't attempt to start api server

### ISSUE THREAD

**Issue by tdavis** [coreos/coreos-kubernetes#626]
I have been banging my head against this for about a day now. I've followed documentation exactly, but the kubelet never attempts to start the apiserver as specified in the manifest file. Here are my files, then some random stuff I've tried:

kubelet.service
```
[Service]
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests

Environment=KUBELET_VERSION=v1.3.5_coreos.0
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=http://127.0.0.1:8080 \
  --network-plugin-dir=/etc/kubernetes/cni/net.d \
  --network-plugin= \
  --register-schedulable=false \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --hostname-override=10.142.0.8 \
  --cluster-dns=10.3.0.10 \
  --cluster-domain=cluster.local
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```

/etc/kubernetes/manifests/kube-apiserver.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.3.5_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers=http://10.142.0.8:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=10.3.0.0/24
    - --secure-port=443
    - --advertise-address=10.142.0.8
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/thirdpartyresources=true
    ports:
    - {containerPort: 443, hostPort: 443, name: https}
    - {containerPort: 8080, hostPort: 8080, name: local}
    volumeMounts:
    - {mountPath: /etc/kubernetes/ssl, name: ssl-certs-kubernetes, readOnly: true}
    - {mountPath: /etc/ssl/certs, name: ssl-certs-host, readOnly: true}
  volumes:
  - {hostPath: {path: /etc/kubernetes/ssl, name: ssl-certs-kubernetes}}
  - {hostPath: {path: /usr/share/ca-certificates, name: ssl-certs-host}}
```

journal output for kubelet
```
Aug 17 21:11:21 node systemd[1]: Starting kubelet.service...
Aug 17 21:11:21 node systemd[1]: Started kubelet.service.
Aug 17 21:11:21 node kubelet-wrapper[4680]: image: using image from file /usr/lib64/rkt/stage1-images/stage1-fly.aci
Aug 17 21:11:21 node kubelet-wrapper[4680]: image: using image from local store for image name quay.io/coreos/hyperkube:v1.3.5_coreos.0
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.782904    4680 docker.go:327] Start docker client with request timeout=2m0s
Aug 17 21:11:24 node kubelet-wrapper[4680]: W0817 21:11:24.789015    4680 server.go:487] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
Aug 17 21:11:24 node kubelet-wrapper[4680]: W0817 21:11:24.789053    4680 server.go:448] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.789410    4680 manager.go:138] cAdvisor running in container: "/system.slice/kubelet.service"
Aug 17 21:11:24 node kubelet-wrapper[4680]: W0817 21:11:24.795070    4680 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.801044    4680 fs.go:139] Filesystem partitions: map[/dev/sda9:{mountpoint:/var/lib/docker major:8 minor:9 fsType:ext4 blockSize:0} /dev/sda3:{mountpoint:/usr/lib/os-release major:8 minor:3 fsType: blockSize:0}]
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.808693    4680 manager.go:192] Machine: {NumCores:2 CpuFrequency:2299998 MemoryCapacity:7848099840 MachineID:748cfc5d0ac0444e85d1cccb08411403 SystemUUID:3DA7904A-2DD4-ACA2-7DDF-5D3C11D15657 BootID:718520e2-e0d7-4e4d-aa36-ecff09557010 Filesystems:[{Device:/dev/sda9 Capacity:18327085056 Type:vfs Inodes:4625792} {Device:/dev/sda3 Capacity:1031946240 Type:vfs Inodes:260096} {Device:overlay Capacity:18327085056 Type:vfs Inodes:4625792}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:21474836480 Scheduler:cfq}] NetworkDevices:[{Name:ens4v1 MacAddress:42:01:0a:8e:00:08 Speed:-1 Mtu:1460} {Name:flannel.1 MacAddress:92:e8:70:86:38:67 Speed:0 Mtu:1410}] Topology:[{Id:0 Memory:7848099840 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:47185920 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-2 InstanceID:1259683106711501886}
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.810547    4680 manager.go:198] Version: {KernelVersion:4.7.0-coreos ContainerOsVersion:CoreOS 1122.1.0 (MoreOS) DockerVersion:1.11.2 CadvisorVersion: CadvisorRevision:}
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.811513    4680 server.go:758] Adding manifest file: /etc/kubernetes/manifests
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.811542    4680 server.go:768] Watching apiserver
Aug 17 21:11:24 node kubelet-wrapper[4680]: W0817 21:11:24.811661    4680 kubelet.go:561] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
Aug 17 21:11:24 node kubelet-wrapper[4680]: I0817 21:11:24.811680    4680 kubelet.go:384] Hairpin mode set to "hairpin-veth"
Aug 17 21:11:24 node kubelet-wrapper[4680]: E0817 21:11:24.818191    4680 reflector.go:205] pkg/kubelet/kubelet.go:281: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D10.142.0.8&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Aug 17 21:11:24 node kubelet-wrapper[4680]: E0817 21:11:24.818318    4680 reflector.go:205] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D10.142.0.8&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Aug 17 21:11:24 node kubelet-wrapper[4680]: E0817 21:11:24.818437    4680 reflector.go:205] pkg/kubelet/kubelet.go:262: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

docker ps -a
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS            NAMES
```

As you can see, the kubelet never attempts to even start a docker container for the api server (or anything else in the manifest directory, but one step at a time I suppose).

There is no error in the log indicating a parse error; I tried using json instead in case there was a silent error. I tried pointing ``--config`` to just the ``kube-apiserver.yaml`` in case some other file was tripping it up. 

I tried running the binary ``kube-apiserver`` directly with the same arguments; it started successfully and kubelet stopped complaining about a refused connection (though it still didn't start any other pods).

Currently on the beta channel; same result with stable channel.

**Comment by aaronlevy** [comment]
@tdavis I validated your api-server manifest by trying to create it against an existing cluster:

`kubectl create -f apiserver.yaml`

And the output:

```
error validating "apiserver.yaml": error validating data: [field name: is required, found invalid field name for v1.HostPathVolumeSource, field name: is required, found invalid field name for v1.HostPathVolumeSource];
```

Unfortunately I don't think there's an easy way to do this same validation in the absence of an api-server (which you're trying to create). One option is to spin up a single-node local cluster then throw your manifest at it.

As a point of reference, here is the generic api-server manifest we use: 

https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh#L261-L313

**Comment by jpweber** [comment]
I'm having the same issue. Using the cloud formation instructions here https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html

**Comment by tdavis** [comment]
@aaronlevy Sorry for the misdirection; I copy-pasta'd the wrong file version. That was after I'd changed the yaml-style maps to json-style in an attempt to appease the yaml parser but before the logs indicated I had screwed it up where I put the "name" bit.

**Comment by tdavis** [comment]
(I was using the exact version you linked to before I got desperate and just assumed it was silently failing for some parse-related reason)

**Comment by aaronlevy** [comment]
@tdavis Are you still seeing the same issue?

**Comment by tdavis** [comment]
Yeah, it's the same. Providing a valid manifest doesn't help anything (other than getting rid of the parse error). A Docker container is never run, whether it be for the API service or any other manifest present in the directory.

**Comment by aaronlevy** [comment]
@tdavis is there anything in the docker daemon logs? Or possibly bump up the kubelet log level (`--v6`)

**Comment by eljefedelrodeodeljefe** [comment]
Same issue. Unfortunately this very bad, since e.g. getting access for CI is very hard without it.

**Comment by aaronlevy** [comment]
Could this possibly be related: https://github.com/kubernetes/kubernetes/issues/22130#issuecomment-241958760

Looks like culprit in that case was a VPC with "DNS Hostnames" attribute disabled

**Comment by tdavis** [comment]
With additional logging, this is the only error that jumps out at me as relevant:

    Aug 24 19:09:41 foo.bar.internal kubelet-wrapper[4722]: I0824 19:09:41.631505    4722 metadata.go:205] Failed to Get service accounts from gce metadata server: Get http://metadata.google.internal./computeMetadata/v1/instance/service-accounts/: dial tcp: lookup metadata.google.internal. on 8.8.8.8:53: no such host

Not really sure why it has a trailing period on ``internal.`` or why it's hardcoding 8.8.8.8 as a DNS address. I have no idea if this is a breaking issue, though. It does seem to be making *some* progress, though I still never see a docker container started.

```
Aug 24 19:09:40 foo.bar.internal kubelet-wrapper[4722]: I0824 19:09:40.922991    4722 config.go:384] Receiving a new pod "kube-apiserver-10.142.0.7_kube-system(046f28ca8162d553386160c9d30bf3a7)"
Aug 24 19:09:40 foo.bar.internal kubelet-wrapper[4722]: I0824 19:09:40.923018    4722 config.go:384] Receiving a new pod "kube-controller-manager-10.142.0.7_kube-system(cabdede4ef4f2c7f08707cf23e044b62)"
Aug 24 19:09:40 foo.bar.internal kubelet-wrapper[4722]: I0824 19:09:40.923034    4722 config.go:384] Receiving a new pod "kube-proxy-10.142.0.7_kube-system(9c4297cc7b8f3a6c0f2dc5eae7b7679c)"
Aug 24 19:09:40 foo.bar.internal kubelet-wrapper[4722]: I0824 19:09:40.923049    4722 config.go:384] Receiving a new pod "kube-scheduler-10.142.0.7_kube-system(f1c644f8cd0f822a04759adc4bc84399)"
```

**Comment by aaronlevy** [comment]
That error means it is not able to resolve the internal google metadata hostname. This likely means it cannot determine the nodename from the metadata service (like the issue I linked previously).

In your kubelet.service unit you may need to mount your host `/etc/resolv.conf`, because a public DNS server (8.8.8.8) is not going to be able to resolve the internal domains.

See: https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html#customizing-rkt-options for example of how to mount the host `/etc/resolv.conf` in the kubelet.service file.

**Comment by tdavis** [comment]
That did indeed fix my issue. The stack is pretty confusing to me at this point, though. So, I need to set rkt options for the kubelet wrapper which runs a container via rkt. And then the kubelet rkt container launches other containers via Docker? That still somehow pick up my resolv.conf settings? Or, if I need those settings propagated, I have to do it another way?
