### ISSUE TITLE
Multi-node Vagrant environment not coming up

### ISSUE THREAD

**Issue by jmreicha** [coreos/coreos-kubernetes#63]
Following the docs I am able to start up a multi-node cluster with Vagrant but the Kubernetes bootstrap process seems to get stuck.

The etcd node comes up with no issues, but `w1` and `c1` are having trouble downloading the Docker images.  After the podmaster image downloads it seems that nothing else wants to download on `c1`.  Likewise, on `w1`, nothing downloads after the pause image.

I also noticed that the `update-engine` fails on `w1` and `c1` with this:

```
-- Logs begin at Sun 2015-09-20 19:36:12 UTC, end at Sun 2015-09-20 19:43:30 UTC. --
Sep 20 19:36:16 localhost systemd[1]: Starting Update Engine...
Sep 20 19:36:17 localhost update_engine[583]: [0920/193617:INFO:main.cc(155)] CoreOS Update Engine starting
Sep 20 19:36:17 localhost systemd[1]: Started Update Engine.
Sep 20 19:36:17 localhost update_engine[583]: [0920/193617:INFO:update_check_scheduler.cc(82)] Next update check in 9m23s
Sep 20 19:36:26 w1 systemd[1]: Stopping Update Engine...
Sep 20 19:36:27 w1 systemd[1]: update-engine.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 19:36:27 w1 systemd[1]: Stopped Update Engine.
Sep 20 19:36:27 w1 systemd[1]: update-engine.service: Unit entered failed state.
Sep 20 19:36:27 w1 systemd[1]: update-engine.service: Failed with result 'exit-code'.
```

Any ideas?  Maybe this is a disk space issue?

I have tested the single node Vagrant method and it is working.

**Comment by jmreicha** [comment]
My mistake, I wasn't waiting long enough for the containers to come up.

**Comment by jojimt** [comment]
How long does one need to wait? This is what I get:
[root@kubernetes-master ~]# docker images
REPOSITORY                                         TAG                                IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/google_containers/kube-apiserver            77293eecb909f50b8cf29b7acd42d900   0b59c89529a8        5 days ago          47.97 MB
gcr.io/google_containers/kube-controller-manager   3eaa8fccb04067a9aae35ce88277dc6c   9e77e572763a        5 days ago          40.12 MB
gcr.io/google_containers/kube-scheduler            24811506dd483157b6a02dfdcec4b0fe   392cbc5e9c5f        5 days ago          21.44 MB
[root@kubernetes-master ~]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@kubernetes-master ~]# kubectl --server=http://${KUBE_MASTER_IP}:8080 get nodes
error: couldn't read version from server: Get http://10.245.1.2:8080/api: dial tcp 10.245.1.2:8080: connection refused
