### ISSUE TITLE
Investigate using AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#634]
Issue reported in Kubernetes Slack:

> I found the issue; kube-aws does not honor the AWS_DEFAULT_PROFILE options so was using the wrong parameters.

We should investigate this.

**Comment by cgag** [comment]
It seems none of the aws SDKs support AWS_DEFAULT_PROFILE (we use the aws-sdk-go library), only the aws cli tools do.  It does support the AWS_PROFILE env var.  

Not sure what the answer is.  We could see if that var is set and issue a warning, but it looks like upstream doesn't want to implement it:  https://github.com/aws/aws-sdk-go/pull/554

**Comment by exarkun** [comment]
I only learned about AWS_PROFILE by finding this issue (on my way to filing one about respecting AWS_DEFAULT_PROFILE).  It would be nice if the documentation mentioned AWS_PROFILE as one of the supported ways to specify credentials.  The documentation (https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html) currently mentions several other supported approaches but not this one.
