### ISSUE TITLE
Errror on  generating SSL artifacts

### ISSUE THREAD

**Issue by kerrer** [coreos/coreos-kubernetes#635]
/opt/vagrant/embedded/bin/openssl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
failed generating SSL artifacts

**Comment by aaronlevy** [comment]
@kerrer this seems like an issue with your openssl installation. Can you run `openssl version` successfully?

**Comment by aaronlevy** [comment]
I'm going to close this due to inactivity, but please let me know if it should be re-opened

**Comment by murugavelpsg** [comment]
I am facing a similar issue on my centos 7 when I run "vagrant box update". I am able to run openssl version command successfully. 

```
[root@vegabuild vagrant]# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
