### ISSUE TITLE
should not use .local

### ISSUE THREAD

**Issue by mischief** [coreos/coreos-kubernetes#658]
.local is effectively reserved by RFC 6762 and could cause unintended side effects.

this repo should not use it.

**Comment by bzub** [comment]
Agreed.  I've had issues in the past with Go programs like etcd and flannel when they are statically linked (common, especially when run from small container images).  Go's netgo DNS implementation tries not to resolve .local domains, and there is no other DNS method in statically linked Go programs.
See: https://github.com/golang/go/blob/master/src/net/net.go#L57

**Comment by pieterlange** [comment]
Maybe tie it to `externalDNSName`? Cluster DNS names might get a little bit long but at least it'd be unique.

**Comment by dghubble** [comment]
Seems like this is prevalent in Kubernetes clusters and unlikely to change. https://github.com/coreos/matchbox/pull/542/commits/05925036528858e6b20284dc1c5414e16aa561c4
