### ISSUE TITLE
calico binaries missing in v1.4.0 beta

### ISSUE THREAD

**Issue by abh** [coreos/coreos-kubernetes#662]
It looks like the calico binaries are missing in the 1.4.0 beta (similar to issue #562?)

```
$ docker run quay.io/coreos/hyperkube:v1.3.6_coreos.0 ls /opt/cni/bin | grep -E 'cni|calico'
calico
cnitool
```

vs

```
$ docker run quay.io/coreos/hyperkube:v1.4.0-beta.0_coreos.1 ls /opt/cni/bin | grep -E 'cni|calico'
cnitool
```

**Comment by aaronlevy** [comment]
v1.4.0-beta.3_coreos.0 image has been released, and contains the calico binary. See: 
https://github.com/coreos/kubernetes/releases
https://quay.io/repository/coreos/hyperkube?tab=tags
