### ISSUE TITLE
command:start and enable:true are a dangerous pair

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-kubernetes#676]
@crawford told me this a nasty surprise cloud-config offers it's users: 

`command:start` and `enabled:true` for the same service can lead to it being started prematurely and failing. We have this affliction in our codebase:

https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cloud-config-controller#L38-L39

https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cloud-config-worker#L20-L21

\cc @robszumski @cgag , another candidate for the `failed kubelet.service` due to dependencies symptom.

Will fix

**Comment by crawford** [comment]
When using coreos-cloudinit, set `runtime: true` and do not enable services. This way, services are always started by coreos-cloudinit and in the same order.

**Comment by pbx0** [comment]
Is this just a cloudinit problem? We do a `systemctl start` and then `enable` via scripts for platforms that are not AWS. I know @steveeJ once had a branch that replaced those with `systemctl enable --now`. Is there a best practice we should follow for non-cloud-init `enable` and `start` commands
