### ISSUE TITLE
ELB deletions during kube-aws destroy

### ISSUE THREAD

**Issue by pydevops** [coreos/coreos-kubernetes#683]
Each k8s service with type:LoadBalancer will create a ELB (v1/classic) in the same subnet, does all the grunt work of registering instance, set up listener and k8s NodePort according to the service Manifest. This is good practice. It would be perfect if *kube-aws destory" tear down logic can take care of ELB deletions as well. 

I can verify the ELBs are properly tagged with KubernetesCluster=ClusterName. It is a matter of finding the load balancer by tag, re-generate the CF template and let the AWS CF does it transactional work.

**Comment by felixbuenemann** [comment]
I think the role of `kube-aws destroy` is to tear down the resources created by the cloudformation template. You could destroy all kubernetes namespaces prior to running `kube-aws destroy` to get rid of all the service ELBs and other resources created by kubernetes.

**Comment by pydevops** [comment]
makes sense. close the issue.
