### ISSUE TITLE
Hyperkube v1.4.0_coreos.0 does not contain calico cni

### ISSUE THREAD

**Issue by ArchiFleKs** [coreos/coreos-kubernetes#691]
Hi, I just upgraded Kubelet and Kubernetes component from 1.3 to 1.4 and Calico is not working anymore.

Similar to #662 and #562

```
Sep 27 10:38:27 zero kubelet-wrapper[1984]: E0927 08:38:27.815852    1984 rkt.go:1031] rkt: failed to tear down network for pod heapster-hyve4_kube-system(ecb3604a-83e7-11e6-a887-0050560c9557): failed to find plugin "calico" in path [/opt/cni/bin /opt/flannel/bin]

Sep 27 10:38:27 zero kubelet-wrapper[1984]: E0927 08:38:27.832509    1984 pod_workers.go:184] Error syncing pod ecb3604a-83e7-11e6-a887-0050560c9557, skipping: failed to SyncPod: failed to set up pod network: failed to find plugin "calico" in path [/opt/cni/bin /opt/flannel/bin]
```

In the hyperkube image : 

```
docker run quay.io/coreos/hyperkube:v1.4.0_coreos.0 ls /opt/cni/bin/                                                                                      bridge                                                                                                                                                               cnitool                                                                                                                                                              dhcp
flannel
host-local
ipvlan
loopback
macvlan
noop
ptp
tuning
```

**Comment by gurvindersingh** [comment]
Yeah I have been hit by the same, I wonder if the shipping jenkins(building tool) has this issue, as there was same issue in earlier releases too as mentioned in referred issues above.

**Comment by TaiSHiNet** [comment]
For reference: calico and calico-ipam _should_ be included

**Comment by aaronlevy** [comment]
It looks like the hyperkube build paths may have changed and the calico binaries are not being included. /cc @tomdee

**Comment by tomdee** [comment]
I'm looking into this now

**Comment by aaronlevy** [comment]
There is a new hyperkube image which contains the fix: quay.io/coreos/hyperkube:v1.4.0_coreos.0

All hyperkube images for reference: https://quay.io/repository/coreos/hyperkube?tab=tags

We will update this repo to use the new image soon, but in the interim you can set the version:

vagrant/generic:
KUBERNETES_VER=v1.4.0_coreos.1

kube-aws (cluster.yaml):
kubernetesVersion=v1.4.0_coreos.1

**Comment by TaiSHiNet** [comment]
calico-ipam is still missing, blocking from a clean full-calico implementation.
Would it be possible to include it? (either now or next minor release)

BEsts

**Comment by tomdee** [comment]
@TaiSHiNet It's still an old version of the Calico CNI plugin that's being bundled. The old (python) version of the plugin doesn't actually need the separate `calico-ipam` file (it's actually inside the other plugin). We'll get this updated to the new go version of the Calico CNI plugin soon.

**Comment by ArchiFleKs** [comment]
Hi, thanks for the heads up and the version bump. Is there a documention / jobs description on how the hyperkube image is built ? To check how and which plugins are included ?

**Comment by tomdee** [comment]
This was the change that fixed the plugin location - https://github.com/coreos/kubernetes/pull/86 - that's probably a good place to start

**Comment by ArchiFleKs** [comment]
Thanks a lot, do you know what the hold up is on upgrading the plugin to the latest release go version ?

**Comment by tomdee** [comment]
Just finding the time to do it. There are some changes to at least the default CNI config that we want to give to users so I need to think a little more about how to handle that.

**Comment by aaronlevy** [comment]
Closing as it seems the original issue has been resolved.
