### ISSUE TITLE
Support TLS-enabled etcd for Vagrant/generic scripts

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#694]
In order to use the generic scripts in a production environment, the project should support configuring etcd with TLS. Some changes I think would need to be made:
- Vagrantfile need to generate the etcd certs just like the Kubernetes certs
- Vagrantfile needs to set env vars with their locations
- worker and controller script need to consume the env vars and pass to API server. Probably support having them unset by default if someone wants to opt out of TLS.

**Comment by aaronlevy** [comment]
Gonna close this as dupe of https://github.com/coreos/coreos-kubernetes/issues/104
