### ISSUE TITLE
glusterfs mount on coreos using special docker container - problem with monitoring in kubernetes

### ISSUE THREAD

**Issue by Rastusik** [coreos/coreos-kubernetes#696]
Hi, I'm not sure whether this is the right place to post the problem, but the main problem is kubernetes running specifically on coreos, so I'll give it a try.

I was able to mount a glusterfs filesystem into coreos using this guide: https://huaminchen.wordpress.com/2015/06/09/share-hosts-mount-namespace-with-docker-containers/ with some modifications - I needed to use shared volume mounts with docker.

To be able to run the whole thing, I needed to change the MountFlags parameter in the systemd config of docker.service to 'shared'

```
MountFlags=shared
```

Then I was able to run this docker image to be able to mount the glusterfs from within the docker container:

```
docker run --privileged --net=host  -v /:/host:shared -i -t centos bash
```

From within the container I just installed the glusterfs tools and mounted the glusterfs volume onto a directory from the /host path, so it would be usable from within the VM.

That actually worked, but with 2 drawbacks:

1) I'm not able to stop the container, even after manually unmounting the glusterfs volume from within the container, the process just hangs. To be able to clearly unmount, I need to stop kubelet and docker in coreos and restart the vhole VM (btw dockker stops at least a minute this way).. this is a problem but I can somehow live with it

2) I am able to use the mount point in kubernetes pods using hostpath volumes, BUT: there is a problem with getting monitoring data from the kubernetes heapster pod into the influxdb-grafana pod (no idea why, I use the standard config from kubernetes repo) - node data is being collected from every node, but there is no new data from the running pods - it's not being written, even the pod names of the newly created pods are missing... I think there is also a problem with writting logs into the ES-Kibana pods (also standard setup from the kube repo), but at first I need to solve the monitoring.

This happens when I run the mounter docker on coreos start slightly before the kubelet process starts. I realized, that when I run the mounter docker after kubelet process starts and after some basic kubernetes containers are online - in this cas the monitoring data of the pods is being logged from heapster into influxdb. I suppose there is some magic being done with the mounts after kubelet starts, but I have no idea what that is and what to do about, and I also have no idea how to run the mounter docker after kubelet, but after all the mounting magic happens (I was also able to run the mounter right after kubelet started, using systemd ExecAfter, but it still was too soon for some reason...)

Could anybody help me understand what's under the hood or maybe suggest a solution of the problem? Maybe there's a cleaner way to mount glusterfs on coreos, but I haven't found any. Is there? This solution works almost perfectly, but still just 95% good... I just realized that after a week of usage, everything worked like a charm, except monitoring of the pods and some logging.

I'm using the current stable version of coreos - 1222.2.0, and kubernetes 1.3.5 (v1.3.5+coreos.0)

**Comment by Rastusik** [comment]
So, if someone would be interested, I 'fixed' this with a temporary workaround, I created a systemd glusterfs-fix.service with this definition:

```
[Unit]
Description=glusterfs-fix
After=docker.service kubelet.service
Requires=docker.service kubelet.service

[Service]
User=core
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker rm glusterfs-fix
ExecStartPre=/usr/bin/docker pull  pixelfederation/coreos-glusterfs-client:1.0
ExecStart=/home/core/bin/glusterfs-fix
ExecStop=/usr/bin/docker stop glusterfs-fix

[Install]
WantedBy=multi-user.target
```

while these are the contents of the **/home/core/bin/glusterfs-fix** file:

```
#!/bin/bash

while [[ $(docker ps | wc -l) == "1" ]]; do sleep 1; done && /usr/bin/docker run --name glusterfs-fix --privileged --net=host -v /:/host:shared pixelfederation/coreos-glusterfs-client:1.0
```

**Comment by somejfn** [comment]
Hi Martin,

Out of curiosity,  is there a specific reason to propagate a mount from the
host down to the container instead of using the Kubernetes glusterfs plugin
for that POD ?    As documented here:
http://kubernetes.io/docs/user-guide/volumes/#glusterfs

regards,

Jfn

**Comment by Rastusik** [comment]
@somejfn well, the reason is obvious I suppose (or I didn't understand something) - regarding this guide: https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/glusterfs I need to have glusterfs client installed on the kubernetes nodes.

> The example assumes that you have already set up a Glusterfs server cluster and the Glusterfs client package is installed on all Kubernetes nodes.

But I don't know how to install glusterfs client on the coreos nodes (on which kubernetes is running). Did I not understand anything from the guide or is there a way to install glusterfs client on coreos and I didn't find it?

**Comment by somejfn** [comment]
Normally the kubelet performs the mount action for the POD you want the
volume allocated so you don't have to mount the FS on all the Kubernetes
hosts your POD could potentially end running. I used the nfs plugins that
way and since the NFS client is built into the kernel there is no need for
a client to be installed in coreos.

I don't know specifically about gluster,  but it may be a case where the
kubelet need some client bin/libs to perform the mount action and doesn't
find it on coreos.   In this case the mount would fail and you'd find the
error in the kubelet logs.

**Comment by Rastusik** [comment]
yes, that's exactly the problem, kubelet doesn't find glusterfs client libs, because they aren't there. I don't want to use nfs because it's slow and it is not scalable comparing to glusterfs.

So the only workaround hack I was able to find was this - run a docker container with glusterfs client with a volume mounted in shared mode (docker volume flag). The docker container mounts the glusterfs filesystem into the shared volume, which is accessible from the host VM. Then I'm using HostPath volumes in Kubernetes, which point to the shared mount point ... It's an ugly hack, but it works and is way faster comparing to nfs.

**Comment by somejfn** [comment]
I remember a similar problem with Ceph and a solution was to use a
container to alias the rbdmap command.  So the kubelet was able to find
"rbdmap" and mount the volume for the POD.  Maybe the same could work for
Gluster and avoid the hostPath hack.

**Comment by Rastusik** [comment]
yes, I was also considering this idea, but I haven't found any information regarding how to do it ... or it more complicated than the hostpath solution... could you show me an example of the rbdmap command aliasing? I could try to reproduce it with glusterfs

**Comment by somejfn** [comment]
Was:

cat /opt/bin/rbd

#!/bin/sh
exec docker run -v /etc/ceph:/etc/ceph ceph/rbd $@

**Comment by Rastusik** [comment]
I can't quite see how kubelet is able to access the ceph ... does this alias create a mount on the host? I suppose not... So is the ceph connection created in the docker context which is then somehow accessible to kubelet through k8s docker containers?

This looks like magic to me :)

**Comment by robszumski** [comment]
Newer 1.4.x hyperkube images should have all of the required client tools to mount storage for you: https://github.com/coreos/coreos-kubernetes/blob/3f25cfebc929c62ab41bc7af6ad8d1e6fad7c283/Documentation/kubelet-wrapper.md#allow-pods-to-use-rbd-volumes

**Comment by Rastusik** [comment]
So I don't need to install anything and just create a glusterfs persistent volume in kubernetes and the volume will be created? That would help quite a lot... or do you only mean rbd/ceph?

**Comment by pcm32** [comment]
@Rastusik did this work for you by just creating the PV for Gluster on kubernetes 1.4.x?

**Comment by Rastusik** [comment]
@pcm32 no it didn't ... I'm getting this error:

```
MountVolume.SetUp failed for volume "kubernetes.io/glusterfs/acbe81ea-8fbf-11e6-8d12-fa163e5ec993-gluster-pv" (spec.Name: "gluster-pv") pod "acbe81ea-8fbf-11e6-8d12-fa163e5ec993" (UID: "acbe81ea-8fbf-11e6-8d12-fa163e5ec993") with: glusterfs: mount failed: mount failed: exit status 32
Mounting arguments: 10.254.0.10:kube_vol1 /var/lib/kubelet/pods/acbe81ea-8fbf-11e6-8d12-fa163e5ec993/volumes/kubernetes.io~glusterfs/gluster-pv glusterfs [log-level=ERROR log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/gluster-pv/test-2703916870-ru9e0-glusterfs.log]
Output: mount: unknown filesystem type 'glusterfs'
```

I think @robszumski meant that kubelet is now able to mount RBD and iSCSI volumes, not glusterfs volumes

**Comment by Rastusik** [comment]
@pcm32 thanks!

**Comment by aaronlevy** [comment]
Going to close this as I believe the underlying issue has been resolved (glusterfs tools are included in quay.io/coreos/hyperkube:v1.4.3+coreos.0 and newer. See https://github.com/coreos/kubernetes/releases for all hyperkube releases.

If this needs to be re-opened please let me know
