### ISSUE TITLE
kubelet-wrapper possible option problem

### ISSUE THREAD

**Issue by TerraTech** [coreos/coreos-kubernetes#706]
I'm not sure if this is a problem, but I noticed the following at:
https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/worker-install.sh#L84-L85
https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh#L118-L119

Where the cluster options were specified as:
--cluster_dns and --cluster_domain

Should that be using a hyphen instead of an underscore?
--cluster-dns and --cluster-domain

**Comment by pbx0** [comment]
This shouldn't cause a problem, it looks like we just never migrated to the new flag style for these flags.  I have a fix pending here: https://github.com/coreos/coreos-kubernetes/pull/711

**Comment by TerraTech** [comment]
@pbx0 Thank you.
