### ISSUE TITLE
kubectl exec - worker cert issue

### ISSUE THREAD

**Issue by ndobson** [coreos/coreos-kubernetes#73]
When using the OpenSSL documentation running kubectl exec produces the following error:
```
kubectl --insecure-skip-tls-verify=false exec busybox -- nslookup kubernetes
error: Unable to upgrade connection: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "x509: certificate is valid for kube-worker, not coreos03",
  "code": 500
}
```
As an insecure workaround I generated the worker csr like so:
```
openssl req -new -key worker-key.pem -out worker.csr -subj "/CN=*"
```

**Comment by hunter** [comment]
We're running into a similar issue with `exec`

```
error: Unable to upgrade connection: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "x509: cannot validate certificate for 172.31.129.X because it doesn't contain any IP SANs",
  "code": 500
}
```

**Comment by polvi** [comment]
We are planning to upgrade the doc to show the `openssl req -new -key worker-key.pem -out worker.csr -subj "/CN=*"` work-around as well as document the "right" way to do it by generating a key for every worker. @hunter @ndobson does that sound like a reasonable approach to you? Any other ideas?

**Comment by ndobson** [comment]
@polvi It could, but also note that the `subj "/CN=*"` approach only works if you change the `--hostname-override=${ADVERTISE_IP}` option from the kubelet of each worker and let the kubelet register itself as a resolvable hostname.

Otherwise, as @hunter demonstrates above, if you try to connect to the worker by ip the cert has to have an IP SAN entry matching that specific ip.

**Comment by polvi** [comment]
Another solution could be to use ssh. I'm pretty sure the apiserver can connect over SSH, but that would require setting up SSH infrastructure as well as x509. Any thoughts on that?

**Comment by bcwaldon** [comment]
This is handled by the AWS installer (multi-node/aws) by adding *.ec2.internal and *.<region>.cluster.internal SANs

**Comment by ntquyen** [comment]
@ndobson I'm having the same problem and have little experience in ssl. Can you please give me more instruction on generating new worker csr? I'm using multi-node for development.

**Comment by hosh** [comment]
@ntquyen  I am trying to figure this out too. I have a cluster on AWS with the hostname override off. I don't know much about SSL either, and have been piecing it together from the scripts in the vagrant and aws startup code. My initial try looks like this:

```
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = *.compute..internal
DNS.4 = *.cluster.local
```

But reading https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/cmd/kube-aws/command_up.go#L209-L212 I am going to try

```
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = *.*.compute..internal
DNS.4 = *.ec2.internal
DNS.5 = *.*.*.cluster.local
```

**Comment by hosh** [comment]
@ntquyen ok I tried a bunch of things. This is what finally works.

I put this into `worker.cnf`
```
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = *.*.compute.internal
DNS.4 = *.ec2.internal
```

Assuming I already have `worker-key.pem` this is how I generated the certs:

```
openssl req -new -key worker-key.pem -out worker.csr -subj "/CN=kube-worker" -config worker.cnf
openssl x509 -req -in worker.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out worker.pem -days 365 -extensions v3_req -extfile worker.cnf
```

I found out you can check the contents of the cert to make sure the SANs (alternate names) are there:

```
openssl x509 -in worker.pem -text -noout
```

Installed, killed kubelet and the proxy, and I'm able to `kubectl exec` now. Good luck

**Comment by ntquyen** [comment]
@hosh I already solved this problem, thanks to the commit by @aaronlevy, but thank you anyway for posting the solution here, that will help many other folks!

**Comment by drocsid** [comment]
Should this issue really be closed when the openSSL certificate generation documentation hasn't been updated?

**Comment by rwehner** [comment]
I'd agree that this issue isn't fully addressed until the [openssl docs](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/openssl.md) show how to create per-worker certs with the correct IPs (similar to how the master certs are documented).

**Comment by esecules** [comment]
what would be a more generic solution for any cluster outside of AWS, something similar to what @hosh came up with?

**Comment by rwehner** [comment]
@esecules I've thrown up a  PR (https://github.com/coreos/coreos-kubernetes/pull/170) that updates the docs with what I think a more generic solution might look like. A similar approach (in my case automated with Ansible) has worked for my on-premise, bare-metal clusters.

@aaronlevy: perhaps this PR can be a starting point for how the docs might look?

**Comment by aaronlevy** [comment]
Closing now that #170 has landed. Please let me know if there are any other concerns with this / needs to be re-opened.
