### ISSUE TITLE
Can't SSH controller / workers

### ISSUE THREAD

**Issue by geostant** [coreos/coreos-kubernetes#752]
Hello,

After deploying my cluster to AWS with an existing key from my AWS pairs
I can't SSH any of the machines and being prompt to a password.

CloudFormation successfully provision the whole orchestration (VPC, Subnets, Controller and Workers).

I've tried as well with a brand new key (uploaded it to AWS prior to `kube-aws up`, but that didn't helped)
On the AWS console I can see my cluster and in the EC2 info I can see that the proper key that I've set during the render match to my need.

All interaction with the cluster thru `kubectl` works flawlessly
 
Any one else had such issue ?

**Comment by mumoshu** [comment]
@geostant Hi!

Excuse me if I'm missing the point but could you try using the `core` user i.e. run the command like `ssh -i path/to/your/key core@<public ip/hostname>`?

**Comment by kruunch** [comment]
I'm having the same issue as @geostant 

@mumoshu adding the user 'core' to the ssh call still invokes a password challenge (even if the key isn't password protected)

**Comment by mumoshu** [comment]
@kruunch Could you double-check that (1) you did specify not a public but a private key with a valid permission (2) and the private key is the one paired to the name of the EC2 key pair associated to EC2 instances i.e. `keyName`?

**Comment by kruunch** [comment]
@mumoshu that was it (my private key wasn't matching with the public one we had stored in AWS)

After fixing that issue and running the command below worked:

ssh -i ~/.ssh/my_key core@instance_ip

 Sorry for the trouble.
