### ISSUE TITLE
apiserver is not available at startup first time

### ISSUE THREAD

**Issue by shenshouer** [coreos/coreos-kubernetes#76]
Kubelet can not create the service pods of apiserver, podmaster and kube-proxy from /etc/kubernetes/manifests/:

<pre>
Sep 23 04:23:10 c1 kubelet[1218]: E0923 04:23:10.172129    1218 reflector.go:136] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:10 c1 kubelet[1218]: E0923 04:23:10.516622    1218 kubelet.go:1641] error getting node: node 172.17.4.101 not found
Sep 23 04:23:11 c1 kubelet[1218]: E0923 04:23:11.173514    1218 reflector.go:136] Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:11 c1 kubelet[1218]: E0923 04:23:11.174512    1218 reflector.go:136] Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:11 c1 kubelet[1218]: E0923 04:23:11.175847    1218 reflector.go:136] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:12 c1 kubelet[1218]: E0923 04:23:12.175900    1218 reflector.go:136] Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:12 c1 kubelet[1218]: E0923 04:23:12.177491    1218 reflector.go:136] Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:12 c1 kubelet[1218]: E0923 04:23:12.177850    1218 reflector.go:136] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:13 c1 kubelet[1218]: E0923 04:23:13.179284    1218 reflector.go:136] Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:13 c1 kubelet[1218]: E0923 04:23:13.186413    1218 reflector.go:136] Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:13 c1 kubelet[1218]: E0923 04:23:13.186447    1218 reflector.go:136] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:13 c1 kubelet[1218]: E0923 04:23:13.206073    1218 event.go:194] Unable to write event: 'Post http://127.0.0.1:8080/api/v1/namespaces/kube-system/events: dial tcp 127.0.0.1:8080: connection refused' (may retry after sleeping)
Sep 23 04:23:14 c1 kubelet[1218]: E0923 04:23:14.188419    1218 reflector.go:136] Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:14 c1 kubelet[1218]: E0923 04:23:14.189941    1218 reflector.go:136] Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
Sep 23 04:23:14 c1 kubelet[1218]: E0923 04:23:14.190631    1218 reflector.go:136] Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101: dial tcp 127.0.0.1:8080: connection refused
</pre>

and none containers up:
<pre>
core@c1 /etc/systemd/system $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
core@c1 /etc/systemd/system $
</pre>

**Comment by shenshouer** [comment]
Sorry for this report!
I know the problem.

**Comment by aaronlevy** [comment]
It can take a few minutes to download all of the required containers. I've opened an issue for us to better document how to inspect the bootstrap process.

**Comment by kalona** [comment]
Hi,

do you have a solution for this?

Thanks.
