### ISSUE TITLE
release 0.8.3 fails GPG check

### ISSUE THREAD

**Issue by rgcosma** [coreos/coreos-kubernetes#763]
gpg: BAD signature from "CoreOS Application Signing Key <security@coreos.com>"
Downloaded 0.8.2, that one validates fine

**Comment by aaronlevy** [comment]
/cc @brianredbeard @colhom 

Also, a side note @rgcosma, the kube-aws tool has moved to its own top-level repository @ https://github.com/coreos/kube-aws

**Comment by colhom** [comment]
@rgcosma which tarball/sig combination are you seeing this with?

**Comment by rgcosma** [comment]
Hi - might have been a temporary issue, and sorry for not saving the file locally at the time. I did download it twice yesterday, though, no proxy..
Right now, for https://github.com/coreos/coreos-kubernetes/releases/download/v0.8.3/kube-aws-linux-amd64.tar.gz
$ gpg2 --verify 083.sig 083.tgz
gpg: Signature made Wed 19 Oct 2016 21:35:12 UTC using RSA key ID BEDDBA18
gpg: Good signature from "CoreOS Application Signing Key <security@coreos.com>"

**Comment by rgcosma** [comment]
thank you @aaronlevy will use the new repo
