### ISSUE TITLE
Cluster lost if controller node fails ?

### ISSUE THREAD

**Issue by robinmonjo** [coreos/coreos-kubernetes#765]
Hello all,

I deployed a cluster and noticed something. The etcd "cluster" is not a cluster, as etcd only runs on the controller node. Plus etcd data store is located on an ephemeral disk (if the instance terminates, the disk is destroyed and all the cluster configuration will be lost).

I see that a cluster deployed with Kubernetes' `kupe-up` command also as a single node etcd cluster, but etcd data store is on a disk that is not destroyed if instance terminates.

In my setup, I don't need the controller node to be highly available. If it dies, my application pods will keep running on my workers and my end users won't experience downtime. However, what happens if my master node dies ? It seems that I won't be able to restart it properly and my workers will be left without master forever ...

**Comment by pieterlange** [comment]
Hi @robinmonjo. What version and configuration did you use?

Note that in recent versions of `kube-aws` etcd is deployed as separate cluster - you can configure how many nodes to spin up, as well as the node type. In the [new kube-aws repo](https://github.com/coreos/kube-aws) we're also working on new functionality regarding etcd availability/backups.

**Comment by robinmonjo** [comment]
Hi,

Sorry wrong repo ! This is the first result in google for `kube-aws`, not the first time I do the mistake :). I deployed using version `0.8.2` and following this guide: https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html.

I didn't tweak the configuration much, just made the certificates last 10 years and deployed workers in 2 availability zones. Sorry for the noise, I'll close this issue and dig more into custom configuration.

**Comment by pieterlange** [comment]
No problem :)

I'm actually working on making it easier to integrate with externally managed etcd solutions so operators can decide themselves on how to manage cluster state. I personally like https://crewjam.com/etcd-aws/, which i utilize through https://github.com/pieterlange/kube-aws/tree/feature/external-etcd which should be merged relatively soon after i work out some minor bugs.

**Comment by robinmonjo** [comment]
Perfect, thank you for this information. I'll will have a look once this is merged then.
