### ISSUE TITLE
Stop manually creating `kube-system` namespace if not needed

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#773]
I wish on `coreos.com/kubernetes/docs/latest/deploy-master.html`

> I wish this page upgrade to get along well with recent version. k8s1.3 and later doesn't need to setup kube-system namespace

**Comment by alekssaul** [comment]
https://github.com/coreos-inc/tectonic/pull/1196 removes it from the documentation. Noticed the same while testing, it. Don't think we need to curl create the namespace.

**Comment by pbx0** [comment]
We don't do this anymore in the scripts either.
