### ISSUE TITLE
Request release of quay.io/coreos/hyperkube:v1.4.7_coreos.0

### ISSUE THREAD

**Issue by Demotivated** [coreos/coreos-kubernetes#778]
Kubernetes [v1.4.7](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v147) is out, can we get a hyperkube release? Thanks!

**Comment by sysit** [comment]
You can find all hyperkube for coreos here:
https://quay.io/repository/coreos/hyperkube?tab=tags

**Comment by rdtr** [comment]
And actually already v1.5.0 is out😅

**Comment by Demotivated** [comment]
@rdtr missed v1.5.0 by a few hours... This is excellent! Thanks!
