### ISSUE TITLE
docs: Add information about inspecting bootstrap process

### ISSUE THREAD

**Issue by aaronlevy** [coreos/coreos-kubernetes#78]
The initial bootstrap of kubernetes components can make it seem like the cluster isn't working initially (api not available, or kubelet log complaining).

We should add more documentation about trouble-shooting, inspecting the bootstrap state. e.g. see tickets for context:

https://github.com/coreos/coreos-kubernetes/issues/76
https://github.com/coreos/coreos-kubernetes/issues/63

**Comment by jojimt** [comment]
Is there manual work-around to start the apiserver? I see that the docker image is downloaded, but the apiserver is not started.
