### ISSUE TITLE
Use DaemonSet for kube-proxy

### ISSUE THREAD

**Issue by Bekt** [coreos/coreos-kubernetes#784]
Is there any reason why DaemonSet would not be suitable for kube-proxy since the pod definition is identical on both the controller and worker nodes?

**Comment by rdtr** [comment]
Wouldn't it be safer to use DaemonSet after DaemonSet supports `kubectl update` command ?

**Comment by Bekt** [comment]
👍 

Makes sense, I didn't know DaemonSet currently doesn't support `kubectl update/apply`.
