### ISSUE TITLE
Simplify ExternalDNSName management

### ISSUE THREAD

**Issue by bcwaldon** [coreos/coreos-kubernetes#83]
When using kube-aws, you are required to provide an `externalDNSName`, which is a DNS name you are expected to make routable to the controller instance. This is helpful, but is a very clunky way of making your cluster externally accessible. Additionally, the documentation is rather sparse and expects you to know what you're doing.

The main reason this exists is so the apiserver TLS certificate is valid for an external name before it is copied into the cluster.

This is clearly clunky, and could be simpler from the perspective of the deployer.

**Comment by trcook** [comment]
+1 on this. I've been staring at the doc for this for a while and I can't make any sense of what I'm supposed to enter in for this. There are only a few lines given to this parameter in the docs and they are cryptic. Plus, the need for an external facing DNS does not really appear in any of the other guides for deploying coreos+kubernetes -- at least not as far as i can tell...

**Comment by robszumski** [comment]
"I wish" from coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html

> I wish this page explained my-cluster-endpoint better! See https://github.com/coreos/coreos-kubernetes/issues/194

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
