### ISSUE TITLE
Deploy kubelets with authn + authz

### ISSUE THREAD

**Issue by euank** [coreos/coreos-kubernetes#844]
Followup to https://github.com/coreos/coreos-kubernetes/pull/842 / https://github.com/coreos/coreos-kubernetes/issues/656

The api-requests from the kube-apiserver to the kubelet should be properly authn/authz'd in a cluster created either from the documentation or the scripts in this repository.

Basically, it's making sure we get the knobs mentioned [here](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#overview) right.

**Comment by philips** [comment]
This is the same discussion @dghubble @ericchiang @aaronlevy @sym3tri and I had yesterday.

**Comment by euank** [comment]
This repo hasn't been maintained for a while, closing.
