### ISSUE TITLE
Use service account in DNS addon

### ISSUE THREAD

**Issue by bcwaldon** [coreos/coreos-kubernetes#9]
The DNS addon currently uses a kubeconfig to configure itself with access to the cluster. Ideally, it would use a service account, and the kubeconfig object would be unnecessary.

This is blocked on https://github.com/kubernetes/kubernetes/issues/13411.

**Comment by aaronlevy** [comment]
This was fixed in https://github.com/coreos/coreos-kubernetes/pull/21
