### ISSUE TITLE
CoreOS hyperkube v1.9.0_coreos.0: No ipset utility, IPVS proxy mode fails

### ISSUE THREAD

**Issue by ivanilves** [coreos/coreos-kubernetes#915]
hyperkube `v1.9.0_coreos.0` does not have ipset utility installed, IPVS proxy mode fails.

Proxying this as CoreOS hyperkube image has the same issue: https://github.com/kubernetes/kubernetes/issues/57321

This is the fix:
https://github.com/kubernetes/kubernetes/commit/787a55bb67ccd2da14aa6e7f91289c859beecb5f#diff-bf0f8d724d18f700f3c821aa5a74f4cf

:bulb: Could we publish a new version of CoreOS hyperkube v1.9.0 with ipset installed? :pray: 

Thanks!

**P.S.:**
Meanwhile I've put a fixed image in `ivanilves/hyperkube:v1.9.0_coreos.0` https://hub.docker.com/r/ivanilves/hyperkube/

**Comment by ericchiang** [comment]
Any idea why https://github.com/kubernetes/kubernetes/pull/56115 wasn't cherry picked to 1.9?

**Comment by ivanilves** [comment]
No idea. :disappointed: 

FYI hyperkube build from gcr.io should have it cherry-picked. Read more:
https://github.com/kubernetes-incubator/kube-aws/pull/1104

**Comment by rphillips** [comment]
It looks like the upstream PR https://github.com/kubernetes/kubernetes/pull/57648 has not been merged yet.

**Comment by christianhuening** [comment]
I would appreciate a new hyperkube image with ipset as well

**Comment by christianhuening** [comment]
Ok so https://github.com/kubernetes/kubernetes/pull/57648 is finally approved and merged. How do we get a hyperkube image with ipset included?

**Comment by rphillips** [comment]
We should try and get the change cherry picked into the 1.9 branch for the next release cycle.

**Comment by christianhuening** [comment]
any updates here @rphillips ?

**Comment by rphillips** [comment]
@christianhuening this should now be fixed in the later 1.9 releases... Can you verify the tool is present in the latest release, so we can close out this issue?

**Comment by christianhuening** [comment]
@rphillips Well I am running  `coreos/hyperkube:v1.9.6_coreos.0` now, and I cannot find ipset in it. It should be at `/sbin/ipset` right?

**Comment by rphillips** [comment]
@christianhuening there was a bug in the 1.9 release that didn't pull in the right image to get this fixed. It is fixed in 1.10, though the hyperkube image is not ready yet. https://github.com/kubernetes/kubernetes/pull/61357 is pending to add udev which would bump the image again. I'm sorry about the churn on this, but I will get this straightened out. If you can use 1.10, please keep your eye out for the image.

**Comment by christianhuening** [comment]
thanks @rphillips ! Already planning the 1.10 update, would be great to have 'em in there!

**Comment by rphillips** [comment]
@christianhuening the 1.10 image was pushed!

**Comment by christianhuening** [comment]
@rphillips thanks! will test!

**Comment by rphillips** [comment]
ipset still isn't in the 1.10 release. The PR is still pending... https://github.com/kubernetes/kubernetes/pull/61861

**Comment by rphillips** [comment]
The upstream PR just merged... This fix will be in the next 1.10 release.

**Comment by PabloCastellano** [comment]
I have just checked that the `ipset` binary is present in v1.9.11_coreos.0

```
$ docker run --rm -ti quay.io/coreos/hyperkube:v1.9.11_coreos.0 ipset
ipset v6.30: No command specified.
Try `ipset help' for more information.
```

I think we can close this issue now @ivanilves

**Comment by ivanilves** [comment]
Yes @PabloCastellano indeed. Thank you!
