### ISSUE TITLE
No hyperkube for v1.7.12?

### ISSUE THREAD

**Issue by jonaz** [coreos/coreos-kubernetes#917]
What decides when hyperkube is built? 
Trying to upgrade from 1.6.13 to 1.7.12 on a baremetal install but 1.7.12 it missing from coreos/hyperkube repo. 

https://quay.io/repository/coreos/hyperkube?tab=tags

**Comment by ericchiang** [comment]
cc @rphillips

**Comment by rphillips** [comment]
on it.

**Comment by rphillips** [comment]
pushed to quay.io
