### ISSUE TITLE
docs: provide instructions for configuring kubectl with AWS

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#97]
Provide instructions for how to set up kubectl with a context from the generated `./clusters/<cluster-name>/kubeconfig` file. Ideally `kube-aws` can merge this file with the default `~/.kube/config`, or sets the appropriate env vars for `kubectl` to find it automatically.

The instructions become something like:

<hr>

A kubectl config file will be written to `./clusters/<cluster-name>/kubeconfig`, **which is referenced automatically by the cluster name configured earlier.**

**`kubectl` can switch between multiple "contexts", which is a combination of user credentials and cluster information. Switch to your new cluster's context and then list the nodes:**

```
$ kubectl config use-context ${CLUSTERNAME}
$ kubectl get nodes
NAME                         LABELS                                              STATUS
ip-10-0-0-223.ec2.internal   kubernetes.io/hostname=ip-10-0-0-223.ec2.internal   Ready
ip-10-0-0-224.ec2.internal   kubernetes.io/hostname=ip-10-0-0-224.ec2.internal   Ready
ip-10-0-0-225.ec2.internal   kubernetes.io/hostname=ip-10-0-0-225.ec2.internal   Ready
```

**Comment by wolfeidau** [comment]
I managed to get a cluster up and running on AWS.

Some notes from this:

* Clone the project into your gopath so you can build `kube-aws`
* Run `godep restore`
* Then you can build the project

If for any reason creation of the cluster fails you will need to `rm -rf clusters` as it can't deal with existing files..

Instances sizes were a bit big for a demo environment so I had to modify the `artifacts/template.json`.

It isn't entirely clear how S3 is used for artifacts, I only had to upload the template.json to s://whatver.s3.amazonaws.com/(GIT HASH)/template.json to get it running.

Also need a note on how to authenticate and access the cluster using it's public IP.

Cheers

**Comment by robszumski** [comment]
Related, a website "I wish" refers to removing the vagrant specific naming on coreos.com/kubernetes/docs/latest/configure-kubectl.html

> I wish this page didn't have instructions that refer to vagrant

**Comment by aaronlevy** [comment]
Given that the kube-aws instructions have changed quite a bit since the time of filing, I'm going to close this issue. Please re-open if this is something that still needs to be addressed.
