### ISSUE TITLE
allow ABAC authorization mode

### ISSUE THREAD

**Issue by JeanMertz** [coreos/coreos-kubernetes#98]
Even though the API endpoint can be TLS secured, service accounts currently have full access to the entire cluster and all its API endpoints. Meaning, if a single pod/container is compromised, everything is.

We're currently doing this manually (by having our own artefacts based on the ones in this repository), but it would be nice if it was possible to define the [authorization plugin](https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/admin/authorization.md) to use.

**Comment by aaronlevy** [comment]
Hi @JeanMertz,
You should be able to modify the flags passed to the apiserver in the aws/vagrant/generic installs. It will require editing the api-server manifest, but there is nothing that would disallow using ABAC authrorization mode.

For example, you could add the `--authorization-mode=ABAC` and `--authorization-policy-file=SOME_FILENAME` to the api-server manifest for kube-aws: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/artifacts/manifests/controller/kube-apiserver.yaml#L14-L25

Then follow the instructions for deployment using custom manifests: https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws#custom-kubernetes-manifests

Also note, the policy file you specify would need to be deployed to your master nodes (where apiserver is running).

**Comment by aaronlevy** [comment]
Closing this issue, but please re-open if you're still having trouble.
