### ISSUE TITLE
Authentication Code Generation to API Endpoints [Doc]

### ISSUE THREAD

**Issue by lucmichalski** [coreos/coreos-kubernetes#99]
Hey,

Can you write a description on how to access the KUBE-UI with any of the Authentication options of Kubernetes ? How to generate and get the tokens ?

Cheers,
Luc Michalski

**Comment by aaronlevy** [comment]
Can you provide a little more detail on the issue you are having?

In general, the UI application should know how to connect to the kubernetes API (via service accounts). And when you are accessing the UI it is done by proxying your request to the pod running the UI (via a kubernetes service).

Maybe as a start, what happens when you go to `https://<kubernetes-master>/ui` ?

**Comment by sdval** [comment]
I'm experiencing the same issue.

```
$ curl https://172.17.4.99/ui -k                                                                                                                            
Unauthorized
```

Very interested in how to hit the https:// endpoints.

**Comment by aaronlevy** [comment]
The easiest way is to make use of `kubectl proxy`. This will open a local proxy to your kubernetes cluster by using the current context in your kubeconfig. As long as your kubeconfig is configured to properly connect to your cluster, the proxy command will take care of authenticating the connection using client certs.

See: http://kubernetes.io/v1.0/docs/user-guide/connecting-to-applications-proxy.html

To use curl directly you will need to specify a client cert to authorize the request. The exact flags can vary depending on platform, but from OSX 10.10 you will need to convert your admin cert to pk12 first:

From the `single-node` directory:

```
openssl pkcs12 -export -in ./ssl/admin.pem -inkey ./ssl/admin-key.pem -out ./ssl/admin.p12
```

Then use the cert in the curl request:

```
curl https://172.17.4.99/v1/api/nodes --cacert ./ssl/ca.pem --cert ./ssl/admin.p12
```

**Comment by aaronlevy** [comment]
Going to close this issue, but if you are still having difficulty, please re-open
